// Code generated by ent, DO NOT EDIT.

package financialauditlog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the financialauditlog type in the database.
	Label = "financial_audit_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAuditID holds the string denoting the audit_id field in the database.
	FieldAuditID = "audit_id"
	// FieldAction holds the string denoting the action field in the database.
	FieldAction = "action"
	// FieldActorType holds the string denoting the actor_type field in the database.
	FieldActorType = "actor_type"
	// FieldActorUserID holds the string denoting the actor_user_id field in the database.
	FieldActorUserID = "actor_user_id"
	// FieldRequestID holds the string denoting the request_id field in the database.
	FieldRequestID = "request_id"
	// FieldTxID holds the string denoting the tx_id field in the database.
	FieldTxID = "tx_id"
	// FieldReversalID holds the string denoting the reversal_id field in the database.
	FieldReversalID = "reversal_id"
	// FieldTargetType holds the string denoting the target_type field in the database.
	FieldTargetType = "target_type"
	// FieldTargetID holds the string denoting the target_id field in the database.
	FieldTargetID = "target_id"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeActorUser holds the string denoting the actor_user edge name in mutations.
	EdgeActorUser = "actor_user"
	// Table holds the table name of the financialauditlog in the database.
	Table = "financial_audit_logs"
	// ActorUserTable is the table that holds the actor_user relation/edge.
	ActorUserTable = "financial_audit_logs"
	// ActorUserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	ActorUserInverseTable = "users"
	// ActorUserColumn is the table column denoting the actor_user relation/edge.
	ActorUserColumn = "actor_user_id"
)

// Columns holds all SQL columns for financialauditlog fields.
var Columns = []string{
	FieldID,
	FieldAuditID,
	FieldAction,
	FieldActorType,
	FieldActorUserID,
	FieldRequestID,
	FieldTxID,
	FieldReversalID,
	FieldTargetType,
	FieldTargetID,
	FieldMetadata,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultAuditID holds the default value on creation for the "audit_id" field.
	DefaultAuditID func() uuid.UUID
	// ActionValidator is a validator for the "action" field. It is called by the builders before save.
	ActionValidator func(string) error
	// DefaultActorType holds the default value on creation for the "actor_type" field.
	DefaultActorType string
	// ActorTypeValidator is a validator for the "actor_type" field. It is called by the builders before save.
	ActorTypeValidator func(string) error
	// RequestIDValidator is a validator for the "request_id" field. It is called by the builders before save.
	RequestIDValidator func(string) error
	// TargetTypeValidator is a validator for the "target_type" field. It is called by the builders before save.
	TargetTypeValidator func(string) error
	// TargetIDValidator is a validator for the "target_id" field. It is called by the builders before save.
	TargetIDValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the FinancialAuditLog queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAuditID orders the results by the audit_id field.
func ByAuditID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuditID, opts...).ToFunc()
}

// ByAction orders the results by the action field.
func ByAction(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAction, opts...).ToFunc()
}

// ByActorType orders the results by the actor_type field.
func ByActorType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActorType, opts...).ToFunc()
}

// ByActorUserID orders the results by the actor_user_id field.
func ByActorUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActorUserID, opts...).ToFunc()
}

// ByRequestID orders the results by the request_id field.
func ByRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestID, opts...).ToFunc()
}

// ByTxID orders the results by the tx_id field.
func ByTxID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTxID, opts...).ToFunc()
}

// ByReversalID orders the results by the reversal_id field.
func ByReversalID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReversalID, opts...).ToFunc()
}

// ByTargetType orders the results by the target_type field.
func ByTargetType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetType, opts...).ToFunc()
}

// ByTargetID orders the results by the target_id field.
func ByTargetID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByActorUserField orders the results by actor_user field.
func ByActorUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newActorUserStep(), sql.OrderByField(field, opts...))
	}
}
func newActorUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ActorUserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ActorUserTable, ActorUserColumn),
	)
}
