// Code generated by ent, DO NOT EDIT.

package balancetransfer

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldLTE(FieldID, id))
}

// SenderID applies equality check predicate on the "sender_id" field. It's identical to SenderIDEQ.
func SenderID(v int64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldEQ(FieldSenderID, v))
}

// ReceiverID applies equality check predicate on the "receiver_id" field. It's identical to ReceiverIDEQ.
func ReceiverID(v int64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldEQ(FieldReceiverID, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldEQ(FieldAmount, v))
}

// Fee applies equality check predicate on the "fee" field. It's identical to FeeEQ.
func Fee(v float64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldEQ(FieldFee, v))
}

// FeeRate applies equality check predicate on the "fee_rate" field. It's identical to FeeRateEQ.
func FeeRate(v float64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldEQ(FieldFeeRate, v))
}

// GrossAmount applies equality check predicate on the "gross_amount" field. It's identical to GrossAmountEQ.
func GrossAmount(v float64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldEQ(FieldGrossAmount, v))
}

// TransferType applies equality check predicate on the "transfer_type" field. It's identical to TransferTypeEQ.
func TransferType(v string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldEQ(FieldTransferType, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldEQ(FieldStatus, v))
}

// Memo applies equality check predicate on the "memo" field. It's identical to MemoEQ.
func Memo(v string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldEQ(FieldMemo, v))
}

// RedpacketID applies equality check predicate on the "redpacket_id" field. It's identical to RedpacketIDEQ.
func RedpacketID(v int64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldEQ(FieldRedpacketID, v))
}

// FrozenAt applies equality check predicate on the "frozen_at" field. It's identical to FrozenAtEQ.
func FrozenAt(v time.Time) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldEQ(FieldFrozenAt, v))
}

// FrozenBy applies equality check predicate on the "frozen_by" field. It's identical to FrozenByEQ.
func FrozenBy(v int64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldEQ(FieldFrozenBy, v))
}

// RevokeReason applies equality check predicate on the "revoke_reason" field. It's identical to RevokeReasonEQ.
func RevokeReason(v string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldEQ(FieldRevokeReason, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldEQ(FieldCreatedAt, v))
}

// SenderIDEQ applies the EQ predicate on the "sender_id" field.
func SenderIDEQ(v int64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldEQ(FieldSenderID, v))
}

// SenderIDNEQ applies the NEQ predicate on the "sender_id" field.
func SenderIDNEQ(v int64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldNEQ(FieldSenderID, v))
}

// SenderIDIn applies the In predicate on the "sender_id" field.
func SenderIDIn(vs ...int64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldIn(FieldSenderID, vs...))
}

// SenderIDNotIn applies the NotIn predicate on the "sender_id" field.
func SenderIDNotIn(vs ...int64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldNotIn(FieldSenderID, vs...))
}

// ReceiverIDEQ applies the EQ predicate on the "receiver_id" field.
func ReceiverIDEQ(v int64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldEQ(FieldReceiverID, v))
}

// ReceiverIDNEQ applies the NEQ predicate on the "receiver_id" field.
func ReceiverIDNEQ(v int64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldNEQ(FieldReceiverID, v))
}

// ReceiverIDIn applies the In predicate on the "receiver_id" field.
func ReceiverIDIn(vs ...int64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldIn(FieldReceiverID, vs...))
}

// ReceiverIDNotIn applies the NotIn predicate on the "receiver_id" field.
func ReceiverIDNotIn(vs ...int64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldNotIn(FieldReceiverID, vs...))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldLTE(FieldAmount, v))
}

// FeeEQ applies the EQ predicate on the "fee" field.
func FeeEQ(v float64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldEQ(FieldFee, v))
}

// FeeNEQ applies the NEQ predicate on the "fee" field.
func FeeNEQ(v float64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldNEQ(FieldFee, v))
}

// FeeIn applies the In predicate on the "fee" field.
func FeeIn(vs ...float64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldIn(FieldFee, vs...))
}

// FeeNotIn applies the NotIn predicate on the "fee" field.
func FeeNotIn(vs ...float64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldNotIn(FieldFee, vs...))
}

// FeeGT applies the GT predicate on the "fee" field.
func FeeGT(v float64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldGT(FieldFee, v))
}

// FeeGTE applies the GTE predicate on the "fee" field.
func FeeGTE(v float64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldGTE(FieldFee, v))
}

// FeeLT applies the LT predicate on the "fee" field.
func FeeLT(v float64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldLT(FieldFee, v))
}

// FeeLTE applies the LTE predicate on the "fee" field.
func FeeLTE(v float64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldLTE(FieldFee, v))
}

// FeeRateEQ applies the EQ predicate on the "fee_rate" field.
func FeeRateEQ(v float64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldEQ(FieldFeeRate, v))
}

// FeeRateNEQ applies the NEQ predicate on the "fee_rate" field.
func FeeRateNEQ(v float64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldNEQ(FieldFeeRate, v))
}

// FeeRateIn applies the In predicate on the "fee_rate" field.
func FeeRateIn(vs ...float64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldIn(FieldFeeRate, vs...))
}

// FeeRateNotIn applies the NotIn predicate on the "fee_rate" field.
func FeeRateNotIn(vs ...float64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldNotIn(FieldFeeRate, vs...))
}

// FeeRateGT applies the GT predicate on the "fee_rate" field.
func FeeRateGT(v float64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldGT(FieldFeeRate, v))
}

// FeeRateGTE applies the GTE predicate on the "fee_rate" field.
func FeeRateGTE(v float64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldGTE(FieldFeeRate, v))
}

// FeeRateLT applies the LT predicate on the "fee_rate" field.
func FeeRateLT(v float64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldLT(FieldFeeRate, v))
}

// FeeRateLTE applies the LTE predicate on the "fee_rate" field.
func FeeRateLTE(v float64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldLTE(FieldFeeRate, v))
}

// GrossAmountEQ applies the EQ predicate on the "gross_amount" field.
func GrossAmountEQ(v float64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldEQ(FieldGrossAmount, v))
}

// GrossAmountNEQ applies the NEQ predicate on the "gross_amount" field.
func GrossAmountNEQ(v float64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldNEQ(FieldGrossAmount, v))
}

// GrossAmountIn applies the In predicate on the "gross_amount" field.
func GrossAmountIn(vs ...float64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldIn(FieldGrossAmount, vs...))
}

// GrossAmountNotIn applies the NotIn predicate on the "gross_amount" field.
func GrossAmountNotIn(vs ...float64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldNotIn(FieldGrossAmount, vs...))
}

// GrossAmountGT applies the GT predicate on the "gross_amount" field.
func GrossAmountGT(v float64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldGT(FieldGrossAmount, v))
}

// GrossAmountGTE applies the GTE predicate on the "gross_amount" field.
func GrossAmountGTE(v float64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldGTE(FieldGrossAmount, v))
}

// GrossAmountLT applies the LT predicate on the "gross_amount" field.
func GrossAmountLT(v float64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldLT(FieldGrossAmount, v))
}

// GrossAmountLTE applies the LTE predicate on the "gross_amount" field.
func GrossAmountLTE(v float64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldLTE(FieldGrossAmount, v))
}

// TransferTypeEQ applies the EQ predicate on the "transfer_type" field.
func TransferTypeEQ(v string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldEQ(FieldTransferType, v))
}

// TransferTypeNEQ applies the NEQ predicate on the "transfer_type" field.
func TransferTypeNEQ(v string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldNEQ(FieldTransferType, v))
}

// TransferTypeIn applies the In predicate on the "transfer_type" field.
func TransferTypeIn(vs ...string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldIn(FieldTransferType, vs...))
}

// TransferTypeNotIn applies the NotIn predicate on the "transfer_type" field.
func TransferTypeNotIn(vs ...string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldNotIn(FieldTransferType, vs...))
}

// TransferTypeGT applies the GT predicate on the "transfer_type" field.
func TransferTypeGT(v string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldGT(FieldTransferType, v))
}

// TransferTypeGTE applies the GTE predicate on the "transfer_type" field.
func TransferTypeGTE(v string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldGTE(FieldTransferType, v))
}

// TransferTypeLT applies the LT predicate on the "transfer_type" field.
func TransferTypeLT(v string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldLT(FieldTransferType, v))
}

// TransferTypeLTE applies the LTE predicate on the "transfer_type" field.
func TransferTypeLTE(v string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldLTE(FieldTransferType, v))
}

// TransferTypeContains applies the Contains predicate on the "transfer_type" field.
func TransferTypeContains(v string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldContains(FieldTransferType, v))
}

// TransferTypeHasPrefix applies the HasPrefix predicate on the "transfer_type" field.
func TransferTypeHasPrefix(v string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldHasPrefix(FieldTransferType, v))
}

// TransferTypeHasSuffix applies the HasSuffix predicate on the "transfer_type" field.
func TransferTypeHasSuffix(v string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldHasSuffix(FieldTransferType, v))
}

// TransferTypeEqualFold applies the EqualFold predicate on the "transfer_type" field.
func TransferTypeEqualFold(v string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldEqualFold(FieldTransferType, v))
}

// TransferTypeContainsFold applies the ContainsFold predicate on the "transfer_type" field.
func TransferTypeContainsFold(v string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldContainsFold(FieldTransferType, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldContainsFold(FieldStatus, v))
}

// MemoEQ applies the EQ predicate on the "memo" field.
func MemoEQ(v string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldEQ(FieldMemo, v))
}

// MemoNEQ applies the NEQ predicate on the "memo" field.
func MemoNEQ(v string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldNEQ(FieldMemo, v))
}

// MemoIn applies the In predicate on the "memo" field.
func MemoIn(vs ...string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldIn(FieldMemo, vs...))
}

// MemoNotIn applies the NotIn predicate on the "memo" field.
func MemoNotIn(vs ...string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldNotIn(FieldMemo, vs...))
}

// MemoGT applies the GT predicate on the "memo" field.
func MemoGT(v string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldGT(FieldMemo, v))
}

// MemoGTE applies the GTE predicate on the "memo" field.
func MemoGTE(v string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldGTE(FieldMemo, v))
}

// MemoLT applies the LT predicate on the "memo" field.
func MemoLT(v string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldLT(FieldMemo, v))
}

// MemoLTE applies the LTE predicate on the "memo" field.
func MemoLTE(v string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldLTE(FieldMemo, v))
}

// MemoContains applies the Contains predicate on the "memo" field.
func MemoContains(v string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldContains(FieldMemo, v))
}

// MemoHasPrefix applies the HasPrefix predicate on the "memo" field.
func MemoHasPrefix(v string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldHasPrefix(FieldMemo, v))
}

// MemoHasSuffix applies the HasSuffix predicate on the "memo" field.
func MemoHasSuffix(v string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldHasSuffix(FieldMemo, v))
}

// MemoIsNil applies the IsNil predicate on the "memo" field.
func MemoIsNil() predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldIsNull(FieldMemo))
}

// MemoNotNil applies the NotNil predicate on the "memo" field.
func MemoNotNil() predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldNotNull(FieldMemo))
}

// MemoEqualFold applies the EqualFold predicate on the "memo" field.
func MemoEqualFold(v string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldEqualFold(FieldMemo, v))
}

// MemoContainsFold applies the ContainsFold predicate on the "memo" field.
func MemoContainsFold(v string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldContainsFold(FieldMemo, v))
}

// RedpacketIDEQ applies the EQ predicate on the "redpacket_id" field.
func RedpacketIDEQ(v int64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldEQ(FieldRedpacketID, v))
}

// RedpacketIDNEQ applies the NEQ predicate on the "redpacket_id" field.
func RedpacketIDNEQ(v int64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldNEQ(FieldRedpacketID, v))
}

// RedpacketIDIn applies the In predicate on the "redpacket_id" field.
func RedpacketIDIn(vs ...int64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldIn(FieldRedpacketID, vs...))
}

// RedpacketIDNotIn applies the NotIn predicate on the "redpacket_id" field.
func RedpacketIDNotIn(vs ...int64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldNotIn(FieldRedpacketID, vs...))
}

// RedpacketIDGT applies the GT predicate on the "redpacket_id" field.
func RedpacketIDGT(v int64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldGT(FieldRedpacketID, v))
}

// RedpacketIDGTE applies the GTE predicate on the "redpacket_id" field.
func RedpacketIDGTE(v int64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldGTE(FieldRedpacketID, v))
}

// RedpacketIDLT applies the LT predicate on the "redpacket_id" field.
func RedpacketIDLT(v int64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldLT(FieldRedpacketID, v))
}

// RedpacketIDLTE applies the LTE predicate on the "redpacket_id" field.
func RedpacketIDLTE(v int64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldLTE(FieldRedpacketID, v))
}

// RedpacketIDIsNil applies the IsNil predicate on the "redpacket_id" field.
func RedpacketIDIsNil() predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldIsNull(FieldRedpacketID))
}

// RedpacketIDNotNil applies the NotNil predicate on the "redpacket_id" field.
func RedpacketIDNotNil() predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldNotNull(FieldRedpacketID))
}

// FrozenAtEQ applies the EQ predicate on the "frozen_at" field.
func FrozenAtEQ(v time.Time) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldEQ(FieldFrozenAt, v))
}

// FrozenAtNEQ applies the NEQ predicate on the "frozen_at" field.
func FrozenAtNEQ(v time.Time) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldNEQ(FieldFrozenAt, v))
}

// FrozenAtIn applies the In predicate on the "frozen_at" field.
func FrozenAtIn(vs ...time.Time) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldIn(FieldFrozenAt, vs...))
}

// FrozenAtNotIn applies the NotIn predicate on the "frozen_at" field.
func FrozenAtNotIn(vs ...time.Time) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldNotIn(FieldFrozenAt, vs...))
}

// FrozenAtGT applies the GT predicate on the "frozen_at" field.
func FrozenAtGT(v time.Time) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldGT(FieldFrozenAt, v))
}

// FrozenAtGTE applies the GTE predicate on the "frozen_at" field.
func FrozenAtGTE(v time.Time) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldGTE(FieldFrozenAt, v))
}

// FrozenAtLT applies the LT predicate on the "frozen_at" field.
func FrozenAtLT(v time.Time) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldLT(FieldFrozenAt, v))
}

// FrozenAtLTE applies the LTE predicate on the "frozen_at" field.
func FrozenAtLTE(v time.Time) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldLTE(FieldFrozenAt, v))
}

// FrozenAtIsNil applies the IsNil predicate on the "frozen_at" field.
func FrozenAtIsNil() predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldIsNull(FieldFrozenAt))
}

// FrozenAtNotNil applies the NotNil predicate on the "frozen_at" field.
func FrozenAtNotNil() predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldNotNull(FieldFrozenAt))
}

// FrozenByEQ applies the EQ predicate on the "frozen_by" field.
func FrozenByEQ(v int64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldEQ(FieldFrozenBy, v))
}

// FrozenByNEQ applies the NEQ predicate on the "frozen_by" field.
func FrozenByNEQ(v int64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldNEQ(FieldFrozenBy, v))
}

// FrozenByIn applies the In predicate on the "frozen_by" field.
func FrozenByIn(vs ...int64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldIn(FieldFrozenBy, vs...))
}

// FrozenByNotIn applies the NotIn predicate on the "frozen_by" field.
func FrozenByNotIn(vs ...int64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldNotIn(FieldFrozenBy, vs...))
}

// FrozenByGT applies the GT predicate on the "frozen_by" field.
func FrozenByGT(v int64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldGT(FieldFrozenBy, v))
}

// FrozenByGTE applies the GTE predicate on the "frozen_by" field.
func FrozenByGTE(v int64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldGTE(FieldFrozenBy, v))
}

// FrozenByLT applies the LT predicate on the "frozen_by" field.
func FrozenByLT(v int64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldLT(FieldFrozenBy, v))
}

// FrozenByLTE applies the LTE predicate on the "frozen_by" field.
func FrozenByLTE(v int64) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldLTE(FieldFrozenBy, v))
}

// FrozenByIsNil applies the IsNil predicate on the "frozen_by" field.
func FrozenByIsNil() predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldIsNull(FieldFrozenBy))
}

// FrozenByNotNil applies the NotNil predicate on the "frozen_by" field.
func FrozenByNotNil() predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldNotNull(FieldFrozenBy))
}

// RevokeReasonEQ applies the EQ predicate on the "revoke_reason" field.
func RevokeReasonEQ(v string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldEQ(FieldRevokeReason, v))
}

// RevokeReasonNEQ applies the NEQ predicate on the "revoke_reason" field.
func RevokeReasonNEQ(v string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldNEQ(FieldRevokeReason, v))
}

// RevokeReasonIn applies the In predicate on the "revoke_reason" field.
func RevokeReasonIn(vs ...string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldIn(FieldRevokeReason, vs...))
}

// RevokeReasonNotIn applies the NotIn predicate on the "revoke_reason" field.
func RevokeReasonNotIn(vs ...string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldNotIn(FieldRevokeReason, vs...))
}

// RevokeReasonGT applies the GT predicate on the "revoke_reason" field.
func RevokeReasonGT(v string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldGT(FieldRevokeReason, v))
}

// RevokeReasonGTE applies the GTE predicate on the "revoke_reason" field.
func RevokeReasonGTE(v string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldGTE(FieldRevokeReason, v))
}

// RevokeReasonLT applies the LT predicate on the "revoke_reason" field.
func RevokeReasonLT(v string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldLT(FieldRevokeReason, v))
}

// RevokeReasonLTE applies the LTE predicate on the "revoke_reason" field.
func RevokeReasonLTE(v string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldLTE(FieldRevokeReason, v))
}

// RevokeReasonContains applies the Contains predicate on the "revoke_reason" field.
func RevokeReasonContains(v string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldContains(FieldRevokeReason, v))
}

// RevokeReasonHasPrefix applies the HasPrefix predicate on the "revoke_reason" field.
func RevokeReasonHasPrefix(v string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldHasPrefix(FieldRevokeReason, v))
}

// RevokeReasonHasSuffix applies the HasSuffix predicate on the "revoke_reason" field.
func RevokeReasonHasSuffix(v string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldHasSuffix(FieldRevokeReason, v))
}

// RevokeReasonIsNil applies the IsNil predicate on the "revoke_reason" field.
func RevokeReasonIsNil() predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldIsNull(FieldRevokeReason))
}

// RevokeReasonNotNil applies the NotNil predicate on the "revoke_reason" field.
func RevokeReasonNotNil() predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldNotNull(FieldRevokeReason))
}

// RevokeReasonEqualFold applies the EqualFold predicate on the "revoke_reason" field.
func RevokeReasonEqualFold(v string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldEqualFold(FieldRevokeReason, v))
}

// RevokeReasonContainsFold applies the ContainsFold predicate on the "revoke_reason" field.
func RevokeReasonContainsFold(v string) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldContainsFold(FieldRevokeReason, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.FieldLTE(FieldCreatedAt, v))
}

// HasSender applies the HasEdge predicate on the "sender" edge.
func HasSender() predicate.BalanceTransfer {
	return predicate.BalanceTransfer(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SenderTable, SenderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSenderWith applies the HasEdge predicate on the "sender" edge with a given conditions (other predicates).
func HasSenderWith(preds ...predicate.User) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(func(s *sql.Selector) {
		step := newSenderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasReceiver applies the HasEdge predicate on the "receiver" edge.
func HasReceiver() predicate.BalanceTransfer {
	return predicate.BalanceTransfer(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ReceiverTable, ReceiverColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasReceiverWith applies the HasEdge predicate on the "receiver" edge with a given conditions (other predicates).
func HasReceiverWith(preds ...predicate.User) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(func(s *sql.Selector) {
		step := newReceiverStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BalanceTransfer) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BalanceTransfer) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BalanceTransfer) predicate.BalanceTransfer {
	return predicate.BalanceTransfer(sql.NotPredicates(p))
}
