// Code generated by ent, DO NOT EDIT.

package proxysubscriptionsource

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldEQ(FieldDeletedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldEQ(FieldName, v))
}

// URL applies equality check predicate on the "url" field. It's identical to URLEQ.
func URL(v string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldEQ(FieldURL, v))
}

// SourceFormat applies equality check predicate on the "source_format" field. It's identical to SourceFormatEQ.
func SourceFormat(v string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldEQ(FieldSourceFormat, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldEQ(FieldEnabled, v))
}

// RefreshIntervalHours applies equality check predicate on the "refresh_interval_hours" field. It's identical to RefreshIntervalHoursEQ.
func RefreshIntervalHours(v int) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldEQ(FieldRefreshIntervalHours, v))
}

// TargetEntryCount applies equality check predicate on the "target_entry_count" field. It's identical to TargetEntryCountEQ.
func TargetEntryCount(v int) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldEQ(FieldTargetEntryCount, v))
}

// AutoAddToPool applies equality check predicate on the "auto_add_to_pool" field. It's identical to AutoAddToPoolEQ.
func AutoAddToPool(v bool) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldEQ(FieldAutoAddToPool, v))
}

// LastRefreshedAt applies equality check predicate on the "last_refreshed_at" field. It's identical to LastRefreshedAtEQ.
func LastRefreshedAt(v time.Time) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldEQ(FieldLastRefreshedAt, v))
}

// LastSuccessAt applies equality check predicate on the "last_success_at" field. It's identical to LastSuccessAtEQ.
func LastSuccessAt(v time.Time) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldEQ(FieldLastSuccessAt, v))
}

// LastError applies equality check predicate on the "last_error" field. It's identical to LastErrorEQ.
func LastError(v string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldEQ(FieldLastError, v))
}

// LastNodeCount applies equality check predicate on the "last_node_count" field. It's identical to LastNodeCountEQ.
func LastNodeCount(v int) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldEQ(FieldLastNodeCount, v))
}

// LastMaterializedProxyCount applies equality check predicate on the "last_materialized_proxy_count" field. It's identical to LastMaterializedProxyCountEQ.
func LastMaterializedProxyCount(v int) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldEQ(FieldLastMaterializedProxyCount, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldNotNull(FieldDeletedAt))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldContainsFold(FieldName, v))
}

// URLEQ applies the EQ predicate on the "url" field.
func URLEQ(v string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldEQ(FieldURL, v))
}

// URLNEQ applies the NEQ predicate on the "url" field.
func URLNEQ(v string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldNEQ(FieldURL, v))
}

// URLIn applies the In predicate on the "url" field.
func URLIn(vs ...string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldIn(FieldURL, vs...))
}

// URLNotIn applies the NotIn predicate on the "url" field.
func URLNotIn(vs ...string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldNotIn(FieldURL, vs...))
}

// URLGT applies the GT predicate on the "url" field.
func URLGT(v string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldGT(FieldURL, v))
}

// URLGTE applies the GTE predicate on the "url" field.
func URLGTE(v string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldGTE(FieldURL, v))
}

// URLLT applies the LT predicate on the "url" field.
func URLLT(v string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldLT(FieldURL, v))
}

// URLLTE applies the LTE predicate on the "url" field.
func URLLTE(v string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldLTE(FieldURL, v))
}

// URLContains applies the Contains predicate on the "url" field.
func URLContains(v string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldContains(FieldURL, v))
}

// URLHasPrefix applies the HasPrefix predicate on the "url" field.
func URLHasPrefix(v string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldHasPrefix(FieldURL, v))
}

// URLHasSuffix applies the HasSuffix predicate on the "url" field.
func URLHasSuffix(v string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldHasSuffix(FieldURL, v))
}

// URLEqualFold applies the EqualFold predicate on the "url" field.
func URLEqualFold(v string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldEqualFold(FieldURL, v))
}

// URLContainsFold applies the ContainsFold predicate on the "url" field.
func URLContainsFold(v string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldContainsFold(FieldURL, v))
}

// SourceFormatEQ applies the EQ predicate on the "source_format" field.
func SourceFormatEQ(v string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldEQ(FieldSourceFormat, v))
}

// SourceFormatNEQ applies the NEQ predicate on the "source_format" field.
func SourceFormatNEQ(v string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldNEQ(FieldSourceFormat, v))
}

// SourceFormatIn applies the In predicate on the "source_format" field.
func SourceFormatIn(vs ...string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldIn(FieldSourceFormat, vs...))
}

// SourceFormatNotIn applies the NotIn predicate on the "source_format" field.
func SourceFormatNotIn(vs ...string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldNotIn(FieldSourceFormat, vs...))
}

// SourceFormatGT applies the GT predicate on the "source_format" field.
func SourceFormatGT(v string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldGT(FieldSourceFormat, v))
}

// SourceFormatGTE applies the GTE predicate on the "source_format" field.
func SourceFormatGTE(v string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldGTE(FieldSourceFormat, v))
}

// SourceFormatLT applies the LT predicate on the "source_format" field.
func SourceFormatLT(v string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldLT(FieldSourceFormat, v))
}

// SourceFormatLTE applies the LTE predicate on the "source_format" field.
func SourceFormatLTE(v string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldLTE(FieldSourceFormat, v))
}

// SourceFormatContains applies the Contains predicate on the "source_format" field.
func SourceFormatContains(v string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldContains(FieldSourceFormat, v))
}

// SourceFormatHasPrefix applies the HasPrefix predicate on the "source_format" field.
func SourceFormatHasPrefix(v string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldHasPrefix(FieldSourceFormat, v))
}

// SourceFormatHasSuffix applies the HasSuffix predicate on the "source_format" field.
func SourceFormatHasSuffix(v string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldHasSuffix(FieldSourceFormat, v))
}

// SourceFormatEqualFold applies the EqualFold predicate on the "source_format" field.
func SourceFormatEqualFold(v string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldEqualFold(FieldSourceFormat, v))
}

// SourceFormatContainsFold applies the ContainsFold predicate on the "source_format" field.
func SourceFormatContainsFold(v string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldContainsFold(FieldSourceFormat, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldNEQ(FieldEnabled, v))
}

// RefreshIntervalHoursEQ applies the EQ predicate on the "refresh_interval_hours" field.
func RefreshIntervalHoursEQ(v int) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldEQ(FieldRefreshIntervalHours, v))
}

// RefreshIntervalHoursNEQ applies the NEQ predicate on the "refresh_interval_hours" field.
func RefreshIntervalHoursNEQ(v int) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldNEQ(FieldRefreshIntervalHours, v))
}

// RefreshIntervalHoursIn applies the In predicate on the "refresh_interval_hours" field.
func RefreshIntervalHoursIn(vs ...int) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldIn(FieldRefreshIntervalHours, vs...))
}

// RefreshIntervalHoursNotIn applies the NotIn predicate on the "refresh_interval_hours" field.
func RefreshIntervalHoursNotIn(vs ...int) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldNotIn(FieldRefreshIntervalHours, vs...))
}

// RefreshIntervalHoursGT applies the GT predicate on the "refresh_interval_hours" field.
func RefreshIntervalHoursGT(v int) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldGT(FieldRefreshIntervalHours, v))
}

// RefreshIntervalHoursGTE applies the GTE predicate on the "refresh_interval_hours" field.
func RefreshIntervalHoursGTE(v int) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldGTE(FieldRefreshIntervalHours, v))
}

// RefreshIntervalHoursLT applies the LT predicate on the "refresh_interval_hours" field.
func RefreshIntervalHoursLT(v int) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldLT(FieldRefreshIntervalHours, v))
}

// RefreshIntervalHoursLTE applies the LTE predicate on the "refresh_interval_hours" field.
func RefreshIntervalHoursLTE(v int) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldLTE(FieldRefreshIntervalHours, v))
}

// TargetEntryCountEQ applies the EQ predicate on the "target_entry_count" field.
func TargetEntryCountEQ(v int) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldEQ(FieldTargetEntryCount, v))
}

// TargetEntryCountNEQ applies the NEQ predicate on the "target_entry_count" field.
func TargetEntryCountNEQ(v int) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldNEQ(FieldTargetEntryCount, v))
}

// TargetEntryCountIn applies the In predicate on the "target_entry_count" field.
func TargetEntryCountIn(vs ...int) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldIn(FieldTargetEntryCount, vs...))
}

// TargetEntryCountNotIn applies the NotIn predicate on the "target_entry_count" field.
func TargetEntryCountNotIn(vs ...int) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldNotIn(FieldTargetEntryCount, vs...))
}

// TargetEntryCountGT applies the GT predicate on the "target_entry_count" field.
func TargetEntryCountGT(v int) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldGT(FieldTargetEntryCount, v))
}

// TargetEntryCountGTE applies the GTE predicate on the "target_entry_count" field.
func TargetEntryCountGTE(v int) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldGTE(FieldTargetEntryCount, v))
}

// TargetEntryCountLT applies the LT predicate on the "target_entry_count" field.
func TargetEntryCountLT(v int) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldLT(FieldTargetEntryCount, v))
}

// TargetEntryCountLTE applies the LTE predicate on the "target_entry_count" field.
func TargetEntryCountLTE(v int) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldLTE(FieldTargetEntryCount, v))
}

// AutoAddToPoolEQ applies the EQ predicate on the "auto_add_to_pool" field.
func AutoAddToPoolEQ(v bool) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldEQ(FieldAutoAddToPool, v))
}

// AutoAddToPoolNEQ applies the NEQ predicate on the "auto_add_to_pool" field.
func AutoAddToPoolNEQ(v bool) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldNEQ(FieldAutoAddToPool, v))
}

// LastRefreshedAtEQ applies the EQ predicate on the "last_refreshed_at" field.
func LastRefreshedAtEQ(v time.Time) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldEQ(FieldLastRefreshedAt, v))
}

// LastRefreshedAtNEQ applies the NEQ predicate on the "last_refreshed_at" field.
func LastRefreshedAtNEQ(v time.Time) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldNEQ(FieldLastRefreshedAt, v))
}

// LastRefreshedAtIn applies the In predicate on the "last_refreshed_at" field.
func LastRefreshedAtIn(vs ...time.Time) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldIn(FieldLastRefreshedAt, vs...))
}

// LastRefreshedAtNotIn applies the NotIn predicate on the "last_refreshed_at" field.
func LastRefreshedAtNotIn(vs ...time.Time) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldNotIn(FieldLastRefreshedAt, vs...))
}

// LastRefreshedAtGT applies the GT predicate on the "last_refreshed_at" field.
func LastRefreshedAtGT(v time.Time) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldGT(FieldLastRefreshedAt, v))
}

// LastRefreshedAtGTE applies the GTE predicate on the "last_refreshed_at" field.
func LastRefreshedAtGTE(v time.Time) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldGTE(FieldLastRefreshedAt, v))
}

// LastRefreshedAtLT applies the LT predicate on the "last_refreshed_at" field.
func LastRefreshedAtLT(v time.Time) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldLT(FieldLastRefreshedAt, v))
}

// LastRefreshedAtLTE applies the LTE predicate on the "last_refreshed_at" field.
func LastRefreshedAtLTE(v time.Time) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldLTE(FieldLastRefreshedAt, v))
}

// LastRefreshedAtIsNil applies the IsNil predicate on the "last_refreshed_at" field.
func LastRefreshedAtIsNil() predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldIsNull(FieldLastRefreshedAt))
}

// LastRefreshedAtNotNil applies the NotNil predicate on the "last_refreshed_at" field.
func LastRefreshedAtNotNil() predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldNotNull(FieldLastRefreshedAt))
}

// LastSuccessAtEQ applies the EQ predicate on the "last_success_at" field.
func LastSuccessAtEQ(v time.Time) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldEQ(FieldLastSuccessAt, v))
}

// LastSuccessAtNEQ applies the NEQ predicate on the "last_success_at" field.
func LastSuccessAtNEQ(v time.Time) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldNEQ(FieldLastSuccessAt, v))
}

// LastSuccessAtIn applies the In predicate on the "last_success_at" field.
func LastSuccessAtIn(vs ...time.Time) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldIn(FieldLastSuccessAt, vs...))
}

// LastSuccessAtNotIn applies the NotIn predicate on the "last_success_at" field.
func LastSuccessAtNotIn(vs ...time.Time) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldNotIn(FieldLastSuccessAt, vs...))
}

// LastSuccessAtGT applies the GT predicate on the "last_success_at" field.
func LastSuccessAtGT(v time.Time) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldGT(FieldLastSuccessAt, v))
}

// LastSuccessAtGTE applies the GTE predicate on the "last_success_at" field.
func LastSuccessAtGTE(v time.Time) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldGTE(FieldLastSuccessAt, v))
}

// LastSuccessAtLT applies the LT predicate on the "last_success_at" field.
func LastSuccessAtLT(v time.Time) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldLT(FieldLastSuccessAt, v))
}

// LastSuccessAtLTE applies the LTE predicate on the "last_success_at" field.
func LastSuccessAtLTE(v time.Time) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldLTE(FieldLastSuccessAt, v))
}

// LastSuccessAtIsNil applies the IsNil predicate on the "last_success_at" field.
func LastSuccessAtIsNil() predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldIsNull(FieldLastSuccessAt))
}

// LastSuccessAtNotNil applies the NotNil predicate on the "last_success_at" field.
func LastSuccessAtNotNil() predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldNotNull(FieldLastSuccessAt))
}

// LastErrorEQ applies the EQ predicate on the "last_error" field.
func LastErrorEQ(v string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldEQ(FieldLastError, v))
}

// LastErrorNEQ applies the NEQ predicate on the "last_error" field.
func LastErrorNEQ(v string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldNEQ(FieldLastError, v))
}

// LastErrorIn applies the In predicate on the "last_error" field.
func LastErrorIn(vs ...string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldIn(FieldLastError, vs...))
}

// LastErrorNotIn applies the NotIn predicate on the "last_error" field.
func LastErrorNotIn(vs ...string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldNotIn(FieldLastError, vs...))
}

// LastErrorGT applies the GT predicate on the "last_error" field.
func LastErrorGT(v string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldGT(FieldLastError, v))
}

// LastErrorGTE applies the GTE predicate on the "last_error" field.
func LastErrorGTE(v string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldGTE(FieldLastError, v))
}

// LastErrorLT applies the LT predicate on the "last_error" field.
func LastErrorLT(v string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldLT(FieldLastError, v))
}

// LastErrorLTE applies the LTE predicate on the "last_error" field.
func LastErrorLTE(v string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldLTE(FieldLastError, v))
}

// LastErrorContains applies the Contains predicate on the "last_error" field.
func LastErrorContains(v string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldContains(FieldLastError, v))
}

// LastErrorHasPrefix applies the HasPrefix predicate on the "last_error" field.
func LastErrorHasPrefix(v string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldHasPrefix(FieldLastError, v))
}

// LastErrorHasSuffix applies the HasSuffix predicate on the "last_error" field.
func LastErrorHasSuffix(v string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldHasSuffix(FieldLastError, v))
}

// LastErrorIsNil applies the IsNil predicate on the "last_error" field.
func LastErrorIsNil() predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldIsNull(FieldLastError))
}

// LastErrorNotNil applies the NotNil predicate on the "last_error" field.
func LastErrorNotNil() predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldNotNull(FieldLastError))
}

// LastErrorEqualFold applies the EqualFold predicate on the "last_error" field.
func LastErrorEqualFold(v string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldEqualFold(FieldLastError, v))
}

// LastErrorContainsFold applies the ContainsFold predicate on the "last_error" field.
func LastErrorContainsFold(v string) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldContainsFold(FieldLastError, v))
}

// LastNodeCountEQ applies the EQ predicate on the "last_node_count" field.
func LastNodeCountEQ(v int) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldEQ(FieldLastNodeCount, v))
}

// LastNodeCountNEQ applies the NEQ predicate on the "last_node_count" field.
func LastNodeCountNEQ(v int) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldNEQ(FieldLastNodeCount, v))
}

// LastNodeCountIn applies the In predicate on the "last_node_count" field.
func LastNodeCountIn(vs ...int) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldIn(FieldLastNodeCount, vs...))
}

// LastNodeCountNotIn applies the NotIn predicate on the "last_node_count" field.
func LastNodeCountNotIn(vs ...int) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldNotIn(FieldLastNodeCount, vs...))
}

// LastNodeCountGT applies the GT predicate on the "last_node_count" field.
func LastNodeCountGT(v int) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldGT(FieldLastNodeCount, v))
}

// LastNodeCountGTE applies the GTE predicate on the "last_node_count" field.
func LastNodeCountGTE(v int) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldGTE(FieldLastNodeCount, v))
}

// LastNodeCountLT applies the LT predicate on the "last_node_count" field.
func LastNodeCountLT(v int) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldLT(FieldLastNodeCount, v))
}

// LastNodeCountLTE applies the LTE predicate on the "last_node_count" field.
func LastNodeCountLTE(v int) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldLTE(FieldLastNodeCount, v))
}

// LastMaterializedProxyCountEQ applies the EQ predicate on the "last_materialized_proxy_count" field.
func LastMaterializedProxyCountEQ(v int) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldEQ(FieldLastMaterializedProxyCount, v))
}

// LastMaterializedProxyCountNEQ applies the NEQ predicate on the "last_materialized_proxy_count" field.
func LastMaterializedProxyCountNEQ(v int) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldNEQ(FieldLastMaterializedProxyCount, v))
}

// LastMaterializedProxyCountIn applies the In predicate on the "last_materialized_proxy_count" field.
func LastMaterializedProxyCountIn(vs ...int) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldIn(FieldLastMaterializedProxyCount, vs...))
}

// LastMaterializedProxyCountNotIn applies the NotIn predicate on the "last_materialized_proxy_count" field.
func LastMaterializedProxyCountNotIn(vs ...int) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldNotIn(FieldLastMaterializedProxyCount, vs...))
}

// LastMaterializedProxyCountGT applies the GT predicate on the "last_materialized_proxy_count" field.
func LastMaterializedProxyCountGT(v int) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldGT(FieldLastMaterializedProxyCount, v))
}

// LastMaterializedProxyCountGTE applies the GTE predicate on the "last_materialized_proxy_count" field.
func LastMaterializedProxyCountGTE(v int) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldGTE(FieldLastMaterializedProxyCount, v))
}

// LastMaterializedProxyCountLT applies the LT predicate on the "last_materialized_proxy_count" field.
func LastMaterializedProxyCountLT(v int) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldLT(FieldLastMaterializedProxyCount, v))
}

// LastMaterializedProxyCountLTE applies the LTE predicate on the "last_materialized_proxy_count" field.
func LastMaterializedProxyCountLTE(v int) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.FieldLTE(FieldLastMaterializedProxyCount, v))
}

// HasNodes applies the HasEdge predicate on the "nodes" edge.
func HasNodes() predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, NodesTable, NodesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasNodesWith applies the HasEdge predicate on the "nodes" edge with a given conditions (other predicates).
func HasNodesWith(preds ...predicate.ProxySubscriptionNode) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(func(s *sql.Selector) {
		step := newNodesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProxySubscriptionSource) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProxySubscriptionSource) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProxySubscriptionSource) predicate.ProxySubscriptionSource {
	return predicate.ProxySubscriptionSource(sql.NotPredicates(p))
}
