export const ADMIN_EMAIL = 'admin@example.com'
export const ADMIN_PASSWORD = 'Passw0rd!'

export function maskAdminApiKey(key) {
  if (!key) return ''
  return `${key.substring(0, 10)}...${key.slice(-4)}`
}

export function buildAdminApiKeyValue(rotation = 1) {
  return `sk-admin-e2e-${String(rotation).padStart(4, '0')}-secret`
}

export function buildAdminApiKeyState(overrides = {}) {
  const currentKey = overrides.currentKey ?? ''
  const rotation = overrides.rotation ?? (currentKey ? 1 : 0)
  const exists = overrides.exists ?? currentKey.length > 0

  return {
    exists,
    masked_key: overrides.masked_key ?? (exists && currentKey ? maskAdminApiKey(currentKey) : ''),
    currentKey,
    rotation,
  }
}

export function buildAuthUser(overrides = {}) {
  return {
    id: 1,
    email: ADMIN_EMAIL,
    username: 'admin',
    role: 'admin',
    status: 'active',
    balance: 88.5,
    avatar_url: '',
    created_at: '2026-05-22T00:00:00Z',
    updated_at: '2026-05-22T00:00:00Z',
    ...overrides,
  }
}

export function buildAuthResponse(overrides = {}) {
  const user = buildAuthUser(overrides.user)
  return {
    access_token: 'playwright-access-token',
    refresh_token: 'playwright-refresh-token',
    expires_in: 7200,
    token_type: 'Bearer',
    user,
    ...overrides,
    user,
  }
}

export function buildPublicSettings(overrides = {}) {
  return {
    registration_enabled: false,
    email_verify_enabled: false,
    force_email_on_third_party_signup: false,
    registration_email_suffix_whitelist: [],
    promo_code_enabled: true,
    password_reset_enabled: false,
    invitation_code_enabled: false,
    turnstile_enabled: false,
    turnstile_site_key: '',
    site_name: 'Sub2API',
    site_logo: '',
    site_subtitle: 'Subscription to API Conversion Platform',
    api_base_url: '',
    contact_info: '',
    doc_url: '',
    home_content: '',
    home_nav_links_enabled: true,
    home_nav_leaderboard_enabled: true,
    home_nav_key_usage_enabled: true,
    home_nav_monitoring_enabled: true,
    home_nav_pricing_enabled: true,
    leaderboard_balance_enabled: true,
    leaderboard_consumption_enabled: true,
    leaderboard_transfer_enabled: true,
    leaderboard_checkin_enabled: true,
    hide_ccs_import_button: false,
    payment_enabled: false,
    table_default_page_size: 20,
    table_page_size_options: [10, 20, 50, 100],
    custom_menu_items: [],
    custom_endpoints: [],
    linuxdo_oauth_enabled: false,
    wechat_oauth_enabled: false,
    wechat_oauth_open_enabled: false,
    wechat_oauth_mp_enabled: false,
    wechat_oauth_mobile_enabled: false,
    oidc_oauth_enabled: false,
    oidc_oauth_provider_name: 'OIDC',
    github_oauth_enabled: false,
    google_oauth_enabled: false,
    backend_mode_enabled: false,
    version: 'test-build',
    balance_low_notify_enabled: false,
    account_quota_notify_enabled: false,
    balance_low_notify_threshold: 0,
    channel_monitor_enabled: true,
    channel_monitor_default_interval_seconds: 60,
    available_channels_enabled: false,
    transfer_enabled: false,
    redpacket_enabled: false,
    risk_control_enabled: false,
    affiliate_enabled: false,
    ...overrides,
  }
}

export function buildSetupStatus(overrides = {}) {
  return {
    needs_setup: false,
    step: 'completed',
    ...overrides,
  }
}

export function buildDashboardSnapshot() {
  return {
    generated_at: '2026-05-22T00:00:00Z',
    start_date: '2026-05-21',
    end_date: '2026-05-22',
    granularity: 'hour',
    stats: {
      total_api_keys: 12,
      active_api_keys: 10,
      total_accounts: 8,
      normal_accounts: 7,
      error_accounts: 1,
      today_requests: 345,
      total_requests: 6789,
      today_new_users: 2,
      total_users: 32,
      today_tokens: 120000,
      today_actual_cost: 18.3,
      today_account_cost: 19.7,
      today_cost: 21.2,
      total_tokens: 780000,
      total_actual_cost: 112.2,
      total_account_cost: 120.1,
      total_cost: 130.4,
      rpm: 45,
      tpm: 18000,
      average_duration_ms: 650,
      active_users: 9,
      uptime: 86400,
    },
    trend: [
      { timestamp: '2026-05-22 08:00', requests: 50, tokens: 12000, cost: 2.3, actual_cost: 2.0, account_cost: 2.2 },
      { timestamp: '2026-05-22 09:00', requests: 75, tokens: 18000, cost: 3.1, actual_cost: 2.8, account_cost: 3.0 },
    ],
    models: [
      { model_name: 'gpt-4o', request_count: 120, token_count: 200000, cost: 33.2, actual_cost: 30.1, account_cost: 31.0 },
    ],
    groups: [],
    users_trend: [],
  }
}

export function buildUserTrend() {
  return {
    trend: [
      { user_id: 1, username: 'admin', email: ADMIN_EMAIL, date: '2026-05-22 08:00', tokens: 12000 },
      { user_id: 1, username: 'admin', email: ADMIN_EMAIL, date: '2026-05-22 09:00', tokens: 18000 },
    ],
    start_date: '2026-05-21',
    end_date: '2026-05-22',
    granularity: 'hour',
  }
}

export function buildUserRanking() {
  return {
    ranking: [
      { user_id: 1, username: 'admin', email: ADMIN_EMAIL, actual_cost: 12.5, request_count: 230, token_count: 80000 },
    ],
    total_actual_cost: 12.5,
    total_requests: 230,
    total_tokens: 80000,
  }
}

export function buildProxyList() {
  return {
    items: [
      {
        id: 101,
        name: 'proxy-alpha',
        protocol: 'http',
        host: '127.0.0.1',
        port: 8080,
        username: '',
        password: '',
        status: 'active',
        runtime_status: 'healthy',
        health_status: 'healthy',
        account_count: 2,
        auto_failover_pool_enabled: true,
        failover_switch_count: 0,
        managed_by_subscription: false,
        latency_ms: 110,
        latency_status: 'success',
        quality_status: 'healthy',
        quality_grade: 'A',
        quality_score: 95,
        quality_checked: 1716336000,
        created_at: '2026-05-22T00:00:00Z',
        updated_at: '2026-05-22T00:00:00Z',
      },
    ],
    total: 1,
    page: 1,
    page_size: 20,
    pages: 1,
  }
}

export function buildGroups() {
  return [
    {
      id: 1,
      name: '默认分组',
      description: '默认开放分组',
      platform: 'openai',
      rate_multiplier: 1,
      rpm_limit: 0,
      status: 'active',
      subscription_type: 'standard',
      is_exclusive: false,
      daily_limit_usd: null,
      weekly_limit_usd: null,
      monthly_limit_usd: null,
      allow_image_generation: false,
      image_rate_independent: false,
      image_rate_multiplier: 1,
      image_price_1k: null,
      image_price_2k: null,
      image_price_4k: null,
      claude_code_only: false,
      fallback_group_id: null,
      fallback_group_id_on_invalid_request: null,
      allow_messages_dispatch: false,
      require_oauth_only: false,
      require_privacy_set: false,
      model_routing: null,
      model_routing_enabled: false,
      mcp_xml_inject: true,
      supported_model_scopes: ['claude', 'gemini_text', 'gemini_image'],
      account_count: 2,
      active_account_count: 2,
      rate_limited_account_count: 0,
      sort_order: 1,
      created_at: '2026-05-22T00:00:00Z',
      updated_at: '2026-05-22T00:00:00Z',
    },
    {
      id: 2,
      name: '高级订阅',
      description: '订阅专用分组',
      platform: 'openai',
      rate_multiplier: 1.2,
      rpm_limit: 120,
      status: 'active',
      subscription_type: 'subscription',
      is_exclusive: false,
      daily_limit_usd: 5,
      weekly_limit_usd: 25,
      monthly_limit_usd: 90,
      allow_image_generation: false,
      image_rate_independent: false,
      image_rate_multiplier: 1,
      image_price_1k: null,
      image_price_2k: null,
      image_price_4k: null,
      claude_code_only: false,
      fallback_group_id: null,
      fallback_group_id_on_invalid_request: null,
      allow_messages_dispatch: false,
      require_oauth_only: false,
      require_privacy_set: false,
      model_routing: null,
      model_routing_enabled: false,
      mcp_xml_inject: true,
      supported_model_scopes: ['claude', 'gemini_text', 'gemini_image'],
      account_count: 1,
      active_account_count: 1,
      rate_limited_account_count: 0,
      sort_order: 2,
      created_at: '2026-05-22T00:00:00Z',
      updated_at: '2026-05-22T00:00:00Z',
    },
  ]
}

export function buildAccounts() {
  return {
    items: [
      {
        id: 201,
        name: 'claude-main',
        notes: '主 Anthropic 账号',
        platform: 'anthropic',
        type: 'apikey',
        status: 'active',
        runtime_status: 'normal',
        schedulable: true,
        concurrency: 8,
        priority: 10,
        rate_multiplier: 1,
        load_factor: 1,
        groups: [
          { id: 1, name: '默认分组', is_exclusive: false },
        ],
        proxy: null,
        credentials: {
          api_key: 'sk-ant-e2e-main',
        },
        extra: {},
        created_at: '2026-05-22T00:00:00Z',
        updated_at: '2026-05-22T00:00:00Z',
        last_used_at: '2026-05-22T10:00:00Z',
        expires_at: null,
        auto_pause_on_expired: false,
      },
      {
        id: 202,
        name: 'ungrouped-openai',
        notes: '未分组 OpenAI 账号',
        platform: 'openai',
        type: 'apikey',
        status: 'inactive',
        runtime_status: 'normal',
        schedulable: false,
        concurrency: 2,
        priority: 5,
        rate_multiplier: 1,
        load_factor: 1,
        groups: [],
        proxy: {
          id: 101,
          name: 'proxy-alpha',
          country_code: 'HK',
        },
        credentials: {
          api_key: 'sk-openai-e2e-ungrouped',
        },
        extra: {},
        created_at: '2026-05-22T00:00:00Z',
        updated_at: '2026-05-22T00:00:00Z',
        last_used_at: null,
        expires_at: null,
        auto_pause_on_expired: false,
      },
    ],
    total: 2,
    page: 1,
    page_size: 20,
    pages: 1,
  }
}

export function buildBatchTodayStats() {
  return {
    stats: {
      '201': {
        requests: 56,
        tokens: 18234,
        cost: 3.42,
        user_cost: 3.42,
      },
      '202': {
        requests: 0,
        tokens: 0,
        cost: 0,
        user_cost: 0,
      },
    },
  }
}

export function buildGroupUsageSummary() {
  return [
    {
      group_id: 1,
      today_cost: 3.42,
      total_cost: 18.5,
    },
    {
      group_id: 2,
      today_cost: 1.2,
      total_cost: 9.7,
    },
  ]
}

export function buildGroupCapacitySummary() {
  return [
    {
      group_id: 1,
      concurrency_used: 3,
      concurrency_max: 10,
      sessions_used: 1,
      sessions_max: 5,
      rpm_used: 45,
      rpm_max: 300,
    },
    {
      group_id: 2,
      concurrency_used: 1,
      concurrency_max: 6,
      sessions_used: 1,
      sessions_max: 3,
      rpm_used: 20,
      rpm_max: 120,
    },
  ]
}

export function buildProxySubscriptions() {
  return {
    items: [],
    total: 0,
    page: 1,
    page_size: 20,
    pages: 1,
  }
}

export function buildMihomoStatus() {
  return {
    config_path: '/tmp/mihomo/config.yaml',
    available_regions: ['HK', 'SG'],
    settings: {
      protocol: 'socks5h',
      target_host: '127.0.0.1',
      start_port: 41001,
      listener_count: 4,
      controller_url: 'http://127.0.0.1:9097',
      controller_secret: '',
      proxy_name_prefix: 'mihomo',
      listener_regions: ['', '', '', ''],
      auto_optimize: false,
      country_filter: '',
    },
  }
}

export function buildCheckinStatus() {
  return {
    enabled: false,
    luck_enabled: false,
    blindbox_enabled: false,
    can_checkin: false,
    streak_days: 0,
    today_reward: null,
    min_reward: 0,
    max_reward: 0,
    min_multiplier: 1,
    max_multiplier: 1,
    balance: 88.5,
  }
}

export function buildActiveSubscriptions() {
  return []
}

export function buildSettings() {
  return {
    registration_enabled: false,
    email_verify_enabled: false,
    registration_email_suffix_whitelist: [],
    promo_code_enabled: true,
    redeem_code_format: {
      prefix: '',
      suffix: '',
      random_length: 8,
      separator: '',
      group_size: 4,
      group_count: 2,
      chars_per_group: 4,
      charset: 'mixed',
      letter_case: 'upper',
    },
    balance_code_format: {
      prefix: '',
      suffix: '',
      random_length: 8,
      separator: '',
      group_size: 4,
      group_count: 2,
      chars_per_group: 4,
      charset: 'mixed',
      letter_case: 'upper',
    },
    concurrency_code_format: {
      prefix: '',
      suffix: '',
      random_length: 8,
      separator: '',
      group_size: 4,
      group_count: 2,
      chars_per_group: 4,
      charset: 'mixed',
      letter_case: 'upper',
    },
    subscription_code_format: {
      prefix: '',
      suffix: '',
      random_length: 8,
      separator: '',
      group_size: 4,
      group_count: 2,
      chars_per_group: 4,
      charset: 'mixed',
      letter_case: 'upper',
    },
    password_reset_enabled: false,
    frontend_url: '',
    invitation_code_enabled: false,
    invitation_code_format: {
      prefix: '',
      suffix: '',
      random_length: 8,
      separator: '',
      group_size: 4,
      group_count: 2,
      chars_per_group: 4,
      charset: 'mixed',
      letter_case: 'upper',
    },
    totp_enabled: false,
    totp_encryption_key_configured: true,
    login_agreement_enabled: false,
    login_agreement_mode: 'modal',
    login_agreement_updated_at: '2026-03-31',
    login_agreement_documents: [],
    default_balance: 0,
    affiliate_code_format: {
      prefix: '',
      suffix: '',
      random_length: 8,
      separator: '',
      group_size: 4,
      group_count: 2,
      chars_per_group: 4,
      charset: 'mixed',
      letter_case: 'upper',
    },
    affiliate_rebate_rate: 0,
    affiliate_rebate_freeze_hours: 0,
    affiliate_rebate_duration_days: 0,
    affiliate_rebate_per_invitee_cap: 0,
    default_concurrency: 5,
    default_user_rpm_limit: 0,
    default_subscriptions: [],
    force_email_on_third_party_signup: false,
    site_name: 'Sub2API',
    site_logo: '',
    site_subtitle: 'Subscription to API Conversion Platform',
    api_base_url: '',
    contact_info: '',
    doc_url: '',
    home_content: '',
    home_nav_links_enabled: true,
    home_nav_leaderboard_enabled: true,
    home_nav_key_usage_enabled: true,
    home_nav_monitoring_enabled: true,
    home_nav_pricing_enabled: true,
    leaderboard_balance_enabled: true,
    leaderboard_consumption_enabled: true,
    leaderboard_transfer_enabled: true,
    leaderboard_checkin_enabled: true,
    leaderboard_include_admin_enabled: false,
    hide_ccs_import_button: false,
    table_default_page_size: 20,
    table_page_size_options: [10, 20, 50, 100],
    backend_mode_enabled: false,
    custom_menu_items: [],
    custom_endpoints: [],
    smtp_host: '',
    smtp_port: 587,
    smtp_username: '',
    smtp_password_configured: false,
    smtp_from_email: '',
    smtp_from_name: '',
    smtp_use_tls: true,
    turnstile_enabled: false,
    turnstile_site_key: '',
    turnstile_secret_key_configured: false,
    linuxdo_connect_enabled: false,
    linuxdo_connect_client_id: '',
    linuxdo_connect_client_secret_configured: false,
    linuxdo_connect_redirect_url: '',
    dingtalk_connect_enabled: false,
    dingtalk_connect_client_id: '',
    dingtalk_connect_client_secret_configured: false,
    dingtalk_connect_redirect_url: '',
    dingtalk_connect_corp_restriction_policy: 'none',
    dingtalk_connect_internal_corp_id: '',
    dingtalk_connect_bypass_registration: false,
    dingtalk_connect_sync_corp_email: false,
    dingtalk_connect_sync_display_name: false,
    dingtalk_connect_sync_dept: false,
    dingtalk_connect_sync_corp_email_attr_key: 'dingtalk_email',
    dingtalk_connect_sync_display_name_attr_key: 'dingtalk_name',
    dingtalk_connect_sync_dept_attr_key: 'dingtalk_department',
    dingtalk_connect_sync_corp_email_attr_name: '钉钉企业邮箱',
    dingtalk_connect_sync_display_name_attr_name: '钉钉姓名',
    dingtalk_connect_sync_dept_attr_name: '钉钉部门',
    wechat_connect_enabled: false,
    wechat_connect_app_id: '',
    wechat_connect_app_secret_configured: false,
    wechat_connect_open_app_id: '',
    wechat_connect_open_app_secret_configured: false,
    wechat_connect_mp_app_id: '',
    wechat_connect_mp_app_secret_configured: false,
    wechat_connect_mobile_app_id: '',
    wechat_connect_mobile_app_secret_configured: false,
    wechat_connect_open_enabled: false,
    wechat_connect_mp_enabled: false,
    wechat_connect_mobile_enabled: false,
    wechat_connect_mode: 'open',
    wechat_connect_scopes: 'snsapi_login',
    wechat_connect_redirect_url: '',
    wechat_connect_frontend_redirect_url: '/auth/wechat/callback',
    oidc_connect_enabled: false,
    oidc_connect_provider_name: 'OIDC',
    oidc_connect_client_id: '',
    oidc_connect_client_secret_configured: false,
    oidc_connect_issuer_url: '',
    oidc_connect_discovery_url: '',
    oidc_connect_authorize_url: '',
    oidc_connect_token_url: '',
    oidc_connect_userinfo_url: '',
    oidc_connect_jwks_url: '',
    oidc_connect_scopes: 'openid email profile',
    oidc_connect_redirect_url: '',
    oidc_connect_frontend_redirect_url: '/auth/oidc/callback',
    oidc_connect_token_auth_method: 'client_secret_post',
    oidc_connect_use_pkce: false,
    oidc_connect_validate_id_token: false,
    oidc_connect_allowed_signing_algs: 'RS256,ES256,PS256',
    oidc_connect_clock_skew_seconds: 120,
    oidc_connect_require_email_verified: false,
    oidc_connect_userinfo_email_path: '',
    oidc_connect_userinfo_id_path: '',
    oidc_connect_userinfo_username_path: '',
    github_oauth_enabled: false,
    github_oauth_client_id: '',
    github_oauth_client_secret_configured: false,
    github_oauth_redirect_url: '',
    github_oauth_frontend_redirect_url: '/auth/oauth/callback',
    google_oauth_enabled: false,
    google_oauth_client_id: '',
    google_oauth_client_secret_configured: false,
    google_oauth_redirect_url: '',
    google_oauth_frontend_redirect_url: '/auth/oauth/callback',
    enable_model_fallback: false,
    fallback_model_anthropic: 'claude-3-5-sonnet-20241022',
    fallback_model_openai: 'gpt-4o',
    fallback_model_gemini: 'gemini-2.5-pro',
    fallback_model_antigravity: 'gemini-2.5-pro',
    enable_identity_patch: true,
    identity_patch_prompt: '',
    ops_monitoring_enabled: true,
    ops_realtime_monitoring_enabled: true,
    ops_query_mode_default: 'auto',
    ops_metrics_interval_seconds: 60,
    min_claude_code_version: '',
    max_claude_code_version: '',
    allow_ungrouped_key_scheduling: false,
    enable_fingerprint_unification: true,
    enable_metadata_passthrough: false,
    enable_cch_signing: false,
    enable_anthropic_cache_ttl_1h_injection: false,
    rewrite_message_cache_control: false,
    antigravity_user_agent_version: '',
    openai_codex_user_agent: '',
    payment_enabled: false,
    risk_control_enabled: false,
    payment_min_amount: 1,
    payment_max_amount: 10000,
    payment_daily_limit: 50000,
    payment_order_timeout_minutes: 30,
    payment_max_pending_orders: 3,
    payment_enabled_types: [],
    payment_balance_disabled: false,
    payment_balance_recharge_multiplier: 1,
    payment_recharge_fee_rate: 0,
    payment_load_balance_strategy: 'round-robin',
    payment_product_name_prefix: '',
    payment_product_name_suffix: '',
    payment_help_image_url: '',
    payment_help_text: '',
    payment_cancel_rate_limit_enabled: false,
    payment_cancel_rate_limit_max: 10,
    payment_cancel_rate_limit_window: 1,
    payment_cancel_rate_limit_unit: 'day',
    payment_cancel_rate_limit_window_mode: 'rolling',
    payment_alipay_force_qrcode: false,
    payment_visible_method_alipay_source: '',
    payment_visible_method_wxpay_source: '',
    payment_visible_method_alipay_enabled: false,
    payment_visible_method_wxpay_enabled: false,
    openai_advanced_scheduler_enabled: false,
    balance_low_notify_enabled: false,
    balance_low_notify_threshold: 0,
    balance_low_notify_recharge_url: '',
    account_quota_notify_enabled: false,
    account_quota_notify_emails: [],
    checkin_enabled: false,
    checkin_min_balance: 0,
    checkin_max_balance: 0,
    checkin_luck_enabled: false,
    checkin_luck_min_multiplier: 1,
    checkin_luck_max_multiplier: 1,
    checkin_blindbox_enabled: false,
    checkin_blindbox_trigger_type: 'streak',
    checkin_blindbox_interval: 7,
    channel_monitor_enabled: true,
    channel_monitor_default_interval_seconds: 60,
    available_channels_enabled: false,
    transfer_enabled: false,
    transfer_fee_rate: 0.01,
    transfer_min_amount: 0.01,
    transfer_max_amount: 1000,
    transfer_daily_limit: 1000,
    transfer_daily_count_limit: 50,
    transfer_vip_fee_exempt: false,
    redpacket_enabled: false,
    redpacket_max_count: 100,
    redpacket_expire_hours: 24,
    affiliate_enabled: false,
  }
}
