// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/balanceredpacket"
	"github.com/Wei-Shaw/sub2api/ent/balanceredpacketclaim"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// BalanceRedPacketQuery is the builder for querying BalanceRedPacket entities.
type BalanceRedPacketQuery struct {
	config
	ctx        *QueryContext
	order      []balanceredpacket.OrderOption
	inters     []Interceptor
	predicates []predicate.BalanceRedPacket
	withSender *UserQuery
	withClaims *BalanceRedPacketClaimQuery
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BalanceRedPacketQuery builder.
func (_q *BalanceRedPacketQuery) Where(ps ...predicate.BalanceRedPacket) *BalanceRedPacketQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *BalanceRedPacketQuery) Limit(limit int) *BalanceRedPacketQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *BalanceRedPacketQuery) Offset(offset int) *BalanceRedPacketQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *BalanceRedPacketQuery) Unique(unique bool) *BalanceRedPacketQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *BalanceRedPacketQuery) Order(o ...balanceredpacket.OrderOption) *BalanceRedPacketQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QuerySender chains the current query on the "sender" edge.
func (_q *BalanceRedPacketQuery) QuerySender() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(balanceredpacket.Table, balanceredpacket.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, balanceredpacket.SenderTable, balanceredpacket.SenderColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryClaims chains the current query on the "claims" edge.
func (_q *BalanceRedPacketQuery) QueryClaims() *BalanceRedPacketClaimQuery {
	query := (&BalanceRedPacketClaimClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(balanceredpacket.Table, balanceredpacket.FieldID, selector),
			sqlgraph.To(balanceredpacketclaim.Table, balanceredpacketclaim.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, balanceredpacket.ClaimsTable, balanceredpacket.ClaimsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first BalanceRedPacket entity from the query.
// Returns a *NotFoundError when no BalanceRedPacket was found.
func (_q *BalanceRedPacketQuery) First(ctx context.Context) (*BalanceRedPacket, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{balanceredpacket.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *BalanceRedPacketQuery) FirstX(ctx context.Context) *BalanceRedPacket {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first BalanceRedPacket ID from the query.
// Returns a *NotFoundError when no BalanceRedPacket ID was found.
func (_q *BalanceRedPacketQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{balanceredpacket.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *BalanceRedPacketQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single BalanceRedPacket entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one BalanceRedPacket entity is found.
// Returns a *NotFoundError when no BalanceRedPacket entities are found.
func (_q *BalanceRedPacketQuery) Only(ctx context.Context) (*BalanceRedPacket, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{balanceredpacket.Label}
	default:
		return nil, &NotSingularError{balanceredpacket.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *BalanceRedPacketQuery) OnlyX(ctx context.Context) *BalanceRedPacket {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only BalanceRedPacket ID in the query.
// Returns a *NotSingularError when more than one BalanceRedPacket ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *BalanceRedPacketQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{balanceredpacket.Label}
	default:
		err = &NotSingularError{balanceredpacket.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *BalanceRedPacketQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of BalanceRedPackets.
func (_q *BalanceRedPacketQuery) All(ctx context.Context) ([]*BalanceRedPacket, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*BalanceRedPacket, *BalanceRedPacketQuery]()
	return withInterceptors[[]*BalanceRedPacket](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *BalanceRedPacketQuery) AllX(ctx context.Context) []*BalanceRedPacket {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of BalanceRedPacket IDs.
func (_q *BalanceRedPacketQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(balanceredpacket.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *BalanceRedPacketQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *BalanceRedPacketQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*BalanceRedPacketQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *BalanceRedPacketQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *BalanceRedPacketQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *BalanceRedPacketQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BalanceRedPacketQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *BalanceRedPacketQuery) Clone() *BalanceRedPacketQuery {
	if _q == nil {
		return nil
	}
	return &BalanceRedPacketQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]balanceredpacket.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.BalanceRedPacket{}, _q.predicates...),
		withSender: _q.withSender.Clone(),
		withClaims: _q.withClaims.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithSender tells the query-builder to eager-load the nodes that are connected to
// the "sender" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *BalanceRedPacketQuery) WithSender(opts ...func(*UserQuery)) *BalanceRedPacketQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSender = query
	return _q
}

// WithClaims tells the query-builder to eager-load the nodes that are connected to
// the "claims" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *BalanceRedPacketQuery) WithClaims(opts ...func(*BalanceRedPacketClaimQuery)) *BalanceRedPacketQuery {
	query := (&BalanceRedPacketClaimClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withClaims = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		SenderID int64 `json:"sender_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.BalanceRedPacket.Query().
//		GroupBy(balanceredpacket.FieldSenderID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *BalanceRedPacketQuery) GroupBy(field string, fields ...string) *BalanceRedPacketGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &BalanceRedPacketGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = balanceredpacket.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		SenderID int64 `json:"sender_id,omitempty"`
//	}
//
//	client.BalanceRedPacket.Query().
//		Select(balanceredpacket.FieldSenderID).
//		Scan(ctx, &v)
func (_q *BalanceRedPacketQuery) Select(fields ...string) *BalanceRedPacketSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &BalanceRedPacketSelect{BalanceRedPacketQuery: _q}
	sbuild.label = balanceredpacket.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a BalanceRedPacketSelect configured with the given aggregations.
func (_q *BalanceRedPacketQuery) Aggregate(fns ...AggregateFunc) *BalanceRedPacketSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *BalanceRedPacketQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !balanceredpacket.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *BalanceRedPacketQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*BalanceRedPacket, error) {
	var (
		nodes       = []*BalanceRedPacket{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withSender != nil,
			_q.withClaims != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*BalanceRedPacket).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &BalanceRedPacket{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withSender; query != nil {
		if err := _q.loadSender(ctx, query, nodes, nil,
			func(n *BalanceRedPacket, e *User) { n.Edges.Sender = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withClaims; query != nil {
		if err := _q.loadClaims(ctx, query, nodes,
			func(n *BalanceRedPacket) { n.Edges.Claims = []*BalanceRedPacketClaim{} },
			func(n *BalanceRedPacket, e *BalanceRedPacketClaim) { n.Edges.Claims = append(n.Edges.Claims, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *BalanceRedPacketQuery) loadSender(ctx context.Context, query *UserQuery, nodes []*BalanceRedPacket, init func(*BalanceRedPacket), assign func(*BalanceRedPacket, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*BalanceRedPacket)
	for i := range nodes {
		fk := nodes[i].SenderID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "sender_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *BalanceRedPacketQuery) loadClaims(ctx context.Context, query *BalanceRedPacketClaimQuery, nodes []*BalanceRedPacket, init func(*BalanceRedPacket), assign func(*BalanceRedPacket, *BalanceRedPacketClaim)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*BalanceRedPacket)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(balanceredpacketclaim.FieldRedpacketID)
	}
	query.Where(predicate.BalanceRedPacketClaim(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(balanceredpacket.ClaimsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.RedpacketID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "redpacket_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *BalanceRedPacketQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *BalanceRedPacketQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(balanceredpacket.Table, balanceredpacket.Columns, sqlgraph.NewFieldSpec(balanceredpacket.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, balanceredpacket.FieldID)
		for i := range fields {
			if fields[i] != balanceredpacket.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withSender != nil {
			_spec.Node.AddColumnOnce(balanceredpacket.FieldSenderID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *BalanceRedPacketQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(balanceredpacket.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = balanceredpacket.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *BalanceRedPacketQuery) ForUpdate(opts ...sql.LockOption) *BalanceRedPacketQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *BalanceRedPacketQuery) ForShare(opts ...sql.LockOption) *BalanceRedPacketQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// BalanceRedPacketGroupBy is the group-by builder for BalanceRedPacket entities.
type BalanceRedPacketGroupBy struct {
	selector
	build *BalanceRedPacketQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *BalanceRedPacketGroupBy) Aggregate(fns ...AggregateFunc) *BalanceRedPacketGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *BalanceRedPacketGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BalanceRedPacketQuery, *BalanceRedPacketGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *BalanceRedPacketGroupBy) sqlScan(ctx context.Context, root *BalanceRedPacketQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// BalanceRedPacketSelect is the builder for selecting fields of BalanceRedPacket entities.
type BalanceRedPacketSelect struct {
	*BalanceRedPacketQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *BalanceRedPacketSelect) Aggregate(fns ...AggregateFunc) *BalanceRedPacketSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *BalanceRedPacketSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BalanceRedPacketQuery, *BalanceRedPacketSelect](ctx, _s.BalanceRedPacketQuery, _s, _s.inters, v)
}

func (_s *BalanceRedPacketSelect) sqlScan(ctx context.Context, root *BalanceRedPacketQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
