// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/balanceredpacket"
	"github.com/Wei-Shaw/sub2api/ent/balanceredpacketclaim"
)

// BalanceRedPacketClaimCreate is the builder for creating a BalanceRedPacketClaim entity.
type BalanceRedPacketClaimCreate struct {
	config
	mutation *BalanceRedPacketClaimMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetRedpacketID sets the "redpacket_id" field.
func (_c *BalanceRedPacketClaimCreate) SetRedpacketID(v int64) *BalanceRedPacketClaimCreate {
	_c.mutation.SetRedpacketID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *BalanceRedPacketClaimCreate) SetUserID(v int64) *BalanceRedPacketClaimCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *BalanceRedPacketClaimCreate) SetAmount(v float64) *BalanceRedPacketClaimCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetTransferID sets the "transfer_id" field.
func (_c *BalanceRedPacketClaimCreate) SetTransferID(v int64) *BalanceRedPacketClaimCreate {
	_c.mutation.SetTransferID(v)
	return _c
}

// SetNillableTransferID sets the "transfer_id" field if the given value is not nil.
func (_c *BalanceRedPacketClaimCreate) SetNillableTransferID(v *int64) *BalanceRedPacketClaimCreate {
	if v != nil {
		_c.SetTransferID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *BalanceRedPacketClaimCreate) SetCreatedAt(v time.Time) *BalanceRedPacketClaimCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *BalanceRedPacketClaimCreate) SetNillableCreatedAt(v *time.Time) *BalanceRedPacketClaimCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetRedpacket sets the "redpacket" edge to the BalanceRedPacket entity.
func (_c *BalanceRedPacketClaimCreate) SetRedpacket(v *BalanceRedPacket) *BalanceRedPacketClaimCreate {
	return _c.SetRedpacketID(v.ID)
}

// Mutation returns the BalanceRedPacketClaimMutation object of the builder.
func (_c *BalanceRedPacketClaimCreate) Mutation() *BalanceRedPacketClaimMutation {
	return _c.mutation
}

// Save creates the BalanceRedPacketClaim in the database.
func (_c *BalanceRedPacketClaimCreate) Save(ctx context.Context) (*BalanceRedPacketClaim, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BalanceRedPacketClaimCreate) SaveX(ctx context.Context) *BalanceRedPacketClaim {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BalanceRedPacketClaimCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BalanceRedPacketClaimCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BalanceRedPacketClaimCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := balanceredpacketclaim.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BalanceRedPacketClaimCreate) check() error {
	if _, ok := _c.mutation.RedpacketID(); !ok {
		return &ValidationError{Name: "redpacket_id", err: errors.New(`ent: missing required field "BalanceRedPacketClaim.redpacket_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "BalanceRedPacketClaim.user_id"`)}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "BalanceRedPacketClaim.amount"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "BalanceRedPacketClaim.created_at"`)}
	}
	if len(_c.mutation.RedpacketIDs()) == 0 {
		return &ValidationError{Name: "redpacket", err: errors.New(`ent: missing required edge "BalanceRedPacketClaim.redpacket"`)}
	}
	return nil
}

func (_c *BalanceRedPacketClaimCreate) sqlSave(ctx context.Context) (*BalanceRedPacketClaim, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BalanceRedPacketClaimCreate) createSpec() (*BalanceRedPacketClaim, *sqlgraph.CreateSpec) {
	var (
		_node = &BalanceRedPacketClaim{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(balanceredpacketclaim.Table, sqlgraph.NewFieldSpec(balanceredpacketclaim.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(balanceredpacketclaim.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(balanceredpacketclaim.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.TransferID(); ok {
		_spec.SetField(balanceredpacketclaim.FieldTransferID, field.TypeInt64, value)
		_node.TransferID = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(balanceredpacketclaim.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.RedpacketIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   balanceredpacketclaim.RedpacketTable,
			Columns: []string{balanceredpacketclaim.RedpacketColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(balanceredpacket.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RedpacketID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BalanceRedPacketClaim.Create().
//		SetRedpacketID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BalanceRedPacketClaimUpsert) {
//			SetRedpacketID(v+v).
//		}).
//		Exec(ctx)
func (_c *BalanceRedPacketClaimCreate) OnConflict(opts ...sql.ConflictOption) *BalanceRedPacketClaimUpsertOne {
	_c.conflict = opts
	return &BalanceRedPacketClaimUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BalanceRedPacketClaim.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BalanceRedPacketClaimCreate) OnConflictColumns(columns ...string) *BalanceRedPacketClaimUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BalanceRedPacketClaimUpsertOne{
		create: _c,
	}
}

type (
	// BalanceRedPacketClaimUpsertOne is the builder for "upsert"-ing
	//  one BalanceRedPacketClaim node.
	BalanceRedPacketClaimUpsertOne struct {
		create *BalanceRedPacketClaimCreate
	}

	// BalanceRedPacketClaimUpsert is the "OnConflict" setter.
	BalanceRedPacketClaimUpsert struct {
		*sql.UpdateSet
	}
)

// SetRedpacketID sets the "redpacket_id" field.
func (u *BalanceRedPacketClaimUpsert) SetRedpacketID(v int64) *BalanceRedPacketClaimUpsert {
	u.Set(balanceredpacketclaim.FieldRedpacketID, v)
	return u
}

// UpdateRedpacketID sets the "redpacket_id" field to the value that was provided on create.
func (u *BalanceRedPacketClaimUpsert) UpdateRedpacketID() *BalanceRedPacketClaimUpsert {
	u.SetExcluded(balanceredpacketclaim.FieldRedpacketID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *BalanceRedPacketClaimUpsert) SetUserID(v int64) *BalanceRedPacketClaimUpsert {
	u.Set(balanceredpacketclaim.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *BalanceRedPacketClaimUpsert) UpdateUserID() *BalanceRedPacketClaimUpsert {
	u.SetExcluded(balanceredpacketclaim.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *BalanceRedPacketClaimUpsert) AddUserID(v int64) *BalanceRedPacketClaimUpsert {
	u.Add(balanceredpacketclaim.FieldUserID, v)
	return u
}

// SetAmount sets the "amount" field.
func (u *BalanceRedPacketClaimUpsert) SetAmount(v float64) *BalanceRedPacketClaimUpsert {
	u.Set(balanceredpacketclaim.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *BalanceRedPacketClaimUpsert) UpdateAmount() *BalanceRedPacketClaimUpsert {
	u.SetExcluded(balanceredpacketclaim.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *BalanceRedPacketClaimUpsert) AddAmount(v float64) *BalanceRedPacketClaimUpsert {
	u.Add(balanceredpacketclaim.FieldAmount, v)
	return u
}

// SetTransferID sets the "transfer_id" field.
func (u *BalanceRedPacketClaimUpsert) SetTransferID(v int64) *BalanceRedPacketClaimUpsert {
	u.Set(balanceredpacketclaim.FieldTransferID, v)
	return u
}

// UpdateTransferID sets the "transfer_id" field to the value that was provided on create.
func (u *BalanceRedPacketClaimUpsert) UpdateTransferID() *BalanceRedPacketClaimUpsert {
	u.SetExcluded(balanceredpacketclaim.FieldTransferID)
	return u
}

// AddTransferID adds v to the "transfer_id" field.
func (u *BalanceRedPacketClaimUpsert) AddTransferID(v int64) *BalanceRedPacketClaimUpsert {
	u.Add(balanceredpacketclaim.FieldTransferID, v)
	return u
}

// ClearTransferID clears the value of the "transfer_id" field.
func (u *BalanceRedPacketClaimUpsert) ClearTransferID() *BalanceRedPacketClaimUpsert {
	u.SetNull(balanceredpacketclaim.FieldTransferID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.BalanceRedPacketClaim.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BalanceRedPacketClaimUpsertOne) UpdateNewValues() *BalanceRedPacketClaimUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(balanceredpacketclaim.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BalanceRedPacketClaim.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *BalanceRedPacketClaimUpsertOne) Ignore() *BalanceRedPacketClaimUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BalanceRedPacketClaimUpsertOne) DoNothing() *BalanceRedPacketClaimUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BalanceRedPacketClaimCreate.OnConflict
// documentation for more info.
func (u *BalanceRedPacketClaimUpsertOne) Update(set func(*BalanceRedPacketClaimUpsert)) *BalanceRedPacketClaimUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BalanceRedPacketClaimUpsert{UpdateSet: update})
	}))
	return u
}

// SetRedpacketID sets the "redpacket_id" field.
func (u *BalanceRedPacketClaimUpsertOne) SetRedpacketID(v int64) *BalanceRedPacketClaimUpsertOne {
	return u.Update(func(s *BalanceRedPacketClaimUpsert) {
		s.SetRedpacketID(v)
	})
}

// UpdateRedpacketID sets the "redpacket_id" field to the value that was provided on create.
func (u *BalanceRedPacketClaimUpsertOne) UpdateRedpacketID() *BalanceRedPacketClaimUpsertOne {
	return u.Update(func(s *BalanceRedPacketClaimUpsert) {
		s.UpdateRedpacketID()
	})
}

// SetUserID sets the "user_id" field.
func (u *BalanceRedPacketClaimUpsertOne) SetUserID(v int64) *BalanceRedPacketClaimUpsertOne {
	return u.Update(func(s *BalanceRedPacketClaimUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *BalanceRedPacketClaimUpsertOne) AddUserID(v int64) *BalanceRedPacketClaimUpsertOne {
	return u.Update(func(s *BalanceRedPacketClaimUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *BalanceRedPacketClaimUpsertOne) UpdateUserID() *BalanceRedPacketClaimUpsertOne {
	return u.Update(func(s *BalanceRedPacketClaimUpsert) {
		s.UpdateUserID()
	})
}

// SetAmount sets the "amount" field.
func (u *BalanceRedPacketClaimUpsertOne) SetAmount(v float64) *BalanceRedPacketClaimUpsertOne {
	return u.Update(func(s *BalanceRedPacketClaimUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *BalanceRedPacketClaimUpsertOne) AddAmount(v float64) *BalanceRedPacketClaimUpsertOne {
	return u.Update(func(s *BalanceRedPacketClaimUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *BalanceRedPacketClaimUpsertOne) UpdateAmount() *BalanceRedPacketClaimUpsertOne {
	return u.Update(func(s *BalanceRedPacketClaimUpsert) {
		s.UpdateAmount()
	})
}

// SetTransferID sets the "transfer_id" field.
func (u *BalanceRedPacketClaimUpsertOne) SetTransferID(v int64) *BalanceRedPacketClaimUpsertOne {
	return u.Update(func(s *BalanceRedPacketClaimUpsert) {
		s.SetTransferID(v)
	})
}

// AddTransferID adds v to the "transfer_id" field.
func (u *BalanceRedPacketClaimUpsertOne) AddTransferID(v int64) *BalanceRedPacketClaimUpsertOne {
	return u.Update(func(s *BalanceRedPacketClaimUpsert) {
		s.AddTransferID(v)
	})
}

// UpdateTransferID sets the "transfer_id" field to the value that was provided on create.
func (u *BalanceRedPacketClaimUpsertOne) UpdateTransferID() *BalanceRedPacketClaimUpsertOne {
	return u.Update(func(s *BalanceRedPacketClaimUpsert) {
		s.UpdateTransferID()
	})
}

// ClearTransferID clears the value of the "transfer_id" field.
func (u *BalanceRedPacketClaimUpsertOne) ClearTransferID() *BalanceRedPacketClaimUpsertOne {
	return u.Update(func(s *BalanceRedPacketClaimUpsert) {
		s.ClearTransferID()
	})
}

// Exec executes the query.
func (u *BalanceRedPacketClaimUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BalanceRedPacketClaimCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BalanceRedPacketClaimUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *BalanceRedPacketClaimUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *BalanceRedPacketClaimUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// BalanceRedPacketClaimCreateBulk is the builder for creating many BalanceRedPacketClaim entities in bulk.
type BalanceRedPacketClaimCreateBulk struct {
	config
	err      error
	builders []*BalanceRedPacketClaimCreate
	conflict []sql.ConflictOption
}

// Save creates the BalanceRedPacketClaim entities in the database.
func (_c *BalanceRedPacketClaimCreateBulk) Save(ctx context.Context) ([]*BalanceRedPacketClaim, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BalanceRedPacketClaim, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BalanceRedPacketClaimMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BalanceRedPacketClaimCreateBulk) SaveX(ctx context.Context) []*BalanceRedPacketClaim {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BalanceRedPacketClaimCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BalanceRedPacketClaimCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BalanceRedPacketClaim.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BalanceRedPacketClaimUpsert) {
//			SetRedpacketID(v+v).
//		}).
//		Exec(ctx)
func (_c *BalanceRedPacketClaimCreateBulk) OnConflict(opts ...sql.ConflictOption) *BalanceRedPacketClaimUpsertBulk {
	_c.conflict = opts
	return &BalanceRedPacketClaimUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BalanceRedPacketClaim.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BalanceRedPacketClaimCreateBulk) OnConflictColumns(columns ...string) *BalanceRedPacketClaimUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BalanceRedPacketClaimUpsertBulk{
		create: _c,
	}
}

// BalanceRedPacketClaimUpsertBulk is the builder for "upsert"-ing
// a bulk of BalanceRedPacketClaim nodes.
type BalanceRedPacketClaimUpsertBulk struct {
	create *BalanceRedPacketClaimCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.BalanceRedPacketClaim.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BalanceRedPacketClaimUpsertBulk) UpdateNewValues() *BalanceRedPacketClaimUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(balanceredpacketclaim.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BalanceRedPacketClaim.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *BalanceRedPacketClaimUpsertBulk) Ignore() *BalanceRedPacketClaimUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BalanceRedPacketClaimUpsertBulk) DoNothing() *BalanceRedPacketClaimUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BalanceRedPacketClaimCreateBulk.OnConflict
// documentation for more info.
func (u *BalanceRedPacketClaimUpsertBulk) Update(set func(*BalanceRedPacketClaimUpsert)) *BalanceRedPacketClaimUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BalanceRedPacketClaimUpsert{UpdateSet: update})
	}))
	return u
}

// SetRedpacketID sets the "redpacket_id" field.
func (u *BalanceRedPacketClaimUpsertBulk) SetRedpacketID(v int64) *BalanceRedPacketClaimUpsertBulk {
	return u.Update(func(s *BalanceRedPacketClaimUpsert) {
		s.SetRedpacketID(v)
	})
}

// UpdateRedpacketID sets the "redpacket_id" field to the value that was provided on create.
func (u *BalanceRedPacketClaimUpsertBulk) UpdateRedpacketID() *BalanceRedPacketClaimUpsertBulk {
	return u.Update(func(s *BalanceRedPacketClaimUpsert) {
		s.UpdateRedpacketID()
	})
}

// SetUserID sets the "user_id" field.
func (u *BalanceRedPacketClaimUpsertBulk) SetUserID(v int64) *BalanceRedPacketClaimUpsertBulk {
	return u.Update(func(s *BalanceRedPacketClaimUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *BalanceRedPacketClaimUpsertBulk) AddUserID(v int64) *BalanceRedPacketClaimUpsertBulk {
	return u.Update(func(s *BalanceRedPacketClaimUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *BalanceRedPacketClaimUpsertBulk) UpdateUserID() *BalanceRedPacketClaimUpsertBulk {
	return u.Update(func(s *BalanceRedPacketClaimUpsert) {
		s.UpdateUserID()
	})
}

// SetAmount sets the "amount" field.
func (u *BalanceRedPacketClaimUpsertBulk) SetAmount(v float64) *BalanceRedPacketClaimUpsertBulk {
	return u.Update(func(s *BalanceRedPacketClaimUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *BalanceRedPacketClaimUpsertBulk) AddAmount(v float64) *BalanceRedPacketClaimUpsertBulk {
	return u.Update(func(s *BalanceRedPacketClaimUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *BalanceRedPacketClaimUpsertBulk) UpdateAmount() *BalanceRedPacketClaimUpsertBulk {
	return u.Update(func(s *BalanceRedPacketClaimUpsert) {
		s.UpdateAmount()
	})
}

// SetTransferID sets the "transfer_id" field.
func (u *BalanceRedPacketClaimUpsertBulk) SetTransferID(v int64) *BalanceRedPacketClaimUpsertBulk {
	return u.Update(func(s *BalanceRedPacketClaimUpsert) {
		s.SetTransferID(v)
	})
}

// AddTransferID adds v to the "transfer_id" field.
func (u *BalanceRedPacketClaimUpsertBulk) AddTransferID(v int64) *BalanceRedPacketClaimUpsertBulk {
	return u.Update(func(s *BalanceRedPacketClaimUpsert) {
		s.AddTransferID(v)
	})
}

// UpdateTransferID sets the "transfer_id" field to the value that was provided on create.
func (u *BalanceRedPacketClaimUpsertBulk) UpdateTransferID() *BalanceRedPacketClaimUpsertBulk {
	return u.Update(func(s *BalanceRedPacketClaimUpsert) {
		s.UpdateTransferID()
	})
}

// ClearTransferID clears the value of the "transfer_id" field.
func (u *BalanceRedPacketClaimUpsertBulk) ClearTransferID() *BalanceRedPacketClaimUpsertBulk {
	return u.Update(func(s *BalanceRedPacketClaimUpsert) {
		s.ClearTransferID()
	})
}

// Exec executes the query.
func (u *BalanceRedPacketClaimUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the BalanceRedPacketClaimCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BalanceRedPacketClaimCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BalanceRedPacketClaimUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
