// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/balancetransfer"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// BalanceTransferUpdate is the builder for updating BalanceTransfer entities.
type BalanceTransferUpdate struct {
	config
	hooks    []Hook
	mutation *BalanceTransferMutation
}

// Where appends a list predicates to the BalanceTransferUpdate builder.
func (_u *BalanceTransferUpdate) Where(ps ...predicate.BalanceTransfer) *BalanceTransferUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSenderID sets the "sender_id" field.
func (_u *BalanceTransferUpdate) SetSenderID(v int64) *BalanceTransferUpdate {
	_u.mutation.SetSenderID(v)
	return _u
}

// SetNillableSenderID sets the "sender_id" field if the given value is not nil.
func (_u *BalanceTransferUpdate) SetNillableSenderID(v *int64) *BalanceTransferUpdate {
	if v != nil {
		_u.SetSenderID(*v)
	}
	return _u
}

// SetReceiverID sets the "receiver_id" field.
func (_u *BalanceTransferUpdate) SetReceiverID(v int64) *BalanceTransferUpdate {
	_u.mutation.SetReceiverID(v)
	return _u
}

// SetNillableReceiverID sets the "receiver_id" field if the given value is not nil.
func (_u *BalanceTransferUpdate) SetNillableReceiverID(v *int64) *BalanceTransferUpdate {
	if v != nil {
		_u.SetReceiverID(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *BalanceTransferUpdate) SetAmount(v float64) *BalanceTransferUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *BalanceTransferUpdate) SetNillableAmount(v *float64) *BalanceTransferUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *BalanceTransferUpdate) AddAmount(v float64) *BalanceTransferUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetFee sets the "fee" field.
func (_u *BalanceTransferUpdate) SetFee(v float64) *BalanceTransferUpdate {
	_u.mutation.ResetFee()
	_u.mutation.SetFee(v)
	return _u
}

// SetNillableFee sets the "fee" field if the given value is not nil.
func (_u *BalanceTransferUpdate) SetNillableFee(v *float64) *BalanceTransferUpdate {
	if v != nil {
		_u.SetFee(*v)
	}
	return _u
}

// AddFee adds value to the "fee" field.
func (_u *BalanceTransferUpdate) AddFee(v float64) *BalanceTransferUpdate {
	_u.mutation.AddFee(v)
	return _u
}

// SetFeeRate sets the "fee_rate" field.
func (_u *BalanceTransferUpdate) SetFeeRate(v float64) *BalanceTransferUpdate {
	_u.mutation.ResetFeeRate()
	_u.mutation.SetFeeRate(v)
	return _u
}

// SetNillableFeeRate sets the "fee_rate" field if the given value is not nil.
func (_u *BalanceTransferUpdate) SetNillableFeeRate(v *float64) *BalanceTransferUpdate {
	if v != nil {
		_u.SetFeeRate(*v)
	}
	return _u
}

// AddFeeRate adds value to the "fee_rate" field.
func (_u *BalanceTransferUpdate) AddFeeRate(v float64) *BalanceTransferUpdate {
	_u.mutation.AddFeeRate(v)
	return _u
}

// SetGrossAmount sets the "gross_amount" field.
func (_u *BalanceTransferUpdate) SetGrossAmount(v float64) *BalanceTransferUpdate {
	_u.mutation.ResetGrossAmount()
	_u.mutation.SetGrossAmount(v)
	return _u
}

// SetNillableGrossAmount sets the "gross_amount" field if the given value is not nil.
func (_u *BalanceTransferUpdate) SetNillableGrossAmount(v *float64) *BalanceTransferUpdate {
	if v != nil {
		_u.SetGrossAmount(*v)
	}
	return _u
}

// AddGrossAmount adds value to the "gross_amount" field.
func (_u *BalanceTransferUpdate) AddGrossAmount(v float64) *BalanceTransferUpdate {
	_u.mutation.AddGrossAmount(v)
	return _u
}

// SetTransferType sets the "transfer_type" field.
func (_u *BalanceTransferUpdate) SetTransferType(v string) *BalanceTransferUpdate {
	_u.mutation.SetTransferType(v)
	return _u
}

// SetNillableTransferType sets the "transfer_type" field if the given value is not nil.
func (_u *BalanceTransferUpdate) SetNillableTransferType(v *string) *BalanceTransferUpdate {
	if v != nil {
		_u.SetTransferType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *BalanceTransferUpdate) SetStatus(v string) *BalanceTransferUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *BalanceTransferUpdate) SetNillableStatus(v *string) *BalanceTransferUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetMemo sets the "memo" field.
func (_u *BalanceTransferUpdate) SetMemo(v string) *BalanceTransferUpdate {
	_u.mutation.SetMemo(v)
	return _u
}

// SetNillableMemo sets the "memo" field if the given value is not nil.
func (_u *BalanceTransferUpdate) SetNillableMemo(v *string) *BalanceTransferUpdate {
	if v != nil {
		_u.SetMemo(*v)
	}
	return _u
}

// ClearMemo clears the value of the "memo" field.
func (_u *BalanceTransferUpdate) ClearMemo() *BalanceTransferUpdate {
	_u.mutation.ClearMemo()
	return _u
}

// SetRedpacketID sets the "redpacket_id" field.
func (_u *BalanceTransferUpdate) SetRedpacketID(v int64) *BalanceTransferUpdate {
	_u.mutation.ResetRedpacketID()
	_u.mutation.SetRedpacketID(v)
	return _u
}

// SetNillableRedpacketID sets the "redpacket_id" field if the given value is not nil.
func (_u *BalanceTransferUpdate) SetNillableRedpacketID(v *int64) *BalanceTransferUpdate {
	if v != nil {
		_u.SetRedpacketID(*v)
	}
	return _u
}

// AddRedpacketID adds value to the "redpacket_id" field.
func (_u *BalanceTransferUpdate) AddRedpacketID(v int64) *BalanceTransferUpdate {
	_u.mutation.AddRedpacketID(v)
	return _u
}

// ClearRedpacketID clears the value of the "redpacket_id" field.
func (_u *BalanceTransferUpdate) ClearRedpacketID() *BalanceTransferUpdate {
	_u.mutation.ClearRedpacketID()
	return _u
}

// SetFrozenAt sets the "frozen_at" field.
func (_u *BalanceTransferUpdate) SetFrozenAt(v time.Time) *BalanceTransferUpdate {
	_u.mutation.SetFrozenAt(v)
	return _u
}

// SetNillableFrozenAt sets the "frozen_at" field if the given value is not nil.
func (_u *BalanceTransferUpdate) SetNillableFrozenAt(v *time.Time) *BalanceTransferUpdate {
	if v != nil {
		_u.SetFrozenAt(*v)
	}
	return _u
}

// ClearFrozenAt clears the value of the "frozen_at" field.
func (_u *BalanceTransferUpdate) ClearFrozenAt() *BalanceTransferUpdate {
	_u.mutation.ClearFrozenAt()
	return _u
}

// SetFrozenBy sets the "frozen_by" field.
func (_u *BalanceTransferUpdate) SetFrozenBy(v int64) *BalanceTransferUpdate {
	_u.mutation.ResetFrozenBy()
	_u.mutation.SetFrozenBy(v)
	return _u
}

// SetNillableFrozenBy sets the "frozen_by" field if the given value is not nil.
func (_u *BalanceTransferUpdate) SetNillableFrozenBy(v *int64) *BalanceTransferUpdate {
	if v != nil {
		_u.SetFrozenBy(*v)
	}
	return _u
}

// AddFrozenBy adds value to the "frozen_by" field.
func (_u *BalanceTransferUpdate) AddFrozenBy(v int64) *BalanceTransferUpdate {
	_u.mutation.AddFrozenBy(v)
	return _u
}

// ClearFrozenBy clears the value of the "frozen_by" field.
func (_u *BalanceTransferUpdate) ClearFrozenBy() *BalanceTransferUpdate {
	_u.mutation.ClearFrozenBy()
	return _u
}

// SetRevokeReason sets the "revoke_reason" field.
func (_u *BalanceTransferUpdate) SetRevokeReason(v string) *BalanceTransferUpdate {
	_u.mutation.SetRevokeReason(v)
	return _u
}

// SetNillableRevokeReason sets the "revoke_reason" field if the given value is not nil.
func (_u *BalanceTransferUpdate) SetNillableRevokeReason(v *string) *BalanceTransferUpdate {
	if v != nil {
		_u.SetRevokeReason(*v)
	}
	return _u
}

// ClearRevokeReason clears the value of the "revoke_reason" field.
func (_u *BalanceTransferUpdate) ClearRevokeReason() *BalanceTransferUpdate {
	_u.mutation.ClearRevokeReason()
	return _u
}

// SetSender sets the "sender" edge to the User entity.
func (_u *BalanceTransferUpdate) SetSender(v *User) *BalanceTransferUpdate {
	return _u.SetSenderID(v.ID)
}

// SetReceiver sets the "receiver" edge to the User entity.
func (_u *BalanceTransferUpdate) SetReceiver(v *User) *BalanceTransferUpdate {
	return _u.SetReceiverID(v.ID)
}

// Mutation returns the BalanceTransferMutation object of the builder.
func (_u *BalanceTransferUpdate) Mutation() *BalanceTransferMutation {
	return _u.mutation
}

// ClearSender clears the "sender" edge to the User entity.
func (_u *BalanceTransferUpdate) ClearSender() *BalanceTransferUpdate {
	_u.mutation.ClearSender()
	return _u
}

// ClearReceiver clears the "receiver" edge to the User entity.
func (_u *BalanceTransferUpdate) ClearReceiver() *BalanceTransferUpdate {
	_u.mutation.ClearReceiver()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BalanceTransferUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BalanceTransferUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BalanceTransferUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BalanceTransferUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BalanceTransferUpdate) check() error {
	if v, ok := _u.mutation.TransferType(); ok {
		if err := balancetransfer.TransferTypeValidator(v); err != nil {
			return &ValidationError{Name: "transfer_type", err: fmt.Errorf(`ent: validator failed for field "BalanceTransfer.transfer_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := balancetransfer.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "BalanceTransfer.status": %w`, err)}
		}
	}
	if _u.mutation.SenderCleared() && len(_u.mutation.SenderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BalanceTransfer.sender"`)
	}
	if _u.mutation.ReceiverCleared() && len(_u.mutation.ReceiverIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BalanceTransfer.receiver"`)
	}
	return nil
}

func (_u *BalanceTransferUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(balancetransfer.Table, balancetransfer.Columns, sqlgraph.NewFieldSpec(balancetransfer.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(balancetransfer.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(balancetransfer.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Fee(); ok {
		_spec.SetField(balancetransfer.FieldFee, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFee(); ok {
		_spec.AddField(balancetransfer.FieldFee, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FeeRate(); ok {
		_spec.SetField(balancetransfer.FieldFeeRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFeeRate(); ok {
		_spec.AddField(balancetransfer.FieldFeeRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.GrossAmount(); ok {
		_spec.SetField(balancetransfer.FieldGrossAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedGrossAmount(); ok {
		_spec.AddField(balancetransfer.FieldGrossAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TransferType(); ok {
		_spec.SetField(balancetransfer.FieldTransferType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(balancetransfer.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Memo(); ok {
		_spec.SetField(balancetransfer.FieldMemo, field.TypeString, value)
	}
	if _u.mutation.MemoCleared() {
		_spec.ClearField(balancetransfer.FieldMemo, field.TypeString)
	}
	if value, ok := _u.mutation.RedpacketID(); ok {
		_spec.SetField(balancetransfer.FieldRedpacketID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRedpacketID(); ok {
		_spec.AddField(balancetransfer.FieldRedpacketID, field.TypeInt64, value)
	}
	if _u.mutation.RedpacketIDCleared() {
		_spec.ClearField(balancetransfer.FieldRedpacketID, field.TypeInt64)
	}
	if value, ok := _u.mutation.FrozenAt(); ok {
		_spec.SetField(balancetransfer.FieldFrozenAt, field.TypeTime, value)
	}
	if _u.mutation.FrozenAtCleared() {
		_spec.ClearField(balancetransfer.FieldFrozenAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FrozenBy(); ok {
		_spec.SetField(balancetransfer.FieldFrozenBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFrozenBy(); ok {
		_spec.AddField(balancetransfer.FieldFrozenBy, field.TypeInt64, value)
	}
	if _u.mutation.FrozenByCleared() {
		_spec.ClearField(balancetransfer.FieldFrozenBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.RevokeReason(); ok {
		_spec.SetField(balancetransfer.FieldRevokeReason, field.TypeString, value)
	}
	if _u.mutation.RevokeReasonCleared() {
		_spec.ClearField(balancetransfer.FieldRevokeReason, field.TypeString)
	}
	if _u.mutation.SenderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   balancetransfer.SenderTable,
			Columns: []string{balancetransfer.SenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SenderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   balancetransfer.SenderTable,
			Columns: []string{balancetransfer.SenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReceiverCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   balancetransfer.ReceiverTable,
			Columns: []string{balancetransfer.ReceiverColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReceiverIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   balancetransfer.ReceiverTable,
			Columns: []string{balancetransfer.ReceiverColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{balancetransfer.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BalanceTransferUpdateOne is the builder for updating a single BalanceTransfer entity.
type BalanceTransferUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BalanceTransferMutation
}

// SetSenderID sets the "sender_id" field.
func (_u *BalanceTransferUpdateOne) SetSenderID(v int64) *BalanceTransferUpdateOne {
	_u.mutation.SetSenderID(v)
	return _u
}

// SetNillableSenderID sets the "sender_id" field if the given value is not nil.
func (_u *BalanceTransferUpdateOne) SetNillableSenderID(v *int64) *BalanceTransferUpdateOne {
	if v != nil {
		_u.SetSenderID(*v)
	}
	return _u
}

// SetReceiverID sets the "receiver_id" field.
func (_u *BalanceTransferUpdateOne) SetReceiverID(v int64) *BalanceTransferUpdateOne {
	_u.mutation.SetReceiverID(v)
	return _u
}

// SetNillableReceiverID sets the "receiver_id" field if the given value is not nil.
func (_u *BalanceTransferUpdateOne) SetNillableReceiverID(v *int64) *BalanceTransferUpdateOne {
	if v != nil {
		_u.SetReceiverID(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *BalanceTransferUpdateOne) SetAmount(v float64) *BalanceTransferUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *BalanceTransferUpdateOne) SetNillableAmount(v *float64) *BalanceTransferUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *BalanceTransferUpdateOne) AddAmount(v float64) *BalanceTransferUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetFee sets the "fee" field.
func (_u *BalanceTransferUpdateOne) SetFee(v float64) *BalanceTransferUpdateOne {
	_u.mutation.ResetFee()
	_u.mutation.SetFee(v)
	return _u
}

// SetNillableFee sets the "fee" field if the given value is not nil.
func (_u *BalanceTransferUpdateOne) SetNillableFee(v *float64) *BalanceTransferUpdateOne {
	if v != nil {
		_u.SetFee(*v)
	}
	return _u
}

// AddFee adds value to the "fee" field.
func (_u *BalanceTransferUpdateOne) AddFee(v float64) *BalanceTransferUpdateOne {
	_u.mutation.AddFee(v)
	return _u
}

// SetFeeRate sets the "fee_rate" field.
func (_u *BalanceTransferUpdateOne) SetFeeRate(v float64) *BalanceTransferUpdateOne {
	_u.mutation.ResetFeeRate()
	_u.mutation.SetFeeRate(v)
	return _u
}

// SetNillableFeeRate sets the "fee_rate" field if the given value is not nil.
func (_u *BalanceTransferUpdateOne) SetNillableFeeRate(v *float64) *BalanceTransferUpdateOne {
	if v != nil {
		_u.SetFeeRate(*v)
	}
	return _u
}

// AddFeeRate adds value to the "fee_rate" field.
func (_u *BalanceTransferUpdateOne) AddFeeRate(v float64) *BalanceTransferUpdateOne {
	_u.mutation.AddFeeRate(v)
	return _u
}

// SetGrossAmount sets the "gross_amount" field.
func (_u *BalanceTransferUpdateOne) SetGrossAmount(v float64) *BalanceTransferUpdateOne {
	_u.mutation.ResetGrossAmount()
	_u.mutation.SetGrossAmount(v)
	return _u
}

// SetNillableGrossAmount sets the "gross_amount" field if the given value is not nil.
func (_u *BalanceTransferUpdateOne) SetNillableGrossAmount(v *float64) *BalanceTransferUpdateOne {
	if v != nil {
		_u.SetGrossAmount(*v)
	}
	return _u
}

// AddGrossAmount adds value to the "gross_amount" field.
func (_u *BalanceTransferUpdateOne) AddGrossAmount(v float64) *BalanceTransferUpdateOne {
	_u.mutation.AddGrossAmount(v)
	return _u
}

// SetTransferType sets the "transfer_type" field.
func (_u *BalanceTransferUpdateOne) SetTransferType(v string) *BalanceTransferUpdateOne {
	_u.mutation.SetTransferType(v)
	return _u
}

// SetNillableTransferType sets the "transfer_type" field if the given value is not nil.
func (_u *BalanceTransferUpdateOne) SetNillableTransferType(v *string) *BalanceTransferUpdateOne {
	if v != nil {
		_u.SetTransferType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *BalanceTransferUpdateOne) SetStatus(v string) *BalanceTransferUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *BalanceTransferUpdateOne) SetNillableStatus(v *string) *BalanceTransferUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetMemo sets the "memo" field.
func (_u *BalanceTransferUpdateOne) SetMemo(v string) *BalanceTransferUpdateOne {
	_u.mutation.SetMemo(v)
	return _u
}

// SetNillableMemo sets the "memo" field if the given value is not nil.
func (_u *BalanceTransferUpdateOne) SetNillableMemo(v *string) *BalanceTransferUpdateOne {
	if v != nil {
		_u.SetMemo(*v)
	}
	return _u
}

// ClearMemo clears the value of the "memo" field.
func (_u *BalanceTransferUpdateOne) ClearMemo() *BalanceTransferUpdateOne {
	_u.mutation.ClearMemo()
	return _u
}

// SetRedpacketID sets the "redpacket_id" field.
func (_u *BalanceTransferUpdateOne) SetRedpacketID(v int64) *BalanceTransferUpdateOne {
	_u.mutation.ResetRedpacketID()
	_u.mutation.SetRedpacketID(v)
	return _u
}

// SetNillableRedpacketID sets the "redpacket_id" field if the given value is not nil.
func (_u *BalanceTransferUpdateOne) SetNillableRedpacketID(v *int64) *BalanceTransferUpdateOne {
	if v != nil {
		_u.SetRedpacketID(*v)
	}
	return _u
}

// AddRedpacketID adds value to the "redpacket_id" field.
func (_u *BalanceTransferUpdateOne) AddRedpacketID(v int64) *BalanceTransferUpdateOne {
	_u.mutation.AddRedpacketID(v)
	return _u
}

// ClearRedpacketID clears the value of the "redpacket_id" field.
func (_u *BalanceTransferUpdateOne) ClearRedpacketID() *BalanceTransferUpdateOne {
	_u.mutation.ClearRedpacketID()
	return _u
}

// SetFrozenAt sets the "frozen_at" field.
func (_u *BalanceTransferUpdateOne) SetFrozenAt(v time.Time) *BalanceTransferUpdateOne {
	_u.mutation.SetFrozenAt(v)
	return _u
}

// SetNillableFrozenAt sets the "frozen_at" field if the given value is not nil.
func (_u *BalanceTransferUpdateOne) SetNillableFrozenAt(v *time.Time) *BalanceTransferUpdateOne {
	if v != nil {
		_u.SetFrozenAt(*v)
	}
	return _u
}

// ClearFrozenAt clears the value of the "frozen_at" field.
func (_u *BalanceTransferUpdateOne) ClearFrozenAt() *BalanceTransferUpdateOne {
	_u.mutation.ClearFrozenAt()
	return _u
}

// SetFrozenBy sets the "frozen_by" field.
func (_u *BalanceTransferUpdateOne) SetFrozenBy(v int64) *BalanceTransferUpdateOne {
	_u.mutation.ResetFrozenBy()
	_u.mutation.SetFrozenBy(v)
	return _u
}

// SetNillableFrozenBy sets the "frozen_by" field if the given value is not nil.
func (_u *BalanceTransferUpdateOne) SetNillableFrozenBy(v *int64) *BalanceTransferUpdateOne {
	if v != nil {
		_u.SetFrozenBy(*v)
	}
	return _u
}

// AddFrozenBy adds value to the "frozen_by" field.
func (_u *BalanceTransferUpdateOne) AddFrozenBy(v int64) *BalanceTransferUpdateOne {
	_u.mutation.AddFrozenBy(v)
	return _u
}

// ClearFrozenBy clears the value of the "frozen_by" field.
func (_u *BalanceTransferUpdateOne) ClearFrozenBy() *BalanceTransferUpdateOne {
	_u.mutation.ClearFrozenBy()
	return _u
}

// SetRevokeReason sets the "revoke_reason" field.
func (_u *BalanceTransferUpdateOne) SetRevokeReason(v string) *BalanceTransferUpdateOne {
	_u.mutation.SetRevokeReason(v)
	return _u
}

// SetNillableRevokeReason sets the "revoke_reason" field if the given value is not nil.
func (_u *BalanceTransferUpdateOne) SetNillableRevokeReason(v *string) *BalanceTransferUpdateOne {
	if v != nil {
		_u.SetRevokeReason(*v)
	}
	return _u
}

// ClearRevokeReason clears the value of the "revoke_reason" field.
func (_u *BalanceTransferUpdateOne) ClearRevokeReason() *BalanceTransferUpdateOne {
	_u.mutation.ClearRevokeReason()
	return _u
}

// SetSender sets the "sender" edge to the User entity.
func (_u *BalanceTransferUpdateOne) SetSender(v *User) *BalanceTransferUpdateOne {
	return _u.SetSenderID(v.ID)
}

// SetReceiver sets the "receiver" edge to the User entity.
func (_u *BalanceTransferUpdateOne) SetReceiver(v *User) *BalanceTransferUpdateOne {
	return _u.SetReceiverID(v.ID)
}

// Mutation returns the BalanceTransferMutation object of the builder.
func (_u *BalanceTransferUpdateOne) Mutation() *BalanceTransferMutation {
	return _u.mutation
}

// ClearSender clears the "sender" edge to the User entity.
func (_u *BalanceTransferUpdateOne) ClearSender() *BalanceTransferUpdateOne {
	_u.mutation.ClearSender()
	return _u
}

// ClearReceiver clears the "receiver" edge to the User entity.
func (_u *BalanceTransferUpdateOne) ClearReceiver() *BalanceTransferUpdateOne {
	_u.mutation.ClearReceiver()
	return _u
}

// Where appends a list predicates to the BalanceTransferUpdate builder.
func (_u *BalanceTransferUpdateOne) Where(ps ...predicate.BalanceTransfer) *BalanceTransferUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BalanceTransferUpdateOne) Select(field string, fields ...string) *BalanceTransferUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BalanceTransfer entity.
func (_u *BalanceTransferUpdateOne) Save(ctx context.Context) (*BalanceTransfer, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BalanceTransferUpdateOne) SaveX(ctx context.Context) *BalanceTransfer {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BalanceTransferUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BalanceTransferUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BalanceTransferUpdateOne) check() error {
	if v, ok := _u.mutation.TransferType(); ok {
		if err := balancetransfer.TransferTypeValidator(v); err != nil {
			return &ValidationError{Name: "transfer_type", err: fmt.Errorf(`ent: validator failed for field "BalanceTransfer.transfer_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := balancetransfer.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "BalanceTransfer.status": %w`, err)}
		}
	}
	if _u.mutation.SenderCleared() && len(_u.mutation.SenderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BalanceTransfer.sender"`)
	}
	if _u.mutation.ReceiverCleared() && len(_u.mutation.ReceiverIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BalanceTransfer.receiver"`)
	}
	return nil
}

func (_u *BalanceTransferUpdateOne) sqlSave(ctx context.Context) (_node *BalanceTransfer, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(balancetransfer.Table, balancetransfer.Columns, sqlgraph.NewFieldSpec(balancetransfer.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BalanceTransfer.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, balancetransfer.FieldID)
		for _, f := range fields {
			if !balancetransfer.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != balancetransfer.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(balancetransfer.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(balancetransfer.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Fee(); ok {
		_spec.SetField(balancetransfer.FieldFee, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFee(); ok {
		_spec.AddField(balancetransfer.FieldFee, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FeeRate(); ok {
		_spec.SetField(balancetransfer.FieldFeeRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFeeRate(); ok {
		_spec.AddField(balancetransfer.FieldFeeRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.GrossAmount(); ok {
		_spec.SetField(balancetransfer.FieldGrossAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedGrossAmount(); ok {
		_spec.AddField(balancetransfer.FieldGrossAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TransferType(); ok {
		_spec.SetField(balancetransfer.FieldTransferType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(balancetransfer.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Memo(); ok {
		_spec.SetField(balancetransfer.FieldMemo, field.TypeString, value)
	}
	if _u.mutation.MemoCleared() {
		_spec.ClearField(balancetransfer.FieldMemo, field.TypeString)
	}
	if value, ok := _u.mutation.RedpacketID(); ok {
		_spec.SetField(balancetransfer.FieldRedpacketID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRedpacketID(); ok {
		_spec.AddField(balancetransfer.FieldRedpacketID, field.TypeInt64, value)
	}
	if _u.mutation.RedpacketIDCleared() {
		_spec.ClearField(balancetransfer.FieldRedpacketID, field.TypeInt64)
	}
	if value, ok := _u.mutation.FrozenAt(); ok {
		_spec.SetField(balancetransfer.FieldFrozenAt, field.TypeTime, value)
	}
	if _u.mutation.FrozenAtCleared() {
		_spec.ClearField(balancetransfer.FieldFrozenAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FrozenBy(); ok {
		_spec.SetField(balancetransfer.FieldFrozenBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFrozenBy(); ok {
		_spec.AddField(balancetransfer.FieldFrozenBy, field.TypeInt64, value)
	}
	if _u.mutation.FrozenByCleared() {
		_spec.ClearField(balancetransfer.FieldFrozenBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.RevokeReason(); ok {
		_spec.SetField(balancetransfer.FieldRevokeReason, field.TypeString, value)
	}
	if _u.mutation.RevokeReasonCleared() {
		_spec.ClearField(balancetransfer.FieldRevokeReason, field.TypeString)
	}
	if _u.mutation.SenderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   balancetransfer.SenderTable,
			Columns: []string{balancetransfer.SenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SenderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   balancetransfer.SenderTable,
			Columns: []string{balancetransfer.SenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReceiverCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   balancetransfer.ReceiverTable,
			Columns: []string{balancetransfer.ReceiverColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReceiverIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   balancetransfer.ReceiverTable,
			Columns: []string{balancetransfer.ReceiverColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &BalanceTransfer{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{balancetransfer.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
