// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/balanceredpacket"
	"github.com/Wei-Shaw/sub2api/ent/balanceredpacketclaim"
)

// BalanceRedPacketClaim is the model entity for the BalanceRedPacketClaim schema.
type BalanceRedPacketClaim struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// RedpacketID holds the value of the "redpacket_id" field.
	RedpacketID int64 `json:"redpacket_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount float64 `json:"amount,omitempty"`
	// TransferID holds the value of the "transfer_id" field.
	TransferID *int64 `json:"transfer_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BalanceRedPacketClaimQuery when eager-loading is set.
	Edges        BalanceRedPacketClaimEdges `json:"edges"`
	selectValues sql.SelectValues
}

// BalanceRedPacketClaimEdges holds the relations/edges for other nodes in the graph.
type BalanceRedPacketClaimEdges struct {
	// Redpacket holds the value of the redpacket edge.
	Redpacket *BalanceRedPacket `json:"redpacket,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// RedpacketOrErr returns the Redpacket value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BalanceRedPacketClaimEdges) RedpacketOrErr() (*BalanceRedPacket, error) {
	if e.Redpacket != nil {
		return e.Redpacket, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: balanceredpacket.Label}
	}
	return nil, &NotLoadedError{edge: "redpacket"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BalanceRedPacketClaim) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case balanceredpacketclaim.FieldAmount:
			values[i] = new(sql.NullFloat64)
		case balanceredpacketclaim.FieldID, balanceredpacketclaim.FieldRedpacketID, balanceredpacketclaim.FieldUserID, balanceredpacketclaim.FieldTransferID:
			values[i] = new(sql.NullInt64)
		case balanceredpacketclaim.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BalanceRedPacketClaim fields.
func (_m *BalanceRedPacketClaim) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case balanceredpacketclaim.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case balanceredpacketclaim.FieldRedpacketID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field redpacket_id", values[i])
			} else if value.Valid {
				_m.RedpacketID = value.Int64
			}
		case balanceredpacketclaim.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case balanceredpacketclaim.FieldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.Float64
			}
		case balanceredpacketclaim.FieldTransferID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field transfer_id", values[i])
			} else if value.Valid {
				_m.TransferID = new(int64)
				*_m.TransferID = value.Int64
			}
		case balanceredpacketclaim.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BalanceRedPacketClaim.
// This includes values selected through modifiers, order, etc.
func (_m *BalanceRedPacketClaim) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRedpacket queries the "redpacket" edge of the BalanceRedPacketClaim entity.
func (_m *BalanceRedPacketClaim) QueryRedpacket() *BalanceRedPacketQuery {
	return NewBalanceRedPacketClaimClient(_m.config).QueryRedpacket(_m)
}

// Update returns a builder for updating this BalanceRedPacketClaim.
// Note that you need to call BalanceRedPacketClaim.Unwrap() before calling this method if this BalanceRedPacketClaim
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BalanceRedPacketClaim) Update() *BalanceRedPacketClaimUpdateOne {
	return NewBalanceRedPacketClaimClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BalanceRedPacketClaim entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BalanceRedPacketClaim) Unwrap() *BalanceRedPacketClaim {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BalanceRedPacketClaim is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BalanceRedPacketClaim) String() string {
	var builder strings.Builder
	builder.WriteString("BalanceRedPacketClaim(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("redpacket_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RedpacketID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	if v := _m.TransferID; v != nil {
		builder.WriteString("transfer_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// BalanceRedPacketClaims is a parsable slice of BalanceRedPacketClaim.
type BalanceRedPacketClaims []*BalanceRedPacketClaim
