// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/balanceredpacketclaim"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// BalanceRedPacketClaimDelete is the builder for deleting a BalanceRedPacketClaim entity.
type BalanceRedPacketClaimDelete struct {
	config
	hooks    []Hook
	mutation *BalanceRedPacketClaimMutation
}

// Where appends a list predicates to the BalanceRedPacketClaimDelete builder.
func (_d *BalanceRedPacketClaimDelete) Where(ps ...predicate.BalanceRedPacketClaim) *BalanceRedPacketClaimDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *BalanceRedPacketClaimDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BalanceRedPacketClaimDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *BalanceRedPacketClaimDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(balanceredpacketclaim.Table, sqlgraph.NewFieldSpec(balanceredpacketclaim.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// BalanceRedPacketClaimDeleteOne is the builder for deleting a single BalanceRedPacketClaim entity.
type BalanceRedPacketClaimDeleteOne struct {
	_d *BalanceRedPacketClaimDelete
}

// Where appends a list predicates to the BalanceRedPacketClaimDelete builder.
func (_d *BalanceRedPacketClaimDeleteOne) Where(ps ...predicate.BalanceRedPacketClaim) *BalanceRedPacketClaimDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *BalanceRedPacketClaimDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{balanceredpacketclaim.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BalanceRedPacketClaimDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
