// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/financialreconciliationissue"
	"github.com/Wei-Shaw/sub2api/ent/financialreconciliationrun"
	"github.com/Wei-Shaw/sub2api/ent/ledgeraccount"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// FinancialReconciliationIssueQuery is the builder for querying FinancialReconciliationIssue entities.
type FinancialReconciliationIssueQuery struct {
	config
	ctx                   *QueryContext
	order                 []financialreconciliationissue.OrderOption
	inters                []Interceptor
	predicates            []predicate.FinancialReconciliationIssue
	withReconciliationRun *FinancialReconciliationRunQuery
	withLedgerAccount     *LedgerAccountQuery
	modifiers             []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FinancialReconciliationIssueQuery builder.
func (_q *FinancialReconciliationIssueQuery) Where(ps ...predicate.FinancialReconciliationIssue) *FinancialReconciliationIssueQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *FinancialReconciliationIssueQuery) Limit(limit int) *FinancialReconciliationIssueQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *FinancialReconciliationIssueQuery) Offset(offset int) *FinancialReconciliationIssueQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *FinancialReconciliationIssueQuery) Unique(unique bool) *FinancialReconciliationIssueQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *FinancialReconciliationIssueQuery) Order(o ...financialreconciliationissue.OrderOption) *FinancialReconciliationIssueQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryReconciliationRun chains the current query on the "reconciliation_run" edge.
func (_q *FinancialReconciliationIssueQuery) QueryReconciliationRun() *FinancialReconciliationRunQuery {
	query := (&FinancialReconciliationRunClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(financialreconciliationissue.Table, financialreconciliationissue.FieldID, selector),
			sqlgraph.To(financialreconciliationrun.Table, financialreconciliationrun.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, financialreconciliationissue.ReconciliationRunTable, financialreconciliationissue.ReconciliationRunColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryLedgerAccount chains the current query on the "ledger_account" edge.
func (_q *FinancialReconciliationIssueQuery) QueryLedgerAccount() *LedgerAccountQuery {
	query := (&LedgerAccountClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(financialreconciliationissue.Table, financialreconciliationissue.FieldID, selector),
			sqlgraph.To(ledgeraccount.Table, ledgeraccount.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, financialreconciliationissue.LedgerAccountTable, financialreconciliationissue.LedgerAccountColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first FinancialReconciliationIssue entity from the query.
// Returns a *NotFoundError when no FinancialReconciliationIssue was found.
func (_q *FinancialReconciliationIssueQuery) First(ctx context.Context) (*FinancialReconciliationIssue, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{financialreconciliationissue.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *FinancialReconciliationIssueQuery) FirstX(ctx context.Context) *FinancialReconciliationIssue {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first FinancialReconciliationIssue ID from the query.
// Returns a *NotFoundError when no FinancialReconciliationIssue ID was found.
func (_q *FinancialReconciliationIssueQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{financialreconciliationissue.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *FinancialReconciliationIssueQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single FinancialReconciliationIssue entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one FinancialReconciliationIssue entity is found.
// Returns a *NotFoundError when no FinancialReconciliationIssue entities are found.
func (_q *FinancialReconciliationIssueQuery) Only(ctx context.Context) (*FinancialReconciliationIssue, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{financialreconciliationissue.Label}
	default:
		return nil, &NotSingularError{financialreconciliationissue.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *FinancialReconciliationIssueQuery) OnlyX(ctx context.Context) *FinancialReconciliationIssue {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only FinancialReconciliationIssue ID in the query.
// Returns a *NotSingularError when more than one FinancialReconciliationIssue ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *FinancialReconciliationIssueQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{financialreconciliationissue.Label}
	default:
		err = &NotSingularError{financialreconciliationissue.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *FinancialReconciliationIssueQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of FinancialReconciliationIssues.
func (_q *FinancialReconciliationIssueQuery) All(ctx context.Context) ([]*FinancialReconciliationIssue, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*FinancialReconciliationIssue, *FinancialReconciliationIssueQuery]()
	return withInterceptors[[]*FinancialReconciliationIssue](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *FinancialReconciliationIssueQuery) AllX(ctx context.Context) []*FinancialReconciliationIssue {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of FinancialReconciliationIssue IDs.
func (_q *FinancialReconciliationIssueQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(financialreconciliationissue.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *FinancialReconciliationIssueQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *FinancialReconciliationIssueQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*FinancialReconciliationIssueQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *FinancialReconciliationIssueQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *FinancialReconciliationIssueQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *FinancialReconciliationIssueQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FinancialReconciliationIssueQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *FinancialReconciliationIssueQuery) Clone() *FinancialReconciliationIssueQuery {
	if _q == nil {
		return nil
	}
	return &FinancialReconciliationIssueQuery{
		config:                _q.config,
		ctx:                   _q.ctx.Clone(),
		order:                 append([]financialreconciliationissue.OrderOption{}, _q.order...),
		inters:                append([]Interceptor{}, _q.inters...),
		predicates:            append([]predicate.FinancialReconciliationIssue{}, _q.predicates...),
		withReconciliationRun: _q.withReconciliationRun.Clone(),
		withLedgerAccount:     _q.withLedgerAccount.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithReconciliationRun tells the query-builder to eager-load the nodes that are connected to
// the "reconciliation_run" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *FinancialReconciliationIssueQuery) WithReconciliationRun(opts ...func(*FinancialReconciliationRunQuery)) *FinancialReconciliationIssueQuery {
	query := (&FinancialReconciliationRunClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withReconciliationRun = query
	return _q
}

// WithLedgerAccount tells the query-builder to eager-load the nodes that are connected to
// the "ledger_account" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *FinancialReconciliationIssueQuery) WithLedgerAccount(opts ...func(*LedgerAccountQuery)) *FinancialReconciliationIssueQuery {
	query := (&LedgerAccountClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withLedgerAccount = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		IssueID uuid.UUID `json:"issue_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.FinancialReconciliationIssue.Query().
//		GroupBy(financialreconciliationissue.FieldIssueID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *FinancialReconciliationIssueQuery) GroupBy(field string, fields ...string) *FinancialReconciliationIssueGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &FinancialReconciliationIssueGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = financialreconciliationissue.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		IssueID uuid.UUID `json:"issue_id,omitempty"`
//	}
//
//	client.FinancialReconciliationIssue.Query().
//		Select(financialreconciliationissue.FieldIssueID).
//		Scan(ctx, &v)
func (_q *FinancialReconciliationIssueQuery) Select(fields ...string) *FinancialReconciliationIssueSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &FinancialReconciliationIssueSelect{FinancialReconciliationIssueQuery: _q}
	sbuild.label = financialreconciliationissue.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a FinancialReconciliationIssueSelect configured with the given aggregations.
func (_q *FinancialReconciliationIssueQuery) Aggregate(fns ...AggregateFunc) *FinancialReconciliationIssueSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *FinancialReconciliationIssueQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !financialreconciliationissue.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *FinancialReconciliationIssueQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*FinancialReconciliationIssue, error) {
	var (
		nodes       = []*FinancialReconciliationIssue{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withReconciliationRun != nil,
			_q.withLedgerAccount != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*FinancialReconciliationIssue).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &FinancialReconciliationIssue{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withReconciliationRun; query != nil {
		if err := _q.loadReconciliationRun(ctx, query, nodes, nil,
			func(n *FinancialReconciliationIssue, e *FinancialReconciliationRun) { n.Edges.ReconciliationRun = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withLedgerAccount; query != nil {
		if err := _q.loadLedgerAccount(ctx, query, nodes, nil,
			func(n *FinancialReconciliationIssue, e *LedgerAccount) { n.Edges.LedgerAccount = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *FinancialReconciliationIssueQuery) loadReconciliationRun(ctx context.Context, query *FinancialReconciliationRunQuery, nodes []*FinancialReconciliationIssue, init func(*FinancialReconciliationIssue), assign func(*FinancialReconciliationIssue, *FinancialReconciliationRun)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*FinancialReconciliationIssue)
	for i := range nodes {
		fk := nodes[i].ReconciliationID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(financialreconciliationrun.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "reconciliation_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *FinancialReconciliationIssueQuery) loadLedgerAccount(ctx context.Context, query *LedgerAccountQuery, nodes []*FinancialReconciliationIssue, init func(*FinancialReconciliationIssue), assign func(*FinancialReconciliationIssue, *LedgerAccount)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*FinancialReconciliationIssue)
	for i := range nodes {
		if nodes[i].LedgerAccountID == nil {
			continue
		}
		fk := *nodes[i].LedgerAccountID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(ledgeraccount.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "ledger_account_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *FinancialReconciliationIssueQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *FinancialReconciliationIssueQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(financialreconciliationissue.Table, financialreconciliationissue.Columns, sqlgraph.NewFieldSpec(financialreconciliationissue.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, financialreconciliationissue.FieldID)
		for i := range fields {
			if fields[i] != financialreconciliationissue.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withReconciliationRun != nil {
			_spec.Node.AddColumnOnce(financialreconciliationissue.FieldReconciliationID)
		}
		if _q.withLedgerAccount != nil {
			_spec.Node.AddColumnOnce(financialreconciliationissue.FieldLedgerAccountID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *FinancialReconciliationIssueQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(financialreconciliationissue.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = financialreconciliationissue.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *FinancialReconciliationIssueQuery) ForUpdate(opts ...sql.LockOption) *FinancialReconciliationIssueQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *FinancialReconciliationIssueQuery) ForShare(opts ...sql.LockOption) *FinancialReconciliationIssueQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// FinancialReconciliationIssueGroupBy is the group-by builder for FinancialReconciliationIssue entities.
type FinancialReconciliationIssueGroupBy struct {
	selector
	build *FinancialReconciliationIssueQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *FinancialReconciliationIssueGroupBy) Aggregate(fns ...AggregateFunc) *FinancialReconciliationIssueGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *FinancialReconciliationIssueGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FinancialReconciliationIssueQuery, *FinancialReconciliationIssueGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *FinancialReconciliationIssueGroupBy) sqlScan(ctx context.Context, root *FinancialReconciliationIssueQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// FinancialReconciliationIssueSelect is the builder for selecting fields of FinancialReconciliationIssue entities.
type FinancialReconciliationIssueSelect struct {
	*FinancialReconciliationIssueQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *FinancialReconciliationIssueSelect) Aggregate(fns ...AggregateFunc) *FinancialReconciliationIssueSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *FinancialReconciliationIssueSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FinancialReconciliationIssueQuery, *FinancialReconciliationIssueSelect](ctx, _s.FinancialReconciliationIssueQuery, _s, _s.inters, v)
}

func (_s *FinancialReconciliationIssueSelect) sqlScan(ctx context.Context, root *FinancialReconciliationIssueQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
