// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/financialreconciliationissue"
	"github.com/Wei-Shaw/sub2api/ent/financialreconciliationrun"
	"github.com/google/uuid"
)

// FinancialReconciliationRunCreate is the builder for creating a FinancialReconciliationRun entity.
type FinancialReconciliationRunCreate struct {
	config
	mutation *FinancialReconciliationRunMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetRunID sets the "run_id" field.
func (_c *FinancialReconciliationRunCreate) SetRunID(v uuid.UUID) *FinancialReconciliationRunCreate {
	_c.mutation.SetRunID(v)
	return _c
}

// SetNillableRunID sets the "run_id" field if the given value is not nil.
func (_c *FinancialReconciliationRunCreate) SetNillableRunID(v *uuid.UUID) *FinancialReconciliationRunCreate {
	if v != nil {
		_c.SetRunID(*v)
	}
	return _c
}

// SetRunDate sets the "run_date" field.
func (_c *FinancialReconciliationRunCreate) SetRunDate(v time.Time) *FinancialReconciliationRunCreate {
	_c.mutation.SetRunDate(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *FinancialReconciliationRunCreate) SetStatus(v string) *FinancialReconciliationRunCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *FinancialReconciliationRunCreate) SetNillableStatus(v *string) *FinancialReconciliationRunCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCheckedTransactions sets the "checked_transactions" field.
func (_c *FinancialReconciliationRunCreate) SetCheckedTransactions(v int64) *FinancialReconciliationRunCreate {
	_c.mutation.SetCheckedTransactions(v)
	return _c
}

// SetNillableCheckedTransactions sets the "checked_transactions" field if the given value is not nil.
func (_c *FinancialReconciliationRunCreate) SetNillableCheckedTransactions(v *int64) *FinancialReconciliationRunCreate {
	if v != nil {
		_c.SetCheckedTransactions(*v)
	}
	return _c
}

// SetCheckedLedgerEntries sets the "checked_ledger_entries" field.
func (_c *FinancialReconciliationRunCreate) SetCheckedLedgerEntries(v int64) *FinancialReconciliationRunCreate {
	_c.mutation.SetCheckedLedgerEntries(v)
	return _c
}

// SetNillableCheckedLedgerEntries sets the "checked_ledger_entries" field if the given value is not nil.
func (_c *FinancialReconciliationRunCreate) SetNillableCheckedLedgerEntries(v *int64) *FinancialReconciliationRunCreate {
	if v != nil {
		_c.SetCheckedLedgerEntries(*v)
	}
	return _c
}

// SetMismatchCount sets the "mismatch_count" field.
func (_c *FinancialReconciliationRunCreate) SetMismatchCount(v int64) *FinancialReconciliationRunCreate {
	_c.mutation.SetMismatchCount(v)
	return _c
}

// SetNillableMismatchCount sets the "mismatch_count" field if the given value is not nil.
func (_c *FinancialReconciliationRunCreate) SetNillableMismatchCount(v *int64) *FinancialReconciliationRunCreate {
	if v != nil {
		_c.SetMismatchCount(*v)
	}
	return _c
}

// SetSummary sets the "summary" field.
func (_c *FinancialReconciliationRunCreate) SetSummary(v map[string]interface{}) *FinancialReconciliationRunCreate {
	_c.mutation.SetSummary(v)
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *FinancialReconciliationRunCreate) SetStartedAt(v time.Time) *FinancialReconciliationRunCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *FinancialReconciliationRunCreate) SetNillableStartedAt(v *time.Time) *FinancialReconciliationRunCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetFinishedAt sets the "finished_at" field.
func (_c *FinancialReconciliationRunCreate) SetFinishedAt(v time.Time) *FinancialReconciliationRunCreate {
	_c.mutation.SetFinishedAt(v)
	return _c
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_c *FinancialReconciliationRunCreate) SetNillableFinishedAt(v *time.Time) *FinancialReconciliationRunCreate {
	if v != nil {
		_c.SetFinishedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *FinancialReconciliationRunCreate) SetCreatedAt(v time.Time) *FinancialReconciliationRunCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *FinancialReconciliationRunCreate) SetNillableCreatedAt(v *time.Time) *FinancialReconciliationRunCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// AddIssueIDs adds the "issues" edge to the FinancialReconciliationIssue entity by IDs.
func (_c *FinancialReconciliationRunCreate) AddIssueIDs(ids ...int64) *FinancialReconciliationRunCreate {
	_c.mutation.AddIssueIDs(ids...)
	return _c
}

// AddIssues adds the "issues" edges to the FinancialReconciliationIssue entity.
func (_c *FinancialReconciliationRunCreate) AddIssues(v ...*FinancialReconciliationIssue) *FinancialReconciliationRunCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddIssueIDs(ids...)
}

// Mutation returns the FinancialReconciliationRunMutation object of the builder.
func (_c *FinancialReconciliationRunCreate) Mutation() *FinancialReconciliationRunMutation {
	return _c.mutation
}

// Save creates the FinancialReconciliationRun in the database.
func (_c *FinancialReconciliationRunCreate) Save(ctx context.Context) (*FinancialReconciliationRun, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FinancialReconciliationRunCreate) SaveX(ctx context.Context) *FinancialReconciliationRun {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FinancialReconciliationRunCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FinancialReconciliationRunCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *FinancialReconciliationRunCreate) defaults() {
	if _, ok := _c.mutation.RunID(); !ok {
		v := financialreconciliationrun.DefaultRunID()
		_c.mutation.SetRunID(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := financialreconciliationrun.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CheckedTransactions(); !ok {
		v := financialreconciliationrun.DefaultCheckedTransactions
		_c.mutation.SetCheckedTransactions(v)
	}
	if _, ok := _c.mutation.CheckedLedgerEntries(); !ok {
		v := financialreconciliationrun.DefaultCheckedLedgerEntries
		_c.mutation.SetCheckedLedgerEntries(v)
	}
	if _, ok := _c.mutation.MismatchCount(); !ok {
		v := financialreconciliationrun.DefaultMismatchCount
		_c.mutation.SetMismatchCount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := financialreconciliationrun.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *FinancialReconciliationRunCreate) check() error {
	if _, ok := _c.mutation.RunID(); !ok {
		return &ValidationError{Name: "run_id", err: errors.New(`ent: missing required field "FinancialReconciliationRun.run_id"`)}
	}
	if _, ok := _c.mutation.RunDate(); !ok {
		return &ValidationError{Name: "run_date", err: errors.New(`ent: missing required field "FinancialReconciliationRun.run_date"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "FinancialReconciliationRun.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := financialreconciliationrun.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "FinancialReconciliationRun.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CheckedTransactions(); !ok {
		return &ValidationError{Name: "checked_transactions", err: errors.New(`ent: missing required field "FinancialReconciliationRun.checked_transactions"`)}
	}
	if _, ok := _c.mutation.CheckedLedgerEntries(); !ok {
		return &ValidationError{Name: "checked_ledger_entries", err: errors.New(`ent: missing required field "FinancialReconciliationRun.checked_ledger_entries"`)}
	}
	if _, ok := _c.mutation.MismatchCount(); !ok {
		return &ValidationError{Name: "mismatch_count", err: errors.New(`ent: missing required field "FinancialReconciliationRun.mismatch_count"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "FinancialReconciliationRun.created_at"`)}
	}
	return nil
}

func (_c *FinancialReconciliationRunCreate) sqlSave(ctx context.Context) (*FinancialReconciliationRun, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FinancialReconciliationRunCreate) createSpec() (*FinancialReconciliationRun, *sqlgraph.CreateSpec) {
	var (
		_node = &FinancialReconciliationRun{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(financialreconciliationrun.Table, sqlgraph.NewFieldSpec(financialreconciliationrun.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.RunID(); ok {
		_spec.SetField(financialreconciliationrun.FieldRunID, field.TypeUUID, value)
		_node.RunID = value
	}
	if value, ok := _c.mutation.RunDate(); ok {
		_spec.SetField(financialreconciliationrun.FieldRunDate, field.TypeTime, value)
		_node.RunDate = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(financialreconciliationrun.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CheckedTransactions(); ok {
		_spec.SetField(financialreconciliationrun.FieldCheckedTransactions, field.TypeInt64, value)
		_node.CheckedTransactions = value
	}
	if value, ok := _c.mutation.CheckedLedgerEntries(); ok {
		_spec.SetField(financialreconciliationrun.FieldCheckedLedgerEntries, field.TypeInt64, value)
		_node.CheckedLedgerEntries = value
	}
	if value, ok := _c.mutation.MismatchCount(); ok {
		_spec.SetField(financialreconciliationrun.FieldMismatchCount, field.TypeInt64, value)
		_node.MismatchCount = value
	}
	if value, ok := _c.mutation.Summary(); ok {
		_spec.SetField(financialreconciliationrun.FieldSummary, field.TypeJSON, value)
		_node.Summary = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(financialreconciliationrun.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = &value
	}
	if value, ok := _c.mutation.FinishedAt(); ok {
		_spec.SetField(financialreconciliationrun.FieldFinishedAt, field.TypeTime, value)
		_node.FinishedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(financialreconciliationrun.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.IssuesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   financialreconciliationrun.IssuesTable,
			Columns: []string{financialreconciliationrun.IssuesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(financialreconciliationissue.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.FinancialReconciliationRun.Create().
//		SetRunID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FinancialReconciliationRunUpsert) {
//			SetRunID(v+v).
//		}).
//		Exec(ctx)
func (_c *FinancialReconciliationRunCreate) OnConflict(opts ...sql.ConflictOption) *FinancialReconciliationRunUpsertOne {
	_c.conflict = opts
	return &FinancialReconciliationRunUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.FinancialReconciliationRun.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *FinancialReconciliationRunCreate) OnConflictColumns(columns ...string) *FinancialReconciliationRunUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &FinancialReconciliationRunUpsertOne{
		create: _c,
	}
}

type (
	// FinancialReconciliationRunUpsertOne is the builder for "upsert"-ing
	//  one FinancialReconciliationRun node.
	FinancialReconciliationRunUpsertOne struct {
		create *FinancialReconciliationRunCreate
	}

	// FinancialReconciliationRunUpsert is the "OnConflict" setter.
	FinancialReconciliationRunUpsert struct {
		*sql.UpdateSet
	}
)

// SetRunID sets the "run_id" field.
func (u *FinancialReconciliationRunUpsert) SetRunID(v uuid.UUID) *FinancialReconciliationRunUpsert {
	u.Set(financialreconciliationrun.FieldRunID, v)
	return u
}

// UpdateRunID sets the "run_id" field to the value that was provided on create.
func (u *FinancialReconciliationRunUpsert) UpdateRunID() *FinancialReconciliationRunUpsert {
	u.SetExcluded(financialreconciliationrun.FieldRunID)
	return u
}

// SetRunDate sets the "run_date" field.
func (u *FinancialReconciliationRunUpsert) SetRunDate(v time.Time) *FinancialReconciliationRunUpsert {
	u.Set(financialreconciliationrun.FieldRunDate, v)
	return u
}

// UpdateRunDate sets the "run_date" field to the value that was provided on create.
func (u *FinancialReconciliationRunUpsert) UpdateRunDate() *FinancialReconciliationRunUpsert {
	u.SetExcluded(financialreconciliationrun.FieldRunDate)
	return u
}

// SetStatus sets the "status" field.
func (u *FinancialReconciliationRunUpsert) SetStatus(v string) *FinancialReconciliationRunUpsert {
	u.Set(financialreconciliationrun.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *FinancialReconciliationRunUpsert) UpdateStatus() *FinancialReconciliationRunUpsert {
	u.SetExcluded(financialreconciliationrun.FieldStatus)
	return u
}

// SetCheckedTransactions sets the "checked_transactions" field.
func (u *FinancialReconciliationRunUpsert) SetCheckedTransactions(v int64) *FinancialReconciliationRunUpsert {
	u.Set(financialreconciliationrun.FieldCheckedTransactions, v)
	return u
}

// UpdateCheckedTransactions sets the "checked_transactions" field to the value that was provided on create.
func (u *FinancialReconciliationRunUpsert) UpdateCheckedTransactions() *FinancialReconciliationRunUpsert {
	u.SetExcluded(financialreconciliationrun.FieldCheckedTransactions)
	return u
}

// AddCheckedTransactions adds v to the "checked_transactions" field.
func (u *FinancialReconciliationRunUpsert) AddCheckedTransactions(v int64) *FinancialReconciliationRunUpsert {
	u.Add(financialreconciliationrun.FieldCheckedTransactions, v)
	return u
}

// SetCheckedLedgerEntries sets the "checked_ledger_entries" field.
func (u *FinancialReconciliationRunUpsert) SetCheckedLedgerEntries(v int64) *FinancialReconciliationRunUpsert {
	u.Set(financialreconciliationrun.FieldCheckedLedgerEntries, v)
	return u
}

// UpdateCheckedLedgerEntries sets the "checked_ledger_entries" field to the value that was provided on create.
func (u *FinancialReconciliationRunUpsert) UpdateCheckedLedgerEntries() *FinancialReconciliationRunUpsert {
	u.SetExcluded(financialreconciliationrun.FieldCheckedLedgerEntries)
	return u
}

// AddCheckedLedgerEntries adds v to the "checked_ledger_entries" field.
func (u *FinancialReconciliationRunUpsert) AddCheckedLedgerEntries(v int64) *FinancialReconciliationRunUpsert {
	u.Add(financialreconciliationrun.FieldCheckedLedgerEntries, v)
	return u
}

// SetMismatchCount sets the "mismatch_count" field.
func (u *FinancialReconciliationRunUpsert) SetMismatchCount(v int64) *FinancialReconciliationRunUpsert {
	u.Set(financialreconciliationrun.FieldMismatchCount, v)
	return u
}

// UpdateMismatchCount sets the "mismatch_count" field to the value that was provided on create.
func (u *FinancialReconciliationRunUpsert) UpdateMismatchCount() *FinancialReconciliationRunUpsert {
	u.SetExcluded(financialreconciliationrun.FieldMismatchCount)
	return u
}

// AddMismatchCount adds v to the "mismatch_count" field.
func (u *FinancialReconciliationRunUpsert) AddMismatchCount(v int64) *FinancialReconciliationRunUpsert {
	u.Add(financialreconciliationrun.FieldMismatchCount, v)
	return u
}

// SetSummary sets the "summary" field.
func (u *FinancialReconciliationRunUpsert) SetSummary(v map[string]interface{}) *FinancialReconciliationRunUpsert {
	u.Set(financialreconciliationrun.FieldSummary, v)
	return u
}

// UpdateSummary sets the "summary" field to the value that was provided on create.
func (u *FinancialReconciliationRunUpsert) UpdateSummary() *FinancialReconciliationRunUpsert {
	u.SetExcluded(financialreconciliationrun.FieldSummary)
	return u
}

// ClearSummary clears the value of the "summary" field.
func (u *FinancialReconciliationRunUpsert) ClearSummary() *FinancialReconciliationRunUpsert {
	u.SetNull(financialreconciliationrun.FieldSummary)
	return u
}

// SetStartedAt sets the "started_at" field.
func (u *FinancialReconciliationRunUpsert) SetStartedAt(v time.Time) *FinancialReconciliationRunUpsert {
	u.Set(financialreconciliationrun.FieldStartedAt, v)
	return u
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *FinancialReconciliationRunUpsert) UpdateStartedAt() *FinancialReconciliationRunUpsert {
	u.SetExcluded(financialreconciliationrun.FieldStartedAt)
	return u
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *FinancialReconciliationRunUpsert) ClearStartedAt() *FinancialReconciliationRunUpsert {
	u.SetNull(financialreconciliationrun.FieldStartedAt)
	return u
}

// SetFinishedAt sets the "finished_at" field.
func (u *FinancialReconciliationRunUpsert) SetFinishedAt(v time.Time) *FinancialReconciliationRunUpsert {
	u.Set(financialreconciliationrun.FieldFinishedAt, v)
	return u
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *FinancialReconciliationRunUpsert) UpdateFinishedAt() *FinancialReconciliationRunUpsert {
	u.SetExcluded(financialreconciliationrun.FieldFinishedAt)
	return u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *FinancialReconciliationRunUpsert) ClearFinishedAt() *FinancialReconciliationRunUpsert {
	u.SetNull(financialreconciliationrun.FieldFinishedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.FinancialReconciliationRun.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *FinancialReconciliationRunUpsertOne) UpdateNewValues() *FinancialReconciliationRunUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(financialreconciliationrun.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.FinancialReconciliationRun.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *FinancialReconciliationRunUpsertOne) Ignore() *FinancialReconciliationRunUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FinancialReconciliationRunUpsertOne) DoNothing() *FinancialReconciliationRunUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FinancialReconciliationRunCreate.OnConflict
// documentation for more info.
func (u *FinancialReconciliationRunUpsertOne) Update(set func(*FinancialReconciliationRunUpsert)) *FinancialReconciliationRunUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FinancialReconciliationRunUpsert{UpdateSet: update})
	}))
	return u
}

// SetRunID sets the "run_id" field.
func (u *FinancialReconciliationRunUpsertOne) SetRunID(v uuid.UUID) *FinancialReconciliationRunUpsertOne {
	return u.Update(func(s *FinancialReconciliationRunUpsert) {
		s.SetRunID(v)
	})
}

// UpdateRunID sets the "run_id" field to the value that was provided on create.
func (u *FinancialReconciliationRunUpsertOne) UpdateRunID() *FinancialReconciliationRunUpsertOne {
	return u.Update(func(s *FinancialReconciliationRunUpsert) {
		s.UpdateRunID()
	})
}

// SetRunDate sets the "run_date" field.
func (u *FinancialReconciliationRunUpsertOne) SetRunDate(v time.Time) *FinancialReconciliationRunUpsertOne {
	return u.Update(func(s *FinancialReconciliationRunUpsert) {
		s.SetRunDate(v)
	})
}

// UpdateRunDate sets the "run_date" field to the value that was provided on create.
func (u *FinancialReconciliationRunUpsertOne) UpdateRunDate() *FinancialReconciliationRunUpsertOne {
	return u.Update(func(s *FinancialReconciliationRunUpsert) {
		s.UpdateRunDate()
	})
}

// SetStatus sets the "status" field.
func (u *FinancialReconciliationRunUpsertOne) SetStatus(v string) *FinancialReconciliationRunUpsertOne {
	return u.Update(func(s *FinancialReconciliationRunUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *FinancialReconciliationRunUpsertOne) UpdateStatus() *FinancialReconciliationRunUpsertOne {
	return u.Update(func(s *FinancialReconciliationRunUpsert) {
		s.UpdateStatus()
	})
}

// SetCheckedTransactions sets the "checked_transactions" field.
func (u *FinancialReconciliationRunUpsertOne) SetCheckedTransactions(v int64) *FinancialReconciliationRunUpsertOne {
	return u.Update(func(s *FinancialReconciliationRunUpsert) {
		s.SetCheckedTransactions(v)
	})
}

// AddCheckedTransactions adds v to the "checked_transactions" field.
func (u *FinancialReconciliationRunUpsertOne) AddCheckedTransactions(v int64) *FinancialReconciliationRunUpsertOne {
	return u.Update(func(s *FinancialReconciliationRunUpsert) {
		s.AddCheckedTransactions(v)
	})
}

// UpdateCheckedTransactions sets the "checked_transactions" field to the value that was provided on create.
func (u *FinancialReconciliationRunUpsertOne) UpdateCheckedTransactions() *FinancialReconciliationRunUpsertOne {
	return u.Update(func(s *FinancialReconciliationRunUpsert) {
		s.UpdateCheckedTransactions()
	})
}

// SetCheckedLedgerEntries sets the "checked_ledger_entries" field.
func (u *FinancialReconciliationRunUpsertOne) SetCheckedLedgerEntries(v int64) *FinancialReconciliationRunUpsertOne {
	return u.Update(func(s *FinancialReconciliationRunUpsert) {
		s.SetCheckedLedgerEntries(v)
	})
}

// AddCheckedLedgerEntries adds v to the "checked_ledger_entries" field.
func (u *FinancialReconciliationRunUpsertOne) AddCheckedLedgerEntries(v int64) *FinancialReconciliationRunUpsertOne {
	return u.Update(func(s *FinancialReconciliationRunUpsert) {
		s.AddCheckedLedgerEntries(v)
	})
}

// UpdateCheckedLedgerEntries sets the "checked_ledger_entries" field to the value that was provided on create.
func (u *FinancialReconciliationRunUpsertOne) UpdateCheckedLedgerEntries() *FinancialReconciliationRunUpsertOne {
	return u.Update(func(s *FinancialReconciliationRunUpsert) {
		s.UpdateCheckedLedgerEntries()
	})
}

// SetMismatchCount sets the "mismatch_count" field.
func (u *FinancialReconciliationRunUpsertOne) SetMismatchCount(v int64) *FinancialReconciliationRunUpsertOne {
	return u.Update(func(s *FinancialReconciliationRunUpsert) {
		s.SetMismatchCount(v)
	})
}

// AddMismatchCount adds v to the "mismatch_count" field.
func (u *FinancialReconciliationRunUpsertOne) AddMismatchCount(v int64) *FinancialReconciliationRunUpsertOne {
	return u.Update(func(s *FinancialReconciliationRunUpsert) {
		s.AddMismatchCount(v)
	})
}

// UpdateMismatchCount sets the "mismatch_count" field to the value that was provided on create.
func (u *FinancialReconciliationRunUpsertOne) UpdateMismatchCount() *FinancialReconciliationRunUpsertOne {
	return u.Update(func(s *FinancialReconciliationRunUpsert) {
		s.UpdateMismatchCount()
	})
}

// SetSummary sets the "summary" field.
func (u *FinancialReconciliationRunUpsertOne) SetSummary(v map[string]interface{}) *FinancialReconciliationRunUpsertOne {
	return u.Update(func(s *FinancialReconciliationRunUpsert) {
		s.SetSummary(v)
	})
}

// UpdateSummary sets the "summary" field to the value that was provided on create.
func (u *FinancialReconciliationRunUpsertOne) UpdateSummary() *FinancialReconciliationRunUpsertOne {
	return u.Update(func(s *FinancialReconciliationRunUpsert) {
		s.UpdateSummary()
	})
}

// ClearSummary clears the value of the "summary" field.
func (u *FinancialReconciliationRunUpsertOne) ClearSummary() *FinancialReconciliationRunUpsertOne {
	return u.Update(func(s *FinancialReconciliationRunUpsert) {
		s.ClearSummary()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *FinancialReconciliationRunUpsertOne) SetStartedAt(v time.Time) *FinancialReconciliationRunUpsertOne {
	return u.Update(func(s *FinancialReconciliationRunUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *FinancialReconciliationRunUpsertOne) UpdateStartedAt() *FinancialReconciliationRunUpsertOne {
	return u.Update(func(s *FinancialReconciliationRunUpsert) {
		s.UpdateStartedAt()
	})
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *FinancialReconciliationRunUpsertOne) ClearStartedAt() *FinancialReconciliationRunUpsertOne {
	return u.Update(func(s *FinancialReconciliationRunUpsert) {
		s.ClearStartedAt()
	})
}

// SetFinishedAt sets the "finished_at" field.
func (u *FinancialReconciliationRunUpsertOne) SetFinishedAt(v time.Time) *FinancialReconciliationRunUpsertOne {
	return u.Update(func(s *FinancialReconciliationRunUpsert) {
		s.SetFinishedAt(v)
	})
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *FinancialReconciliationRunUpsertOne) UpdateFinishedAt() *FinancialReconciliationRunUpsertOne {
	return u.Update(func(s *FinancialReconciliationRunUpsert) {
		s.UpdateFinishedAt()
	})
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *FinancialReconciliationRunUpsertOne) ClearFinishedAt() *FinancialReconciliationRunUpsertOne {
	return u.Update(func(s *FinancialReconciliationRunUpsert) {
		s.ClearFinishedAt()
	})
}

// Exec executes the query.
func (u *FinancialReconciliationRunUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FinancialReconciliationRunCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FinancialReconciliationRunUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *FinancialReconciliationRunUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *FinancialReconciliationRunUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// FinancialReconciliationRunCreateBulk is the builder for creating many FinancialReconciliationRun entities in bulk.
type FinancialReconciliationRunCreateBulk struct {
	config
	err      error
	builders []*FinancialReconciliationRunCreate
	conflict []sql.ConflictOption
}

// Save creates the FinancialReconciliationRun entities in the database.
func (_c *FinancialReconciliationRunCreateBulk) Save(ctx context.Context) ([]*FinancialReconciliationRun, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*FinancialReconciliationRun, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FinancialReconciliationRunMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FinancialReconciliationRunCreateBulk) SaveX(ctx context.Context) []*FinancialReconciliationRun {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FinancialReconciliationRunCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FinancialReconciliationRunCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.FinancialReconciliationRun.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FinancialReconciliationRunUpsert) {
//			SetRunID(v+v).
//		}).
//		Exec(ctx)
func (_c *FinancialReconciliationRunCreateBulk) OnConflict(opts ...sql.ConflictOption) *FinancialReconciliationRunUpsertBulk {
	_c.conflict = opts
	return &FinancialReconciliationRunUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.FinancialReconciliationRun.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *FinancialReconciliationRunCreateBulk) OnConflictColumns(columns ...string) *FinancialReconciliationRunUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &FinancialReconciliationRunUpsertBulk{
		create: _c,
	}
}

// FinancialReconciliationRunUpsertBulk is the builder for "upsert"-ing
// a bulk of FinancialReconciliationRun nodes.
type FinancialReconciliationRunUpsertBulk struct {
	create *FinancialReconciliationRunCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.FinancialReconciliationRun.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *FinancialReconciliationRunUpsertBulk) UpdateNewValues() *FinancialReconciliationRunUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(financialreconciliationrun.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.FinancialReconciliationRun.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *FinancialReconciliationRunUpsertBulk) Ignore() *FinancialReconciliationRunUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FinancialReconciliationRunUpsertBulk) DoNothing() *FinancialReconciliationRunUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FinancialReconciliationRunCreateBulk.OnConflict
// documentation for more info.
func (u *FinancialReconciliationRunUpsertBulk) Update(set func(*FinancialReconciliationRunUpsert)) *FinancialReconciliationRunUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FinancialReconciliationRunUpsert{UpdateSet: update})
	}))
	return u
}

// SetRunID sets the "run_id" field.
func (u *FinancialReconciliationRunUpsertBulk) SetRunID(v uuid.UUID) *FinancialReconciliationRunUpsertBulk {
	return u.Update(func(s *FinancialReconciliationRunUpsert) {
		s.SetRunID(v)
	})
}

// UpdateRunID sets the "run_id" field to the value that was provided on create.
func (u *FinancialReconciliationRunUpsertBulk) UpdateRunID() *FinancialReconciliationRunUpsertBulk {
	return u.Update(func(s *FinancialReconciliationRunUpsert) {
		s.UpdateRunID()
	})
}

// SetRunDate sets the "run_date" field.
func (u *FinancialReconciliationRunUpsertBulk) SetRunDate(v time.Time) *FinancialReconciliationRunUpsertBulk {
	return u.Update(func(s *FinancialReconciliationRunUpsert) {
		s.SetRunDate(v)
	})
}

// UpdateRunDate sets the "run_date" field to the value that was provided on create.
func (u *FinancialReconciliationRunUpsertBulk) UpdateRunDate() *FinancialReconciliationRunUpsertBulk {
	return u.Update(func(s *FinancialReconciliationRunUpsert) {
		s.UpdateRunDate()
	})
}

// SetStatus sets the "status" field.
func (u *FinancialReconciliationRunUpsertBulk) SetStatus(v string) *FinancialReconciliationRunUpsertBulk {
	return u.Update(func(s *FinancialReconciliationRunUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *FinancialReconciliationRunUpsertBulk) UpdateStatus() *FinancialReconciliationRunUpsertBulk {
	return u.Update(func(s *FinancialReconciliationRunUpsert) {
		s.UpdateStatus()
	})
}

// SetCheckedTransactions sets the "checked_transactions" field.
func (u *FinancialReconciliationRunUpsertBulk) SetCheckedTransactions(v int64) *FinancialReconciliationRunUpsertBulk {
	return u.Update(func(s *FinancialReconciliationRunUpsert) {
		s.SetCheckedTransactions(v)
	})
}

// AddCheckedTransactions adds v to the "checked_transactions" field.
func (u *FinancialReconciliationRunUpsertBulk) AddCheckedTransactions(v int64) *FinancialReconciliationRunUpsertBulk {
	return u.Update(func(s *FinancialReconciliationRunUpsert) {
		s.AddCheckedTransactions(v)
	})
}

// UpdateCheckedTransactions sets the "checked_transactions" field to the value that was provided on create.
func (u *FinancialReconciliationRunUpsertBulk) UpdateCheckedTransactions() *FinancialReconciliationRunUpsertBulk {
	return u.Update(func(s *FinancialReconciliationRunUpsert) {
		s.UpdateCheckedTransactions()
	})
}

// SetCheckedLedgerEntries sets the "checked_ledger_entries" field.
func (u *FinancialReconciliationRunUpsertBulk) SetCheckedLedgerEntries(v int64) *FinancialReconciliationRunUpsertBulk {
	return u.Update(func(s *FinancialReconciliationRunUpsert) {
		s.SetCheckedLedgerEntries(v)
	})
}

// AddCheckedLedgerEntries adds v to the "checked_ledger_entries" field.
func (u *FinancialReconciliationRunUpsertBulk) AddCheckedLedgerEntries(v int64) *FinancialReconciliationRunUpsertBulk {
	return u.Update(func(s *FinancialReconciliationRunUpsert) {
		s.AddCheckedLedgerEntries(v)
	})
}

// UpdateCheckedLedgerEntries sets the "checked_ledger_entries" field to the value that was provided on create.
func (u *FinancialReconciliationRunUpsertBulk) UpdateCheckedLedgerEntries() *FinancialReconciliationRunUpsertBulk {
	return u.Update(func(s *FinancialReconciliationRunUpsert) {
		s.UpdateCheckedLedgerEntries()
	})
}

// SetMismatchCount sets the "mismatch_count" field.
func (u *FinancialReconciliationRunUpsertBulk) SetMismatchCount(v int64) *FinancialReconciliationRunUpsertBulk {
	return u.Update(func(s *FinancialReconciliationRunUpsert) {
		s.SetMismatchCount(v)
	})
}

// AddMismatchCount adds v to the "mismatch_count" field.
func (u *FinancialReconciliationRunUpsertBulk) AddMismatchCount(v int64) *FinancialReconciliationRunUpsertBulk {
	return u.Update(func(s *FinancialReconciliationRunUpsert) {
		s.AddMismatchCount(v)
	})
}

// UpdateMismatchCount sets the "mismatch_count" field to the value that was provided on create.
func (u *FinancialReconciliationRunUpsertBulk) UpdateMismatchCount() *FinancialReconciliationRunUpsertBulk {
	return u.Update(func(s *FinancialReconciliationRunUpsert) {
		s.UpdateMismatchCount()
	})
}

// SetSummary sets the "summary" field.
func (u *FinancialReconciliationRunUpsertBulk) SetSummary(v map[string]interface{}) *FinancialReconciliationRunUpsertBulk {
	return u.Update(func(s *FinancialReconciliationRunUpsert) {
		s.SetSummary(v)
	})
}

// UpdateSummary sets the "summary" field to the value that was provided on create.
func (u *FinancialReconciliationRunUpsertBulk) UpdateSummary() *FinancialReconciliationRunUpsertBulk {
	return u.Update(func(s *FinancialReconciliationRunUpsert) {
		s.UpdateSummary()
	})
}

// ClearSummary clears the value of the "summary" field.
func (u *FinancialReconciliationRunUpsertBulk) ClearSummary() *FinancialReconciliationRunUpsertBulk {
	return u.Update(func(s *FinancialReconciliationRunUpsert) {
		s.ClearSummary()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *FinancialReconciliationRunUpsertBulk) SetStartedAt(v time.Time) *FinancialReconciliationRunUpsertBulk {
	return u.Update(func(s *FinancialReconciliationRunUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *FinancialReconciliationRunUpsertBulk) UpdateStartedAt() *FinancialReconciliationRunUpsertBulk {
	return u.Update(func(s *FinancialReconciliationRunUpsert) {
		s.UpdateStartedAt()
	})
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *FinancialReconciliationRunUpsertBulk) ClearStartedAt() *FinancialReconciliationRunUpsertBulk {
	return u.Update(func(s *FinancialReconciliationRunUpsert) {
		s.ClearStartedAt()
	})
}

// SetFinishedAt sets the "finished_at" field.
func (u *FinancialReconciliationRunUpsertBulk) SetFinishedAt(v time.Time) *FinancialReconciliationRunUpsertBulk {
	return u.Update(func(s *FinancialReconciliationRunUpsert) {
		s.SetFinishedAt(v)
	})
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *FinancialReconciliationRunUpsertBulk) UpdateFinishedAt() *FinancialReconciliationRunUpsertBulk {
	return u.Update(func(s *FinancialReconciliationRunUpsert) {
		s.UpdateFinishedAt()
	})
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *FinancialReconciliationRunUpsertBulk) ClearFinishedAt() *FinancialReconciliationRunUpsertBulk {
	return u.Update(func(s *FinancialReconciliationRunUpsert) {
		s.ClearFinishedAt()
	})
}

// Exec executes the query.
func (u *FinancialReconciliationRunUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the FinancialReconciliationRunCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FinancialReconciliationRunCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FinancialReconciliationRunUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
