// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/ledgeraccount"
	"github.com/Wei-Shaw/sub2api/ent/ledgerentry"
	"github.com/Wei-Shaw/sub2api/ent/transactionlog"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

// LedgerEntryCreate is the builder for creating a LedgerEntry entity.
type LedgerEntryCreate struct {
	config
	mutation *LedgerEntryMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetEntryID sets the "entry_id" field.
func (_c *LedgerEntryCreate) SetEntryID(v uuid.UUID) *LedgerEntryCreate {
	_c.mutation.SetEntryID(v)
	return _c
}

// SetNillableEntryID sets the "entry_id" field if the given value is not nil.
func (_c *LedgerEntryCreate) SetNillableEntryID(v *uuid.UUID) *LedgerEntryCreate {
	if v != nil {
		_c.SetEntryID(*v)
	}
	return _c
}

// SetTransactionLogID sets the "transaction_log_id" field.
func (_c *LedgerEntryCreate) SetTransactionLogID(v int64) *LedgerEntryCreate {
	_c.mutation.SetTransactionLogID(v)
	return _c
}

// SetTxID sets the "tx_id" field.
func (_c *LedgerEntryCreate) SetTxID(v uuid.UUID) *LedgerEntryCreate {
	_c.mutation.SetTxID(v)
	return _c
}

// SetLedgerAccountID sets the "ledger_account_id" field.
func (_c *LedgerEntryCreate) SetLedgerAccountID(v int64) *LedgerEntryCreate {
	_c.mutation.SetLedgerAccountID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *LedgerEntryCreate) SetUserID(v int64) *LedgerEntryCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *LedgerEntryCreate) SetNillableUserID(v *int64) *LedgerEntryCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetEntrySide sets the "entry_side" field.
func (_c *LedgerEntryCreate) SetEntrySide(v string) *LedgerEntryCreate {
	_c.mutation.SetEntrySide(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *LedgerEntryCreate) SetAmount(v decimal.Decimal) *LedgerEntryCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetBusinessModule sets the "business_module" field.
func (_c *LedgerEntryCreate) SetBusinessModule(v string) *LedgerEntryCreate {
	_c.mutation.SetBusinessModule(v)
	return _c
}

// SetTxType sets the "tx_type" field.
func (_c *LedgerEntryCreate) SetTxType(v string) *LedgerEntryCreate {
	_c.mutation.SetTxType(v)
	return _c
}

// SetReferenceType sets the "reference_type" field.
func (_c *LedgerEntryCreate) SetReferenceType(v string) *LedgerEntryCreate {
	_c.mutation.SetReferenceType(v)
	return _c
}

// SetNillableReferenceType sets the "reference_type" field if the given value is not nil.
func (_c *LedgerEntryCreate) SetNillableReferenceType(v *string) *LedgerEntryCreate {
	if v != nil {
		_c.SetReferenceType(*v)
	}
	return _c
}

// SetReferenceID sets the "reference_id" field.
func (_c *LedgerEntryCreate) SetReferenceID(v string) *LedgerEntryCreate {
	_c.mutation.SetReferenceID(v)
	return _c
}

// SetNillableReferenceID sets the "reference_id" field if the given value is not nil.
func (_c *LedgerEntryCreate) SetNillableReferenceID(v *string) *LedgerEntryCreate {
	if v != nil {
		_c.SetReferenceID(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *LedgerEntryCreate) SetDescription(v string) *LedgerEntryCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *LedgerEntryCreate) SetNillableDescription(v *string) *LedgerEntryCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *LedgerEntryCreate) SetMetadata(v map[string]interface{}) *LedgerEntryCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *LedgerEntryCreate) SetCreatedAt(v time.Time) *LedgerEntryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LedgerEntryCreate) SetNillableCreatedAt(v *time.Time) *LedgerEntryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetTransactionID sets the "transaction" edge to the TransactionLog entity by ID.
func (_c *LedgerEntryCreate) SetTransactionID(id int64) *LedgerEntryCreate {
	_c.mutation.SetTransactionID(id)
	return _c
}

// SetTransaction sets the "transaction" edge to the TransactionLog entity.
func (_c *LedgerEntryCreate) SetTransaction(v *TransactionLog) *LedgerEntryCreate {
	return _c.SetTransactionID(v.ID)
}

// SetLedgerAccount sets the "ledger_account" edge to the LedgerAccount entity.
func (_c *LedgerEntryCreate) SetLedgerAccount(v *LedgerAccount) *LedgerEntryCreate {
	return _c.SetLedgerAccountID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *LedgerEntryCreate) SetUser(v *User) *LedgerEntryCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the LedgerEntryMutation object of the builder.
func (_c *LedgerEntryCreate) Mutation() *LedgerEntryMutation {
	return _c.mutation
}

// Save creates the LedgerEntry in the database.
func (_c *LedgerEntryCreate) Save(ctx context.Context) (*LedgerEntry, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LedgerEntryCreate) SaveX(ctx context.Context) *LedgerEntry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LedgerEntryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LedgerEntryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LedgerEntryCreate) defaults() {
	if _, ok := _c.mutation.EntryID(); !ok {
		v := ledgerentry.DefaultEntryID()
		_c.mutation.SetEntryID(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := ledgerentry.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := ledgerentry.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LedgerEntryCreate) check() error {
	if _, ok := _c.mutation.EntryID(); !ok {
		return &ValidationError{Name: "entry_id", err: errors.New(`ent: missing required field "LedgerEntry.entry_id"`)}
	}
	if _, ok := _c.mutation.TransactionLogID(); !ok {
		return &ValidationError{Name: "transaction_log_id", err: errors.New(`ent: missing required field "LedgerEntry.transaction_log_id"`)}
	}
	if _, ok := _c.mutation.TxID(); !ok {
		return &ValidationError{Name: "tx_id", err: errors.New(`ent: missing required field "LedgerEntry.tx_id"`)}
	}
	if _, ok := _c.mutation.LedgerAccountID(); !ok {
		return &ValidationError{Name: "ledger_account_id", err: errors.New(`ent: missing required field "LedgerEntry.ledger_account_id"`)}
	}
	if _, ok := _c.mutation.EntrySide(); !ok {
		return &ValidationError{Name: "entry_side", err: errors.New(`ent: missing required field "LedgerEntry.entry_side"`)}
	}
	if v, ok := _c.mutation.EntrySide(); ok {
		if err := ledgerentry.EntrySideValidator(v); err != nil {
			return &ValidationError{Name: "entry_side", err: fmt.Errorf(`ent: validator failed for field "LedgerEntry.entry_side": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "LedgerEntry.amount"`)}
	}
	if _, ok := _c.mutation.BusinessModule(); !ok {
		return &ValidationError{Name: "business_module", err: errors.New(`ent: missing required field "LedgerEntry.business_module"`)}
	}
	if v, ok := _c.mutation.BusinessModule(); ok {
		if err := ledgerentry.BusinessModuleValidator(v); err != nil {
			return &ValidationError{Name: "business_module", err: fmt.Errorf(`ent: validator failed for field "LedgerEntry.business_module": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TxType(); !ok {
		return &ValidationError{Name: "tx_type", err: errors.New(`ent: missing required field "LedgerEntry.tx_type"`)}
	}
	if v, ok := _c.mutation.TxType(); ok {
		if err := ledgerentry.TxTypeValidator(v); err != nil {
			return &ValidationError{Name: "tx_type", err: fmt.Errorf(`ent: validator failed for field "LedgerEntry.tx_type": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ReferenceType(); ok {
		if err := ledgerentry.ReferenceTypeValidator(v); err != nil {
			return &ValidationError{Name: "reference_type", err: fmt.Errorf(`ent: validator failed for field "LedgerEntry.reference_type": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ReferenceID(); ok {
		if err := ledgerentry.ReferenceIDValidator(v); err != nil {
			return &ValidationError{Name: "reference_id", err: fmt.Errorf(`ent: validator failed for field "LedgerEntry.reference_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "LedgerEntry.description"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "LedgerEntry.created_at"`)}
	}
	if len(_c.mutation.TransactionIDs()) == 0 {
		return &ValidationError{Name: "transaction", err: errors.New(`ent: missing required edge "LedgerEntry.transaction"`)}
	}
	if len(_c.mutation.LedgerAccountIDs()) == 0 {
		return &ValidationError{Name: "ledger_account", err: errors.New(`ent: missing required edge "LedgerEntry.ledger_account"`)}
	}
	return nil
}

func (_c *LedgerEntryCreate) sqlSave(ctx context.Context) (*LedgerEntry, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LedgerEntryCreate) createSpec() (*LedgerEntry, *sqlgraph.CreateSpec) {
	var (
		_node = &LedgerEntry{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ledgerentry.Table, sqlgraph.NewFieldSpec(ledgerentry.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.EntryID(); ok {
		_spec.SetField(ledgerentry.FieldEntryID, field.TypeUUID, value)
		_node.EntryID = value
	}
	if value, ok := _c.mutation.TxID(); ok {
		_spec.SetField(ledgerentry.FieldTxID, field.TypeUUID, value)
		_node.TxID = value
	}
	if value, ok := _c.mutation.EntrySide(); ok {
		_spec.SetField(ledgerentry.FieldEntrySide, field.TypeString, value)
		_node.EntrySide = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(ledgerentry.FieldAmount, field.TypeOther, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.BusinessModule(); ok {
		_spec.SetField(ledgerentry.FieldBusinessModule, field.TypeString, value)
		_node.BusinessModule = value
	}
	if value, ok := _c.mutation.TxType(); ok {
		_spec.SetField(ledgerentry.FieldTxType, field.TypeString, value)
		_node.TxType = value
	}
	if value, ok := _c.mutation.ReferenceType(); ok {
		_spec.SetField(ledgerentry.FieldReferenceType, field.TypeString, value)
		_node.ReferenceType = &value
	}
	if value, ok := _c.mutation.ReferenceID(); ok {
		_spec.SetField(ledgerentry.FieldReferenceID, field.TypeString, value)
		_node.ReferenceID = &value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(ledgerentry.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(ledgerentry.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(ledgerentry.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.TransactionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ledgerentry.TransactionTable,
			Columns: []string{ledgerentry.TransactionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transactionlog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TransactionLogID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.LedgerAccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ledgerentry.LedgerAccountTable,
			Columns: []string{ledgerentry.LedgerAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgeraccount.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.LedgerAccountID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ledgerentry.UserTable,
			Columns: []string{ledgerentry.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LedgerEntry.Create().
//		SetEntryID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LedgerEntryUpsert) {
//			SetEntryID(v+v).
//		}).
//		Exec(ctx)
func (_c *LedgerEntryCreate) OnConflict(opts ...sql.ConflictOption) *LedgerEntryUpsertOne {
	_c.conflict = opts
	return &LedgerEntryUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LedgerEntry.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LedgerEntryCreate) OnConflictColumns(columns ...string) *LedgerEntryUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LedgerEntryUpsertOne{
		create: _c,
	}
}

type (
	// LedgerEntryUpsertOne is the builder for "upsert"-ing
	//  one LedgerEntry node.
	LedgerEntryUpsertOne struct {
		create *LedgerEntryCreate
	}

	// LedgerEntryUpsert is the "OnConflict" setter.
	LedgerEntryUpsert struct {
		*sql.UpdateSet
	}
)

// SetTransactionLogID sets the "transaction_log_id" field.
func (u *LedgerEntryUpsert) SetTransactionLogID(v int64) *LedgerEntryUpsert {
	u.Set(ledgerentry.FieldTransactionLogID, v)
	return u
}

// UpdateTransactionLogID sets the "transaction_log_id" field to the value that was provided on create.
func (u *LedgerEntryUpsert) UpdateTransactionLogID() *LedgerEntryUpsert {
	u.SetExcluded(ledgerentry.FieldTransactionLogID)
	return u
}

// SetLedgerAccountID sets the "ledger_account_id" field.
func (u *LedgerEntryUpsert) SetLedgerAccountID(v int64) *LedgerEntryUpsert {
	u.Set(ledgerentry.FieldLedgerAccountID, v)
	return u
}

// UpdateLedgerAccountID sets the "ledger_account_id" field to the value that was provided on create.
func (u *LedgerEntryUpsert) UpdateLedgerAccountID() *LedgerEntryUpsert {
	u.SetExcluded(ledgerentry.FieldLedgerAccountID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *LedgerEntryUpsert) SetUserID(v int64) *LedgerEntryUpsert {
	u.Set(ledgerentry.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *LedgerEntryUpsert) UpdateUserID() *LedgerEntryUpsert {
	u.SetExcluded(ledgerentry.FieldUserID)
	return u
}

// ClearUserID clears the value of the "user_id" field.
func (u *LedgerEntryUpsert) ClearUserID() *LedgerEntryUpsert {
	u.SetNull(ledgerentry.FieldUserID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.LedgerEntry.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LedgerEntryUpsertOne) UpdateNewValues() *LedgerEntryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.EntryID(); exists {
			s.SetIgnore(ledgerentry.FieldEntryID)
		}
		if _, exists := u.create.mutation.TxID(); exists {
			s.SetIgnore(ledgerentry.FieldTxID)
		}
		if _, exists := u.create.mutation.EntrySide(); exists {
			s.SetIgnore(ledgerentry.FieldEntrySide)
		}
		if _, exists := u.create.mutation.Amount(); exists {
			s.SetIgnore(ledgerentry.FieldAmount)
		}
		if _, exists := u.create.mutation.BusinessModule(); exists {
			s.SetIgnore(ledgerentry.FieldBusinessModule)
		}
		if _, exists := u.create.mutation.TxType(); exists {
			s.SetIgnore(ledgerentry.FieldTxType)
		}
		if _, exists := u.create.mutation.ReferenceType(); exists {
			s.SetIgnore(ledgerentry.FieldReferenceType)
		}
		if _, exists := u.create.mutation.ReferenceID(); exists {
			s.SetIgnore(ledgerentry.FieldReferenceID)
		}
		if _, exists := u.create.mutation.Description(); exists {
			s.SetIgnore(ledgerentry.FieldDescription)
		}
		if _, exists := u.create.mutation.Metadata(); exists {
			s.SetIgnore(ledgerentry.FieldMetadata)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(ledgerentry.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LedgerEntry.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *LedgerEntryUpsertOne) Ignore() *LedgerEntryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LedgerEntryUpsertOne) DoNothing() *LedgerEntryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LedgerEntryCreate.OnConflict
// documentation for more info.
func (u *LedgerEntryUpsertOne) Update(set func(*LedgerEntryUpsert)) *LedgerEntryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LedgerEntryUpsert{UpdateSet: update})
	}))
	return u
}

// SetTransactionLogID sets the "transaction_log_id" field.
func (u *LedgerEntryUpsertOne) SetTransactionLogID(v int64) *LedgerEntryUpsertOne {
	return u.Update(func(s *LedgerEntryUpsert) {
		s.SetTransactionLogID(v)
	})
}

// UpdateTransactionLogID sets the "transaction_log_id" field to the value that was provided on create.
func (u *LedgerEntryUpsertOne) UpdateTransactionLogID() *LedgerEntryUpsertOne {
	return u.Update(func(s *LedgerEntryUpsert) {
		s.UpdateTransactionLogID()
	})
}

// SetLedgerAccountID sets the "ledger_account_id" field.
func (u *LedgerEntryUpsertOne) SetLedgerAccountID(v int64) *LedgerEntryUpsertOne {
	return u.Update(func(s *LedgerEntryUpsert) {
		s.SetLedgerAccountID(v)
	})
}

// UpdateLedgerAccountID sets the "ledger_account_id" field to the value that was provided on create.
func (u *LedgerEntryUpsertOne) UpdateLedgerAccountID() *LedgerEntryUpsertOne {
	return u.Update(func(s *LedgerEntryUpsert) {
		s.UpdateLedgerAccountID()
	})
}

// SetUserID sets the "user_id" field.
func (u *LedgerEntryUpsertOne) SetUserID(v int64) *LedgerEntryUpsertOne {
	return u.Update(func(s *LedgerEntryUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *LedgerEntryUpsertOne) UpdateUserID() *LedgerEntryUpsertOne {
	return u.Update(func(s *LedgerEntryUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *LedgerEntryUpsertOne) ClearUserID() *LedgerEntryUpsertOne {
	return u.Update(func(s *LedgerEntryUpsert) {
		s.ClearUserID()
	})
}

// Exec executes the query.
func (u *LedgerEntryUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LedgerEntryCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LedgerEntryUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *LedgerEntryUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *LedgerEntryUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// LedgerEntryCreateBulk is the builder for creating many LedgerEntry entities in bulk.
type LedgerEntryCreateBulk struct {
	config
	err      error
	builders []*LedgerEntryCreate
	conflict []sql.ConflictOption
}

// Save creates the LedgerEntry entities in the database.
func (_c *LedgerEntryCreateBulk) Save(ctx context.Context) ([]*LedgerEntry, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LedgerEntry, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LedgerEntryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LedgerEntryCreateBulk) SaveX(ctx context.Context) []*LedgerEntry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LedgerEntryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LedgerEntryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LedgerEntry.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LedgerEntryUpsert) {
//			SetEntryID(v+v).
//		}).
//		Exec(ctx)
func (_c *LedgerEntryCreateBulk) OnConflict(opts ...sql.ConflictOption) *LedgerEntryUpsertBulk {
	_c.conflict = opts
	return &LedgerEntryUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LedgerEntry.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LedgerEntryCreateBulk) OnConflictColumns(columns ...string) *LedgerEntryUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LedgerEntryUpsertBulk{
		create: _c,
	}
}

// LedgerEntryUpsertBulk is the builder for "upsert"-ing
// a bulk of LedgerEntry nodes.
type LedgerEntryUpsertBulk struct {
	create *LedgerEntryCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.LedgerEntry.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LedgerEntryUpsertBulk) UpdateNewValues() *LedgerEntryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.EntryID(); exists {
				s.SetIgnore(ledgerentry.FieldEntryID)
			}
			if _, exists := b.mutation.TxID(); exists {
				s.SetIgnore(ledgerentry.FieldTxID)
			}
			if _, exists := b.mutation.EntrySide(); exists {
				s.SetIgnore(ledgerentry.FieldEntrySide)
			}
			if _, exists := b.mutation.Amount(); exists {
				s.SetIgnore(ledgerentry.FieldAmount)
			}
			if _, exists := b.mutation.BusinessModule(); exists {
				s.SetIgnore(ledgerentry.FieldBusinessModule)
			}
			if _, exists := b.mutation.TxType(); exists {
				s.SetIgnore(ledgerentry.FieldTxType)
			}
			if _, exists := b.mutation.ReferenceType(); exists {
				s.SetIgnore(ledgerentry.FieldReferenceType)
			}
			if _, exists := b.mutation.ReferenceID(); exists {
				s.SetIgnore(ledgerentry.FieldReferenceID)
			}
			if _, exists := b.mutation.Description(); exists {
				s.SetIgnore(ledgerentry.FieldDescription)
			}
			if _, exists := b.mutation.Metadata(); exists {
				s.SetIgnore(ledgerentry.FieldMetadata)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(ledgerentry.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LedgerEntry.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *LedgerEntryUpsertBulk) Ignore() *LedgerEntryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LedgerEntryUpsertBulk) DoNothing() *LedgerEntryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LedgerEntryCreateBulk.OnConflict
// documentation for more info.
func (u *LedgerEntryUpsertBulk) Update(set func(*LedgerEntryUpsert)) *LedgerEntryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LedgerEntryUpsert{UpdateSet: update})
	}))
	return u
}

// SetTransactionLogID sets the "transaction_log_id" field.
func (u *LedgerEntryUpsertBulk) SetTransactionLogID(v int64) *LedgerEntryUpsertBulk {
	return u.Update(func(s *LedgerEntryUpsert) {
		s.SetTransactionLogID(v)
	})
}

// UpdateTransactionLogID sets the "transaction_log_id" field to the value that was provided on create.
func (u *LedgerEntryUpsertBulk) UpdateTransactionLogID() *LedgerEntryUpsertBulk {
	return u.Update(func(s *LedgerEntryUpsert) {
		s.UpdateTransactionLogID()
	})
}

// SetLedgerAccountID sets the "ledger_account_id" field.
func (u *LedgerEntryUpsertBulk) SetLedgerAccountID(v int64) *LedgerEntryUpsertBulk {
	return u.Update(func(s *LedgerEntryUpsert) {
		s.SetLedgerAccountID(v)
	})
}

// UpdateLedgerAccountID sets the "ledger_account_id" field to the value that was provided on create.
func (u *LedgerEntryUpsertBulk) UpdateLedgerAccountID() *LedgerEntryUpsertBulk {
	return u.Update(func(s *LedgerEntryUpsert) {
		s.UpdateLedgerAccountID()
	})
}

// SetUserID sets the "user_id" field.
func (u *LedgerEntryUpsertBulk) SetUserID(v int64) *LedgerEntryUpsertBulk {
	return u.Update(func(s *LedgerEntryUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *LedgerEntryUpsertBulk) UpdateUserID() *LedgerEntryUpsertBulk {
	return u.Update(func(s *LedgerEntryUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *LedgerEntryUpsertBulk) ClearUserID() *LedgerEntryUpsertBulk {
	return u.Update(func(s *LedgerEntryUpsert) {
		s.ClearUserID()
	})
}

// Exec executes the query.
func (u *LedgerEntryUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the LedgerEntryCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LedgerEntryCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LedgerEntryUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
