// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/loancontract"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

// LoanContractCreate is the builder for creating a LoanContract entity.
type LoanContractCreate struct {
	config
	mutation *LoanContractMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *LoanContractCreate) SetCreatedAt(v time.Time) *LoanContractCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LoanContractCreate) SetNillableCreatedAt(v *time.Time) *LoanContractCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *LoanContractCreate) SetUpdatedAt(v time.Time) *LoanContractCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *LoanContractCreate) SetNillableUpdatedAt(v *time.Time) *LoanContractCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetLoanID sets the "loan_id" field.
func (_c *LoanContractCreate) SetLoanID(v uuid.UUID) *LoanContractCreate {
	_c.mutation.SetLoanID(v)
	return _c
}

// SetNillableLoanID sets the "loan_id" field if the given value is not nil.
func (_c *LoanContractCreate) SetNillableLoanID(v *uuid.UUID) *LoanContractCreate {
	if v != nil {
		_c.SetLoanID(*v)
	}
	return _c
}

// SetBorrowerID sets the "borrower_id" field.
func (_c *LoanContractCreate) SetBorrowerID(v int64) *LoanContractCreate {
	_c.mutation.SetBorrowerID(v)
	return _c
}

// SetLenderType sets the "lender_type" field.
func (_c *LoanContractCreate) SetLenderType(v string) *LoanContractCreate {
	_c.mutation.SetLenderType(v)
	return _c
}

// SetLenderID sets the "lender_id" field.
func (_c *LoanContractCreate) SetLenderID(v int64) *LoanContractCreate {
	_c.mutation.SetLenderID(v)
	return _c
}

// SetNillableLenderID sets the "lender_id" field if the given value is not nil.
func (_c *LoanContractCreate) SetNillableLenderID(v *int64) *LoanContractCreate {
	if v != nil {
		_c.SetLenderID(*v)
	}
	return _c
}

// SetPrincipal sets the "principal" field.
func (_c *LoanContractCreate) SetPrincipal(v decimal.Decimal) *LoanContractCreate {
	_c.mutation.SetPrincipal(v)
	return _c
}

// SetInterestRate sets the "interest_rate" field.
func (_c *LoanContractCreate) SetInterestRate(v decimal.Decimal) *LoanContractCreate {
	_c.mutation.SetInterestRate(v)
	return _c
}

// SetAccruedInterest sets the "accrued_interest" field.
func (_c *LoanContractCreate) SetAccruedInterest(v decimal.Decimal) *LoanContractCreate {
	_c.mutation.SetAccruedInterest(v)
	return _c
}

// SetNillableAccruedInterest sets the "accrued_interest" field if the given value is not nil.
func (_c *LoanContractCreate) SetNillableAccruedInterest(v *decimal.Decimal) *LoanContractCreate {
	if v != nil {
		_c.SetAccruedInterest(*v)
	}
	return _c
}

// SetRepaidPrincipal sets the "repaid_principal" field.
func (_c *LoanContractCreate) SetRepaidPrincipal(v decimal.Decimal) *LoanContractCreate {
	_c.mutation.SetRepaidPrincipal(v)
	return _c
}

// SetNillableRepaidPrincipal sets the "repaid_principal" field if the given value is not nil.
func (_c *LoanContractCreate) SetNillableRepaidPrincipal(v *decimal.Decimal) *LoanContractCreate {
	if v != nil {
		_c.SetRepaidPrincipal(*v)
	}
	return _c
}

// SetRepaidInterest sets the "repaid_interest" field.
func (_c *LoanContractCreate) SetRepaidInterest(v decimal.Decimal) *LoanContractCreate {
	_c.mutation.SetRepaidInterest(v)
	return _c
}

// SetNillableRepaidInterest sets the "repaid_interest" field if the given value is not nil.
func (_c *LoanContractCreate) SetNillableRepaidInterest(v *decimal.Decimal) *LoanContractCreate {
	if v != nil {
		_c.SetRepaidInterest(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *LoanContractCreate) SetStatus(v string) *LoanContractCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *LoanContractCreate) SetNillableStatus(v *string) *LoanContractCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetDueDate sets the "due_date" field.
func (_c *LoanContractCreate) SetDueDate(v time.Time) *LoanContractCreate {
	_c.mutation.SetDueDate(v)
	return _c
}

// SetBorrower sets the "borrower" edge to the User entity.
func (_c *LoanContractCreate) SetBorrower(v *User) *LoanContractCreate {
	return _c.SetBorrowerID(v.ID)
}

// SetLender sets the "lender" edge to the User entity.
func (_c *LoanContractCreate) SetLender(v *User) *LoanContractCreate {
	return _c.SetLenderID(v.ID)
}

// Mutation returns the LoanContractMutation object of the builder.
func (_c *LoanContractCreate) Mutation() *LoanContractMutation {
	return _c.mutation
}

// Save creates the LoanContract in the database.
func (_c *LoanContractCreate) Save(ctx context.Context) (*LoanContract, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LoanContractCreate) SaveX(ctx context.Context) *LoanContract {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LoanContractCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LoanContractCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LoanContractCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := loancontract.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := loancontract.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.LoanID(); !ok {
		v := loancontract.DefaultLoanID()
		_c.mutation.SetLoanID(v)
	}
	if _, ok := _c.mutation.AccruedInterest(); !ok {
		v := loancontract.DefaultAccruedInterest
		_c.mutation.SetAccruedInterest(v)
	}
	if _, ok := _c.mutation.RepaidPrincipal(); !ok {
		v := loancontract.DefaultRepaidPrincipal
		_c.mutation.SetRepaidPrincipal(v)
	}
	if _, ok := _c.mutation.RepaidInterest(); !ok {
		v := loancontract.DefaultRepaidInterest
		_c.mutation.SetRepaidInterest(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := loancontract.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LoanContractCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "LoanContract.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "LoanContract.updated_at"`)}
	}
	if _, ok := _c.mutation.LoanID(); !ok {
		return &ValidationError{Name: "loan_id", err: errors.New(`ent: missing required field "LoanContract.loan_id"`)}
	}
	if _, ok := _c.mutation.BorrowerID(); !ok {
		return &ValidationError{Name: "borrower_id", err: errors.New(`ent: missing required field "LoanContract.borrower_id"`)}
	}
	if _, ok := _c.mutation.LenderType(); !ok {
		return &ValidationError{Name: "lender_type", err: errors.New(`ent: missing required field "LoanContract.lender_type"`)}
	}
	if v, ok := _c.mutation.LenderType(); ok {
		if err := loancontract.LenderTypeValidator(v); err != nil {
			return &ValidationError{Name: "lender_type", err: fmt.Errorf(`ent: validator failed for field "LoanContract.lender_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Principal(); !ok {
		return &ValidationError{Name: "principal", err: errors.New(`ent: missing required field "LoanContract.principal"`)}
	}
	if _, ok := _c.mutation.InterestRate(); !ok {
		return &ValidationError{Name: "interest_rate", err: errors.New(`ent: missing required field "LoanContract.interest_rate"`)}
	}
	if _, ok := _c.mutation.AccruedInterest(); !ok {
		return &ValidationError{Name: "accrued_interest", err: errors.New(`ent: missing required field "LoanContract.accrued_interest"`)}
	}
	if _, ok := _c.mutation.RepaidPrincipal(); !ok {
		return &ValidationError{Name: "repaid_principal", err: errors.New(`ent: missing required field "LoanContract.repaid_principal"`)}
	}
	if _, ok := _c.mutation.RepaidInterest(); !ok {
		return &ValidationError{Name: "repaid_interest", err: errors.New(`ent: missing required field "LoanContract.repaid_interest"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "LoanContract.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := loancontract.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "LoanContract.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DueDate(); !ok {
		return &ValidationError{Name: "due_date", err: errors.New(`ent: missing required field "LoanContract.due_date"`)}
	}
	if len(_c.mutation.BorrowerIDs()) == 0 {
		return &ValidationError{Name: "borrower", err: errors.New(`ent: missing required edge "LoanContract.borrower"`)}
	}
	return nil
}

func (_c *LoanContractCreate) sqlSave(ctx context.Context) (*LoanContract, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LoanContractCreate) createSpec() (*LoanContract, *sqlgraph.CreateSpec) {
	var (
		_node = &LoanContract{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(loancontract.Table, sqlgraph.NewFieldSpec(loancontract.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(loancontract.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(loancontract.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.LoanID(); ok {
		_spec.SetField(loancontract.FieldLoanID, field.TypeUUID, value)
		_node.LoanID = value
	}
	if value, ok := _c.mutation.LenderType(); ok {
		_spec.SetField(loancontract.FieldLenderType, field.TypeString, value)
		_node.LenderType = value
	}
	if value, ok := _c.mutation.Principal(); ok {
		_spec.SetField(loancontract.FieldPrincipal, field.TypeOther, value)
		_node.Principal = value
	}
	if value, ok := _c.mutation.InterestRate(); ok {
		_spec.SetField(loancontract.FieldInterestRate, field.TypeOther, value)
		_node.InterestRate = value
	}
	if value, ok := _c.mutation.AccruedInterest(); ok {
		_spec.SetField(loancontract.FieldAccruedInterest, field.TypeOther, value)
		_node.AccruedInterest = value
	}
	if value, ok := _c.mutation.RepaidPrincipal(); ok {
		_spec.SetField(loancontract.FieldRepaidPrincipal, field.TypeOther, value)
		_node.RepaidPrincipal = value
	}
	if value, ok := _c.mutation.RepaidInterest(); ok {
		_spec.SetField(loancontract.FieldRepaidInterest, field.TypeOther, value)
		_node.RepaidInterest = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(loancontract.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.DueDate(); ok {
		_spec.SetField(loancontract.FieldDueDate, field.TypeTime, value)
		_node.DueDate = value
	}
	if nodes := _c.mutation.BorrowerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   loancontract.BorrowerTable,
			Columns: []string{loancontract.BorrowerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.BorrowerID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.LenderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   loancontract.LenderTable,
			Columns: []string{loancontract.LenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.LenderID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LoanContract.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LoanContractUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *LoanContractCreate) OnConflict(opts ...sql.ConflictOption) *LoanContractUpsertOne {
	_c.conflict = opts
	return &LoanContractUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LoanContract.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LoanContractCreate) OnConflictColumns(columns ...string) *LoanContractUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LoanContractUpsertOne{
		create: _c,
	}
}

type (
	// LoanContractUpsertOne is the builder for "upsert"-ing
	//  one LoanContract node.
	LoanContractUpsertOne struct {
		create *LoanContractCreate
	}

	// LoanContractUpsert is the "OnConflict" setter.
	LoanContractUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *LoanContractUpsert) SetUpdatedAt(v time.Time) *LoanContractUpsert {
	u.Set(loancontract.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LoanContractUpsert) UpdateUpdatedAt() *LoanContractUpsert {
	u.SetExcluded(loancontract.FieldUpdatedAt)
	return u
}

// SetLoanID sets the "loan_id" field.
func (u *LoanContractUpsert) SetLoanID(v uuid.UUID) *LoanContractUpsert {
	u.Set(loancontract.FieldLoanID, v)
	return u
}

// UpdateLoanID sets the "loan_id" field to the value that was provided on create.
func (u *LoanContractUpsert) UpdateLoanID() *LoanContractUpsert {
	u.SetExcluded(loancontract.FieldLoanID)
	return u
}

// SetBorrowerID sets the "borrower_id" field.
func (u *LoanContractUpsert) SetBorrowerID(v int64) *LoanContractUpsert {
	u.Set(loancontract.FieldBorrowerID, v)
	return u
}

// UpdateBorrowerID sets the "borrower_id" field to the value that was provided on create.
func (u *LoanContractUpsert) UpdateBorrowerID() *LoanContractUpsert {
	u.SetExcluded(loancontract.FieldBorrowerID)
	return u
}

// SetLenderType sets the "lender_type" field.
func (u *LoanContractUpsert) SetLenderType(v string) *LoanContractUpsert {
	u.Set(loancontract.FieldLenderType, v)
	return u
}

// UpdateLenderType sets the "lender_type" field to the value that was provided on create.
func (u *LoanContractUpsert) UpdateLenderType() *LoanContractUpsert {
	u.SetExcluded(loancontract.FieldLenderType)
	return u
}

// SetLenderID sets the "lender_id" field.
func (u *LoanContractUpsert) SetLenderID(v int64) *LoanContractUpsert {
	u.Set(loancontract.FieldLenderID, v)
	return u
}

// UpdateLenderID sets the "lender_id" field to the value that was provided on create.
func (u *LoanContractUpsert) UpdateLenderID() *LoanContractUpsert {
	u.SetExcluded(loancontract.FieldLenderID)
	return u
}

// ClearLenderID clears the value of the "lender_id" field.
func (u *LoanContractUpsert) ClearLenderID() *LoanContractUpsert {
	u.SetNull(loancontract.FieldLenderID)
	return u
}

// SetPrincipal sets the "principal" field.
func (u *LoanContractUpsert) SetPrincipal(v decimal.Decimal) *LoanContractUpsert {
	u.Set(loancontract.FieldPrincipal, v)
	return u
}

// UpdatePrincipal sets the "principal" field to the value that was provided on create.
func (u *LoanContractUpsert) UpdatePrincipal() *LoanContractUpsert {
	u.SetExcluded(loancontract.FieldPrincipal)
	return u
}

// SetInterestRate sets the "interest_rate" field.
func (u *LoanContractUpsert) SetInterestRate(v decimal.Decimal) *LoanContractUpsert {
	u.Set(loancontract.FieldInterestRate, v)
	return u
}

// UpdateInterestRate sets the "interest_rate" field to the value that was provided on create.
func (u *LoanContractUpsert) UpdateInterestRate() *LoanContractUpsert {
	u.SetExcluded(loancontract.FieldInterestRate)
	return u
}

// SetAccruedInterest sets the "accrued_interest" field.
func (u *LoanContractUpsert) SetAccruedInterest(v decimal.Decimal) *LoanContractUpsert {
	u.Set(loancontract.FieldAccruedInterest, v)
	return u
}

// UpdateAccruedInterest sets the "accrued_interest" field to the value that was provided on create.
func (u *LoanContractUpsert) UpdateAccruedInterest() *LoanContractUpsert {
	u.SetExcluded(loancontract.FieldAccruedInterest)
	return u
}

// SetRepaidPrincipal sets the "repaid_principal" field.
func (u *LoanContractUpsert) SetRepaidPrincipal(v decimal.Decimal) *LoanContractUpsert {
	u.Set(loancontract.FieldRepaidPrincipal, v)
	return u
}

// UpdateRepaidPrincipal sets the "repaid_principal" field to the value that was provided on create.
func (u *LoanContractUpsert) UpdateRepaidPrincipal() *LoanContractUpsert {
	u.SetExcluded(loancontract.FieldRepaidPrincipal)
	return u
}

// SetRepaidInterest sets the "repaid_interest" field.
func (u *LoanContractUpsert) SetRepaidInterest(v decimal.Decimal) *LoanContractUpsert {
	u.Set(loancontract.FieldRepaidInterest, v)
	return u
}

// UpdateRepaidInterest sets the "repaid_interest" field to the value that was provided on create.
func (u *LoanContractUpsert) UpdateRepaidInterest() *LoanContractUpsert {
	u.SetExcluded(loancontract.FieldRepaidInterest)
	return u
}

// SetStatus sets the "status" field.
func (u *LoanContractUpsert) SetStatus(v string) *LoanContractUpsert {
	u.Set(loancontract.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *LoanContractUpsert) UpdateStatus() *LoanContractUpsert {
	u.SetExcluded(loancontract.FieldStatus)
	return u
}

// SetDueDate sets the "due_date" field.
func (u *LoanContractUpsert) SetDueDate(v time.Time) *LoanContractUpsert {
	u.Set(loancontract.FieldDueDate, v)
	return u
}

// UpdateDueDate sets the "due_date" field to the value that was provided on create.
func (u *LoanContractUpsert) UpdateDueDate() *LoanContractUpsert {
	u.SetExcluded(loancontract.FieldDueDate)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.LoanContract.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LoanContractUpsertOne) UpdateNewValues() *LoanContractUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(loancontract.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LoanContract.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *LoanContractUpsertOne) Ignore() *LoanContractUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LoanContractUpsertOne) DoNothing() *LoanContractUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LoanContractCreate.OnConflict
// documentation for more info.
func (u *LoanContractUpsertOne) Update(set func(*LoanContractUpsert)) *LoanContractUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LoanContractUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LoanContractUpsertOne) SetUpdatedAt(v time.Time) *LoanContractUpsertOne {
	return u.Update(func(s *LoanContractUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LoanContractUpsertOne) UpdateUpdatedAt() *LoanContractUpsertOne {
	return u.Update(func(s *LoanContractUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetLoanID sets the "loan_id" field.
func (u *LoanContractUpsertOne) SetLoanID(v uuid.UUID) *LoanContractUpsertOne {
	return u.Update(func(s *LoanContractUpsert) {
		s.SetLoanID(v)
	})
}

// UpdateLoanID sets the "loan_id" field to the value that was provided on create.
func (u *LoanContractUpsertOne) UpdateLoanID() *LoanContractUpsertOne {
	return u.Update(func(s *LoanContractUpsert) {
		s.UpdateLoanID()
	})
}

// SetBorrowerID sets the "borrower_id" field.
func (u *LoanContractUpsertOne) SetBorrowerID(v int64) *LoanContractUpsertOne {
	return u.Update(func(s *LoanContractUpsert) {
		s.SetBorrowerID(v)
	})
}

// UpdateBorrowerID sets the "borrower_id" field to the value that was provided on create.
func (u *LoanContractUpsertOne) UpdateBorrowerID() *LoanContractUpsertOne {
	return u.Update(func(s *LoanContractUpsert) {
		s.UpdateBorrowerID()
	})
}

// SetLenderType sets the "lender_type" field.
func (u *LoanContractUpsertOne) SetLenderType(v string) *LoanContractUpsertOne {
	return u.Update(func(s *LoanContractUpsert) {
		s.SetLenderType(v)
	})
}

// UpdateLenderType sets the "lender_type" field to the value that was provided on create.
func (u *LoanContractUpsertOne) UpdateLenderType() *LoanContractUpsertOne {
	return u.Update(func(s *LoanContractUpsert) {
		s.UpdateLenderType()
	})
}

// SetLenderID sets the "lender_id" field.
func (u *LoanContractUpsertOne) SetLenderID(v int64) *LoanContractUpsertOne {
	return u.Update(func(s *LoanContractUpsert) {
		s.SetLenderID(v)
	})
}

// UpdateLenderID sets the "lender_id" field to the value that was provided on create.
func (u *LoanContractUpsertOne) UpdateLenderID() *LoanContractUpsertOne {
	return u.Update(func(s *LoanContractUpsert) {
		s.UpdateLenderID()
	})
}

// ClearLenderID clears the value of the "lender_id" field.
func (u *LoanContractUpsertOne) ClearLenderID() *LoanContractUpsertOne {
	return u.Update(func(s *LoanContractUpsert) {
		s.ClearLenderID()
	})
}

// SetPrincipal sets the "principal" field.
func (u *LoanContractUpsertOne) SetPrincipal(v decimal.Decimal) *LoanContractUpsertOne {
	return u.Update(func(s *LoanContractUpsert) {
		s.SetPrincipal(v)
	})
}

// UpdatePrincipal sets the "principal" field to the value that was provided on create.
func (u *LoanContractUpsertOne) UpdatePrincipal() *LoanContractUpsertOne {
	return u.Update(func(s *LoanContractUpsert) {
		s.UpdatePrincipal()
	})
}

// SetInterestRate sets the "interest_rate" field.
func (u *LoanContractUpsertOne) SetInterestRate(v decimal.Decimal) *LoanContractUpsertOne {
	return u.Update(func(s *LoanContractUpsert) {
		s.SetInterestRate(v)
	})
}

// UpdateInterestRate sets the "interest_rate" field to the value that was provided on create.
func (u *LoanContractUpsertOne) UpdateInterestRate() *LoanContractUpsertOne {
	return u.Update(func(s *LoanContractUpsert) {
		s.UpdateInterestRate()
	})
}

// SetAccruedInterest sets the "accrued_interest" field.
func (u *LoanContractUpsertOne) SetAccruedInterest(v decimal.Decimal) *LoanContractUpsertOne {
	return u.Update(func(s *LoanContractUpsert) {
		s.SetAccruedInterest(v)
	})
}

// UpdateAccruedInterest sets the "accrued_interest" field to the value that was provided on create.
func (u *LoanContractUpsertOne) UpdateAccruedInterest() *LoanContractUpsertOne {
	return u.Update(func(s *LoanContractUpsert) {
		s.UpdateAccruedInterest()
	})
}

// SetRepaidPrincipal sets the "repaid_principal" field.
func (u *LoanContractUpsertOne) SetRepaidPrincipal(v decimal.Decimal) *LoanContractUpsertOne {
	return u.Update(func(s *LoanContractUpsert) {
		s.SetRepaidPrincipal(v)
	})
}

// UpdateRepaidPrincipal sets the "repaid_principal" field to the value that was provided on create.
func (u *LoanContractUpsertOne) UpdateRepaidPrincipal() *LoanContractUpsertOne {
	return u.Update(func(s *LoanContractUpsert) {
		s.UpdateRepaidPrincipal()
	})
}

// SetRepaidInterest sets the "repaid_interest" field.
func (u *LoanContractUpsertOne) SetRepaidInterest(v decimal.Decimal) *LoanContractUpsertOne {
	return u.Update(func(s *LoanContractUpsert) {
		s.SetRepaidInterest(v)
	})
}

// UpdateRepaidInterest sets the "repaid_interest" field to the value that was provided on create.
func (u *LoanContractUpsertOne) UpdateRepaidInterest() *LoanContractUpsertOne {
	return u.Update(func(s *LoanContractUpsert) {
		s.UpdateRepaidInterest()
	})
}

// SetStatus sets the "status" field.
func (u *LoanContractUpsertOne) SetStatus(v string) *LoanContractUpsertOne {
	return u.Update(func(s *LoanContractUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *LoanContractUpsertOne) UpdateStatus() *LoanContractUpsertOne {
	return u.Update(func(s *LoanContractUpsert) {
		s.UpdateStatus()
	})
}

// SetDueDate sets the "due_date" field.
func (u *LoanContractUpsertOne) SetDueDate(v time.Time) *LoanContractUpsertOne {
	return u.Update(func(s *LoanContractUpsert) {
		s.SetDueDate(v)
	})
}

// UpdateDueDate sets the "due_date" field to the value that was provided on create.
func (u *LoanContractUpsertOne) UpdateDueDate() *LoanContractUpsertOne {
	return u.Update(func(s *LoanContractUpsert) {
		s.UpdateDueDate()
	})
}

// Exec executes the query.
func (u *LoanContractUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LoanContractCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LoanContractUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *LoanContractUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *LoanContractUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// LoanContractCreateBulk is the builder for creating many LoanContract entities in bulk.
type LoanContractCreateBulk struct {
	config
	err      error
	builders []*LoanContractCreate
	conflict []sql.ConflictOption
}

// Save creates the LoanContract entities in the database.
func (_c *LoanContractCreateBulk) Save(ctx context.Context) ([]*LoanContract, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LoanContract, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LoanContractMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LoanContractCreateBulk) SaveX(ctx context.Context) []*LoanContract {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LoanContractCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LoanContractCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LoanContract.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LoanContractUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *LoanContractCreateBulk) OnConflict(opts ...sql.ConflictOption) *LoanContractUpsertBulk {
	_c.conflict = opts
	return &LoanContractUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LoanContract.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LoanContractCreateBulk) OnConflictColumns(columns ...string) *LoanContractUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LoanContractUpsertBulk{
		create: _c,
	}
}

// LoanContractUpsertBulk is the builder for "upsert"-ing
// a bulk of LoanContract nodes.
type LoanContractUpsertBulk struct {
	create *LoanContractCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.LoanContract.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LoanContractUpsertBulk) UpdateNewValues() *LoanContractUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(loancontract.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LoanContract.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *LoanContractUpsertBulk) Ignore() *LoanContractUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LoanContractUpsertBulk) DoNothing() *LoanContractUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LoanContractCreateBulk.OnConflict
// documentation for more info.
func (u *LoanContractUpsertBulk) Update(set func(*LoanContractUpsert)) *LoanContractUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LoanContractUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LoanContractUpsertBulk) SetUpdatedAt(v time.Time) *LoanContractUpsertBulk {
	return u.Update(func(s *LoanContractUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LoanContractUpsertBulk) UpdateUpdatedAt() *LoanContractUpsertBulk {
	return u.Update(func(s *LoanContractUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetLoanID sets the "loan_id" field.
func (u *LoanContractUpsertBulk) SetLoanID(v uuid.UUID) *LoanContractUpsertBulk {
	return u.Update(func(s *LoanContractUpsert) {
		s.SetLoanID(v)
	})
}

// UpdateLoanID sets the "loan_id" field to the value that was provided on create.
func (u *LoanContractUpsertBulk) UpdateLoanID() *LoanContractUpsertBulk {
	return u.Update(func(s *LoanContractUpsert) {
		s.UpdateLoanID()
	})
}

// SetBorrowerID sets the "borrower_id" field.
func (u *LoanContractUpsertBulk) SetBorrowerID(v int64) *LoanContractUpsertBulk {
	return u.Update(func(s *LoanContractUpsert) {
		s.SetBorrowerID(v)
	})
}

// UpdateBorrowerID sets the "borrower_id" field to the value that was provided on create.
func (u *LoanContractUpsertBulk) UpdateBorrowerID() *LoanContractUpsertBulk {
	return u.Update(func(s *LoanContractUpsert) {
		s.UpdateBorrowerID()
	})
}

// SetLenderType sets the "lender_type" field.
func (u *LoanContractUpsertBulk) SetLenderType(v string) *LoanContractUpsertBulk {
	return u.Update(func(s *LoanContractUpsert) {
		s.SetLenderType(v)
	})
}

// UpdateLenderType sets the "lender_type" field to the value that was provided on create.
func (u *LoanContractUpsertBulk) UpdateLenderType() *LoanContractUpsertBulk {
	return u.Update(func(s *LoanContractUpsert) {
		s.UpdateLenderType()
	})
}

// SetLenderID sets the "lender_id" field.
func (u *LoanContractUpsertBulk) SetLenderID(v int64) *LoanContractUpsertBulk {
	return u.Update(func(s *LoanContractUpsert) {
		s.SetLenderID(v)
	})
}

// UpdateLenderID sets the "lender_id" field to the value that was provided on create.
func (u *LoanContractUpsertBulk) UpdateLenderID() *LoanContractUpsertBulk {
	return u.Update(func(s *LoanContractUpsert) {
		s.UpdateLenderID()
	})
}

// ClearLenderID clears the value of the "lender_id" field.
func (u *LoanContractUpsertBulk) ClearLenderID() *LoanContractUpsertBulk {
	return u.Update(func(s *LoanContractUpsert) {
		s.ClearLenderID()
	})
}

// SetPrincipal sets the "principal" field.
func (u *LoanContractUpsertBulk) SetPrincipal(v decimal.Decimal) *LoanContractUpsertBulk {
	return u.Update(func(s *LoanContractUpsert) {
		s.SetPrincipal(v)
	})
}

// UpdatePrincipal sets the "principal" field to the value that was provided on create.
func (u *LoanContractUpsertBulk) UpdatePrincipal() *LoanContractUpsertBulk {
	return u.Update(func(s *LoanContractUpsert) {
		s.UpdatePrincipal()
	})
}

// SetInterestRate sets the "interest_rate" field.
func (u *LoanContractUpsertBulk) SetInterestRate(v decimal.Decimal) *LoanContractUpsertBulk {
	return u.Update(func(s *LoanContractUpsert) {
		s.SetInterestRate(v)
	})
}

// UpdateInterestRate sets the "interest_rate" field to the value that was provided on create.
func (u *LoanContractUpsertBulk) UpdateInterestRate() *LoanContractUpsertBulk {
	return u.Update(func(s *LoanContractUpsert) {
		s.UpdateInterestRate()
	})
}

// SetAccruedInterest sets the "accrued_interest" field.
func (u *LoanContractUpsertBulk) SetAccruedInterest(v decimal.Decimal) *LoanContractUpsertBulk {
	return u.Update(func(s *LoanContractUpsert) {
		s.SetAccruedInterest(v)
	})
}

// UpdateAccruedInterest sets the "accrued_interest" field to the value that was provided on create.
func (u *LoanContractUpsertBulk) UpdateAccruedInterest() *LoanContractUpsertBulk {
	return u.Update(func(s *LoanContractUpsert) {
		s.UpdateAccruedInterest()
	})
}

// SetRepaidPrincipal sets the "repaid_principal" field.
func (u *LoanContractUpsertBulk) SetRepaidPrincipal(v decimal.Decimal) *LoanContractUpsertBulk {
	return u.Update(func(s *LoanContractUpsert) {
		s.SetRepaidPrincipal(v)
	})
}

// UpdateRepaidPrincipal sets the "repaid_principal" field to the value that was provided on create.
func (u *LoanContractUpsertBulk) UpdateRepaidPrincipal() *LoanContractUpsertBulk {
	return u.Update(func(s *LoanContractUpsert) {
		s.UpdateRepaidPrincipal()
	})
}

// SetRepaidInterest sets the "repaid_interest" field.
func (u *LoanContractUpsertBulk) SetRepaidInterest(v decimal.Decimal) *LoanContractUpsertBulk {
	return u.Update(func(s *LoanContractUpsert) {
		s.SetRepaidInterest(v)
	})
}

// UpdateRepaidInterest sets the "repaid_interest" field to the value that was provided on create.
func (u *LoanContractUpsertBulk) UpdateRepaidInterest() *LoanContractUpsertBulk {
	return u.Update(func(s *LoanContractUpsert) {
		s.UpdateRepaidInterest()
	})
}

// SetStatus sets the "status" field.
func (u *LoanContractUpsertBulk) SetStatus(v string) *LoanContractUpsertBulk {
	return u.Update(func(s *LoanContractUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *LoanContractUpsertBulk) UpdateStatus() *LoanContractUpsertBulk {
	return u.Update(func(s *LoanContractUpsert) {
		s.UpdateStatus()
	})
}

// SetDueDate sets the "due_date" field.
func (u *LoanContractUpsertBulk) SetDueDate(v time.Time) *LoanContractUpsertBulk {
	return u.Update(func(s *LoanContractUpsert) {
		s.SetDueDate(v)
	})
}

// UpdateDueDate sets the "due_date" field to the value that was provided on create.
func (u *LoanContractUpsertBulk) UpdateDueDate() *LoanContractUpsertBulk {
	return u.Update(func(s *LoanContractUpsert) {
		s.UpdateDueDate()
	})
}

// Exec executes the query.
func (u *LoanContractUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the LoanContractCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LoanContractCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LoanContractUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
