// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/proxysubscriptionnode"
	"github.com/Wei-Shaw/sub2api/ent/proxysubscriptionsource"
)

// ProxySubscriptionNodeUpdate is the builder for updating ProxySubscriptionNode entities.
type ProxySubscriptionNodeUpdate struct {
	config
	hooks    []Hook
	mutation *ProxySubscriptionNodeMutation
}

// Where appends a list predicates to the ProxySubscriptionNodeUpdate builder.
func (_u *ProxySubscriptionNodeUpdate) Where(ps ...predicate.ProxySubscriptionNode) *ProxySubscriptionNodeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProxySubscriptionNodeUpdate) SetUpdatedAt(v time.Time) *ProxySubscriptionNodeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ProxySubscriptionNodeUpdate) SetDeletedAt(v time.Time) *ProxySubscriptionNodeUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ProxySubscriptionNodeUpdate) SetNillableDeletedAt(v *time.Time) *ProxySubscriptionNodeUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ProxySubscriptionNodeUpdate) ClearDeletedAt() *ProxySubscriptionNodeUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetSourceID sets the "source_id" field.
func (_u *ProxySubscriptionNodeUpdate) SetSourceID(v int64) *ProxySubscriptionNodeUpdate {
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *ProxySubscriptionNodeUpdate) SetNillableSourceID(v *int64) *ProxySubscriptionNodeUpdate {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// SetNodeKey sets the "node_key" field.
func (_u *ProxySubscriptionNodeUpdate) SetNodeKey(v string) *ProxySubscriptionNodeUpdate {
	_u.mutation.SetNodeKey(v)
	return _u
}

// SetNillableNodeKey sets the "node_key" field if the given value is not nil.
func (_u *ProxySubscriptionNodeUpdate) SetNillableNodeKey(v *string) *ProxySubscriptionNodeUpdate {
	if v != nil {
		_u.SetNodeKey(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *ProxySubscriptionNodeUpdate) SetDisplayName(v string) *ProxySubscriptionNodeUpdate {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *ProxySubscriptionNodeUpdate) SetNillableDisplayName(v *string) *ProxySubscriptionNodeUpdate {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// ClearDisplayName clears the value of the "display_name" field.
func (_u *ProxySubscriptionNodeUpdate) ClearDisplayName() *ProxySubscriptionNodeUpdate {
	_u.mutation.ClearDisplayName()
	return _u
}

// SetNodeType sets the "node_type" field.
func (_u *ProxySubscriptionNodeUpdate) SetNodeType(v string) *ProxySubscriptionNodeUpdate {
	_u.mutation.SetNodeType(v)
	return _u
}

// SetNillableNodeType sets the "node_type" field if the given value is not nil.
func (_u *ProxySubscriptionNodeUpdate) SetNillableNodeType(v *string) *ProxySubscriptionNodeUpdate {
	if v != nil {
		_u.SetNodeType(*v)
	}
	return _u
}

// SetServer sets the "server" field.
func (_u *ProxySubscriptionNodeUpdate) SetServer(v string) *ProxySubscriptionNodeUpdate {
	_u.mutation.SetServer(v)
	return _u
}

// SetNillableServer sets the "server" field if the given value is not nil.
func (_u *ProxySubscriptionNodeUpdate) SetNillableServer(v *string) *ProxySubscriptionNodeUpdate {
	if v != nil {
		_u.SetServer(*v)
	}
	return _u
}

// SetPort sets the "port" field.
func (_u *ProxySubscriptionNodeUpdate) SetPort(v int) *ProxySubscriptionNodeUpdate {
	_u.mutation.ResetPort()
	_u.mutation.SetPort(v)
	return _u
}

// SetNillablePort sets the "port" field if the given value is not nil.
func (_u *ProxySubscriptionNodeUpdate) SetNillablePort(v *int) *ProxySubscriptionNodeUpdate {
	if v != nil {
		_u.SetPort(*v)
	}
	return _u
}

// AddPort adds value to the "port" field.
func (_u *ProxySubscriptionNodeUpdate) AddPort(v int) *ProxySubscriptionNodeUpdate {
	_u.mutation.AddPort(v)
	return _u
}

// SetConfigJSON sets the "config_json" field.
func (_u *ProxySubscriptionNodeUpdate) SetConfigJSON(v map[string]interface{}) *ProxySubscriptionNodeUpdate {
	_u.mutation.SetConfigJSON(v)
	return _u
}

// ClearConfigJSON clears the value of the "config_json" field.
func (_u *ProxySubscriptionNodeUpdate) ClearConfigJSON() *ProxySubscriptionNodeUpdate {
	_u.mutation.ClearConfigJSON()
	return _u
}

// SetLandingStatus sets the "landing_status" field.
func (_u *ProxySubscriptionNodeUpdate) SetLandingStatus(v string) *ProxySubscriptionNodeUpdate {
	_u.mutation.SetLandingStatus(v)
	return _u
}

// SetNillableLandingStatus sets the "landing_status" field if the given value is not nil.
func (_u *ProxySubscriptionNodeUpdate) SetNillableLandingStatus(v *string) *ProxySubscriptionNodeUpdate {
	if v != nil {
		_u.SetLandingStatus(*v)
	}
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *ProxySubscriptionNodeUpdate) SetLastError(v string) *ProxySubscriptionNodeUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *ProxySubscriptionNodeUpdate) SetNillableLastError(v *string) *ProxySubscriptionNodeUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *ProxySubscriptionNodeUpdate) ClearLastError() *ProxySubscriptionNodeUpdate {
	_u.mutation.ClearLastError()
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *ProxySubscriptionNodeUpdate) SetLastSeenAt(v time.Time) *ProxySubscriptionNodeUpdate {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *ProxySubscriptionNodeUpdate) SetNillableLastSeenAt(v *time.Time) *ProxySubscriptionNodeUpdate {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// SetSource sets the "source" edge to the ProxySubscriptionSource entity.
func (_u *ProxySubscriptionNodeUpdate) SetSource(v *ProxySubscriptionSource) *ProxySubscriptionNodeUpdate {
	return _u.SetSourceID(v.ID)
}

// Mutation returns the ProxySubscriptionNodeMutation object of the builder.
func (_u *ProxySubscriptionNodeUpdate) Mutation() *ProxySubscriptionNodeMutation {
	return _u.mutation
}

// ClearSource clears the "source" edge to the ProxySubscriptionSource entity.
func (_u *ProxySubscriptionNodeUpdate) ClearSource() *ProxySubscriptionNodeUpdate {
	_u.mutation.ClearSource()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProxySubscriptionNodeUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProxySubscriptionNodeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProxySubscriptionNodeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProxySubscriptionNodeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProxySubscriptionNodeUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if proxysubscriptionnode.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized proxysubscriptionnode.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := proxysubscriptionnode.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProxySubscriptionNodeUpdate) check() error {
	if v, ok := _u.mutation.NodeKey(); ok {
		if err := proxysubscriptionnode.NodeKeyValidator(v); err != nil {
			return &ValidationError{Name: "node_key", err: fmt.Errorf(`ent: validator failed for field "ProxySubscriptionNode.node_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := proxysubscriptionnode.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "ProxySubscriptionNode.display_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NodeType(); ok {
		if err := proxysubscriptionnode.NodeTypeValidator(v); err != nil {
			return &ValidationError{Name: "node_type", err: fmt.Errorf(`ent: validator failed for field "ProxySubscriptionNode.node_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Server(); ok {
		if err := proxysubscriptionnode.ServerValidator(v); err != nil {
			return &ValidationError{Name: "server", err: fmt.Errorf(`ent: validator failed for field "ProxySubscriptionNode.server": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LandingStatus(); ok {
		if err := proxysubscriptionnode.LandingStatusValidator(v); err != nil {
			return &ValidationError{Name: "landing_status", err: fmt.Errorf(`ent: validator failed for field "ProxySubscriptionNode.landing_status": %w`, err)}
		}
	}
	if _u.mutation.SourceCleared() && len(_u.mutation.SourceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProxySubscriptionNode.source"`)
	}
	return nil
}

func (_u *ProxySubscriptionNodeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(proxysubscriptionnode.Table, proxysubscriptionnode.Columns, sqlgraph.NewFieldSpec(proxysubscriptionnode.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(proxysubscriptionnode.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(proxysubscriptionnode.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(proxysubscriptionnode.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.NodeKey(); ok {
		_spec.SetField(proxysubscriptionnode.FieldNodeKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(proxysubscriptionnode.FieldDisplayName, field.TypeString, value)
	}
	if _u.mutation.DisplayNameCleared() {
		_spec.ClearField(proxysubscriptionnode.FieldDisplayName, field.TypeString)
	}
	if value, ok := _u.mutation.NodeType(); ok {
		_spec.SetField(proxysubscriptionnode.FieldNodeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Server(); ok {
		_spec.SetField(proxysubscriptionnode.FieldServer, field.TypeString, value)
	}
	if value, ok := _u.mutation.Port(); ok {
		_spec.SetField(proxysubscriptionnode.FieldPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPort(); ok {
		_spec.AddField(proxysubscriptionnode.FieldPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ConfigJSON(); ok {
		_spec.SetField(proxysubscriptionnode.FieldConfigJSON, field.TypeJSON, value)
	}
	if _u.mutation.ConfigJSONCleared() {
		_spec.ClearField(proxysubscriptionnode.FieldConfigJSON, field.TypeJSON)
	}
	if value, ok := _u.mutation.LandingStatus(); ok {
		_spec.SetField(proxysubscriptionnode.FieldLandingStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(proxysubscriptionnode.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(proxysubscriptionnode.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(proxysubscriptionnode.FieldLastSeenAt, field.TypeTime, value)
	}
	if _u.mutation.SourceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   proxysubscriptionnode.SourceTable,
			Columns: []string{proxysubscriptionnode.SourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxysubscriptionsource.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SourceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   proxysubscriptionnode.SourceTable,
			Columns: []string{proxysubscriptionnode.SourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxysubscriptionsource.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{proxysubscriptionnode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProxySubscriptionNodeUpdateOne is the builder for updating a single ProxySubscriptionNode entity.
type ProxySubscriptionNodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProxySubscriptionNodeMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProxySubscriptionNodeUpdateOne) SetUpdatedAt(v time.Time) *ProxySubscriptionNodeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ProxySubscriptionNodeUpdateOne) SetDeletedAt(v time.Time) *ProxySubscriptionNodeUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ProxySubscriptionNodeUpdateOne) SetNillableDeletedAt(v *time.Time) *ProxySubscriptionNodeUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ProxySubscriptionNodeUpdateOne) ClearDeletedAt() *ProxySubscriptionNodeUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetSourceID sets the "source_id" field.
func (_u *ProxySubscriptionNodeUpdateOne) SetSourceID(v int64) *ProxySubscriptionNodeUpdateOne {
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *ProxySubscriptionNodeUpdateOne) SetNillableSourceID(v *int64) *ProxySubscriptionNodeUpdateOne {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// SetNodeKey sets the "node_key" field.
func (_u *ProxySubscriptionNodeUpdateOne) SetNodeKey(v string) *ProxySubscriptionNodeUpdateOne {
	_u.mutation.SetNodeKey(v)
	return _u
}

// SetNillableNodeKey sets the "node_key" field if the given value is not nil.
func (_u *ProxySubscriptionNodeUpdateOne) SetNillableNodeKey(v *string) *ProxySubscriptionNodeUpdateOne {
	if v != nil {
		_u.SetNodeKey(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *ProxySubscriptionNodeUpdateOne) SetDisplayName(v string) *ProxySubscriptionNodeUpdateOne {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *ProxySubscriptionNodeUpdateOne) SetNillableDisplayName(v *string) *ProxySubscriptionNodeUpdateOne {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// ClearDisplayName clears the value of the "display_name" field.
func (_u *ProxySubscriptionNodeUpdateOne) ClearDisplayName() *ProxySubscriptionNodeUpdateOne {
	_u.mutation.ClearDisplayName()
	return _u
}

// SetNodeType sets the "node_type" field.
func (_u *ProxySubscriptionNodeUpdateOne) SetNodeType(v string) *ProxySubscriptionNodeUpdateOne {
	_u.mutation.SetNodeType(v)
	return _u
}

// SetNillableNodeType sets the "node_type" field if the given value is not nil.
func (_u *ProxySubscriptionNodeUpdateOne) SetNillableNodeType(v *string) *ProxySubscriptionNodeUpdateOne {
	if v != nil {
		_u.SetNodeType(*v)
	}
	return _u
}

// SetServer sets the "server" field.
func (_u *ProxySubscriptionNodeUpdateOne) SetServer(v string) *ProxySubscriptionNodeUpdateOne {
	_u.mutation.SetServer(v)
	return _u
}

// SetNillableServer sets the "server" field if the given value is not nil.
func (_u *ProxySubscriptionNodeUpdateOne) SetNillableServer(v *string) *ProxySubscriptionNodeUpdateOne {
	if v != nil {
		_u.SetServer(*v)
	}
	return _u
}

// SetPort sets the "port" field.
func (_u *ProxySubscriptionNodeUpdateOne) SetPort(v int) *ProxySubscriptionNodeUpdateOne {
	_u.mutation.ResetPort()
	_u.mutation.SetPort(v)
	return _u
}

// SetNillablePort sets the "port" field if the given value is not nil.
func (_u *ProxySubscriptionNodeUpdateOne) SetNillablePort(v *int) *ProxySubscriptionNodeUpdateOne {
	if v != nil {
		_u.SetPort(*v)
	}
	return _u
}

// AddPort adds value to the "port" field.
func (_u *ProxySubscriptionNodeUpdateOne) AddPort(v int) *ProxySubscriptionNodeUpdateOne {
	_u.mutation.AddPort(v)
	return _u
}

// SetConfigJSON sets the "config_json" field.
func (_u *ProxySubscriptionNodeUpdateOne) SetConfigJSON(v map[string]interface{}) *ProxySubscriptionNodeUpdateOne {
	_u.mutation.SetConfigJSON(v)
	return _u
}

// ClearConfigJSON clears the value of the "config_json" field.
func (_u *ProxySubscriptionNodeUpdateOne) ClearConfigJSON() *ProxySubscriptionNodeUpdateOne {
	_u.mutation.ClearConfigJSON()
	return _u
}

// SetLandingStatus sets the "landing_status" field.
func (_u *ProxySubscriptionNodeUpdateOne) SetLandingStatus(v string) *ProxySubscriptionNodeUpdateOne {
	_u.mutation.SetLandingStatus(v)
	return _u
}

// SetNillableLandingStatus sets the "landing_status" field if the given value is not nil.
func (_u *ProxySubscriptionNodeUpdateOne) SetNillableLandingStatus(v *string) *ProxySubscriptionNodeUpdateOne {
	if v != nil {
		_u.SetLandingStatus(*v)
	}
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *ProxySubscriptionNodeUpdateOne) SetLastError(v string) *ProxySubscriptionNodeUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *ProxySubscriptionNodeUpdateOne) SetNillableLastError(v *string) *ProxySubscriptionNodeUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *ProxySubscriptionNodeUpdateOne) ClearLastError() *ProxySubscriptionNodeUpdateOne {
	_u.mutation.ClearLastError()
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *ProxySubscriptionNodeUpdateOne) SetLastSeenAt(v time.Time) *ProxySubscriptionNodeUpdateOne {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *ProxySubscriptionNodeUpdateOne) SetNillableLastSeenAt(v *time.Time) *ProxySubscriptionNodeUpdateOne {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// SetSource sets the "source" edge to the ProxySubscriptionSource entity.
func (_u *ProxySubscriptionNodeUpdateOne) SetSource(v *ProxySubscriptionSource) *ProxySubscriptionNodeUpdateOne {
	return _u.SetSourceID(v.ID)
}

// Mutation returns the ProxySubscriptionNodeMutation object of the builder.
func (_u *ProxySubscriptionNodeUpdateOne) Mutation() *ProxySubscriptionNodeMutation {
	return _u.mutation
}

// ClearSource clears the "source" edge to the ProxySubscriptionSource entity.
func (_u *ProxySubscriptionNodeUpdateOne) ClearSource() *ProxySubscriptionNodeUpdateOne {
	_u.mutation.ClearSource()
	return _u
}

// Where appends a list predicates to the ProxySubscriptionNodeUpdate builder.
func (_u *ProxySubscriptionNodeUpdateOne) Where(ps ...predicate.ProxySubscriptionNode) *ProxySubscriptionNodeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProxySubscriptionNodeUpdateOne) Select(field string, fields ...string) *ProxySubscriptionNodeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProxySubscriptionNode entity.
func (_u *ProxySubscriptionNodeUpdateOne) Save(ctx context.Context) (*ProxySubscriptionNode, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProxySubscriptionNodeUpdateOne) SaveX(ctx context.Context) *ProxySubscriptionNode {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProxySubscriptionNodeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProxySubscriptionNodeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProxySubscriptionNodeUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if proxysubscriptionnode.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized proxysubscriptionnode.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := proxysubscriptionnode.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProxySubscriptionNodeUpdateOne) check() error {
	if v, ok := _u.mutation.NodeKey(); ok {
		if err := proxysubscriptionnode.NodeKeyValidator(v); err != nil {
			return &ValidationError{Name: "node_key", err: fmt.Errorf(`ent: validator failed for field "ProxySubscriptionNode.node_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := proxysubscriptionnode.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "ProxySubscriptionNode.display_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NodeType(); ok {
		if err := proxysubscriptionnode.NodeTypeValidator(v); err != nil {
			return &ValidationError{Name: "node_type", err: fmt.Errorf(`ent: validator failed for field "ProxySubscriptionNode.node_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Server(); ok {
		if err := proxysubscriptionnode.ServerValidator(v); err != nil {
			return &ValidationError{Name: "server", err: fmt.Errorf(`ent: validator failed for field "ProxySubscriptionNode.server": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LandingStatus(); ok {
		if err := proxysubscriptionnode.LandingStatusValidator(v); err != nil {
			return &ValidationError{Name: "landing_status", err: fmt.Errorf(`ent: validator failed for field "ProxySubscriptionNode.landing_status": %w`, err)}
		}
	}
	if _u.mutation.SourceCleared() && len(_u.mutation.SourceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProxySubscriptionNode.source"`)
	}
	return nil
}

func (_u *ProxySubscriptionNodeUpdateOne) sqlSave(ctx context.Context) (_node *ProxySubscriptionNode, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(proxysubscriptionnode.Table, proxysubscriptionnode.Columns, sqlgraph.NewFieldSpec(proxysubscriptionnode.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProxySubscriptionNode.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, proxysubscriptionnode.FieldID)
		for _, f := range fields {
			if !proxysubscriptionnode.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != proxysubscriptionnode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(proxysubscriptionnode.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(proxysubscriptionnode.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(proxysubscriptionnode.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.NodeKey(); ok {
		_spec.SetField(proxysubscriptionnode.FieldNodeKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(proxysubscriptionnode.FieldDisplayName, field.TypeString, value)
	}
	if _u.mutation.DisplayNameCleared() {
		_spec.ClearField(proxysubscriptionnode.FieldDisplayName, field.TypeString)
	}
	if value, ok := _u.mutation.NodeType(); ok {
		_spec.SetField(proxysubscriptionnode.FieldNodeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Server(); ok {
		_spec.SetField(proxysubscriptionnode.FieldServer, field.TypeString, value)
	}
	if value, ok := _u.mutation.Port(); ok {
		_spec.SetField(proxysubscriptionnode.FieldPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPort(); ok {
		_spec.AddField(proxysubscriptionnode.FieldPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ConfigJSON(); ok {
		_spec.SetField(proxysubscriptionnode.FieldConfigJSON, field.TypeJSON, value)
	}
	if _u.mutation.ConfigJSONCleared() {
		_spec.ClearField(proxysubscriptionnode.FieldConfigJSON, field.TypeJSON)
	}
	if value, ok := _u.mutation.LandingStatus(); ok {
		_spec.SetField(proxysubscriptionnode.FieldLandingStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(proxysubscriptionnode.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(proxysubscriptionnode.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(proxysubscriptionnode.FieldLastSeenAt, field.TypeTime, value)
	}
	if _u.mutation.SourceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   proxysubscriptionnode.SourceTable,
			Columns: []string{proxysubscriptionnode.SourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxysubscriptionsource.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SourceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   proxysubscriptionnode.SourceTable,
			Columns: []string{proxysubscriptionnode.SourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxysubscriptionsource.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ProxySubscriptionNode{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{proxysubscriptionnode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
