// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/proxysubscriptionnode"
	"github.com/Wei-Shaw/sub2api/ent/proxysubscriptionsource"
)

// ProxySubscriptionNode is the model entity for the ProxySubscriptionNode schema.
type ProxySubscriptionNode struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// SourceID holds the value of the "source_id" field.
	SourceID int64 `json:"source_id,omitempty"`
	// NodeKey holds the value of the "node_key" field.
	NodeKey string `json:"node_key,omitempty"`
	// DisplayName holds the value of the "display_name" field.
	DisplayName *string `json:"display_name,omitempty"`
	// NodeType holds the value of the "node_type" field.
	NodeType string `json:"node_type,omitempty"`
	// Server holds the value of the "server" field.
	Server string `json:"server,omitempty"`
	// Port holds the value of the "port" field.
	Port int `json:"port,omitempty"`
	// ConfigJSON holds the value of the "config_json" field.
	ConfigJSON map[string]interface{} `json:"config_json,omitempty"`
	// LandingStatus holds the value of the "landing_status" field.
	LandingStatus string `json:"landing_status,omitempty"`
	// LastError holds the value of the "last_error" field.
	LastError *string `json:"last_error,omitempty"`
	// LastSeenAt holds the value of the "last_seen_at" field.
	LastSeenAt time.Time `json:"last_seen_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProxySubscriptionNodeQuery when eager-loading is set.
	Edges        ProxySubscriptionNodeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ProxySubscriptionNodeEdges holds the relations/edges for other nodes in the graph.
type ProxySubscriptionNodeEdges struct {
	// Source holds the value of the source edge.
	Source *ProxySubscriptionSource `json:"source,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SourceOrErr returns the Source value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProxySubscriptionNodeEdges) SourceOrErr() (*ProxySubscriptionSource, error) {
	if e.Source != nil {
		return e.Source, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: proxysubscriptionsource.Label}
	}
	return nil, &NotLoadedError{edge: "source"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProxySubscriptionNode) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case proxysubscriptionnode.FieldConfigJSON:
			values[i] = new([]byte)
		case proxysubscriptionnode.FieldID, proxysubscriptionnode.FieldSourceID, proxysubscriptionnode.FieldPort:
			values[i] = new(sql.NullInt64)
		case proxysubscriptionnode.FieldNodeKey, proxysubscriptionnode.FieldDisplayName, proxysubscriptionnode.FieldNodeType, proxysubscriptionnode.FieldServer, proxysubscriptionnode.FieldLandingStatus, proxysubscriptionnode.FieldLastError:
			values[i] = new(sql.NullString)
		case proxysubscriptionnode.FieldCreatedAt, proxysubscriptionnode.FieldUpdatedAt, proxysubscriptionnode.FieldDeletedAt, proxysubscriptionnode.FieldLastSeenAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProxySubscriptionNode fields.
func (_m *ProxySubscriptionNode) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case proxysubscriptionnode.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case proxysubscriptionnode.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case proxysubscriptionnode.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case proxysubscriptionnode.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case proxysubscriptionnode.FieldSourceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field source_id", values[i])
			} else if value.Valid {
				_m.SourceID = value.Int64
			}
		case proxysubscriptionnode.FieldNodeKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field node_key", values[i])
			} else if value.Valid {
				_m.NodeKey = value.String
			}
		case proxysubscriptionnode.FieldDisplayName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field display_name", values[i])
			} else if value.Valid {
				_m.DisplayName = new(string)
				*_m.DisplayName = value.String
			}
		case proxysubscriptionnode.FieldNodeType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field node_type", values[i])
			} else if value.Valid {
				_m.NodeType = value.String
			}
		case proxysubscriptionnode.FieldServer:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field server", values[i])
			} else if value.Valid {
				_m.Server = value.String
			}
		case proxysubscriptionnode.FieldPort:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field port", values[i])
			} else if value.Valid {
				_m.Port = int(value.Int64)
			}
		case proxysubscriptionnode.FieldConfigJSON:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field config_json", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ConfigJSON); err != nil {
					return fmt.Errorf("unmarshal field config_json: %w", err)
				}
			}
		case proxysubscriptionnode.FieldLandingStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field landing_status", values[i])
			} else if value.Valid {
				_m.LandingStatus = value.String
			}
		case proxysubscriptionnode.FieldLastError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error", values[i])
			} else if value.Valid {
				_m.LastError = new(string)
				*_m.LastError = value.String
			}
		case proxysubscriptionnode.FieldLastSeenAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_seen_at", values[i])
			} else if value.Valid {
				_m.LastSeenAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProxySubscriptionNode.
// This includes values selected through modifiers, order, etc.
func (_m *ProxySubscriptionNode) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySource queries the "source" edge of the ProxySubscriptionNode entity.
func (_m *ProxySubscriptionNode) QuerySource() *ProxySubscriptionSourceQuery {
	return NewProxySubscriptionNodeClient(_m.config).QuerySource(_m)
}

// Update returns a builder for updating this ProxySubscriptionNode.
// Note that you need to call ProxySubscriptionNode.Unwrap() before calling this method if this ProxySubscriptionNode
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProxySubscriptionNode) Update() *ProxySubscriptionNodeUpdateOne {
	return NewProxySubscriptionNodeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProxySubscriptionNode entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProxySubscriptionNode) Unwrap() *ProxySubscriptionNode {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProxySubscriptionNode is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProxySubscriptionNode) String() string {
	var builder strings.Builder
	builder.WriteString("ProxySubscriptionNode(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("source_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SourceID))
	builder.WriteString(", ")
	builder.WriteString("node_key=")
	builder.WriteString(_m.NodeKey)
	builder.WriteString(", ")
	if v := _m.DisplayName; v != nil {
		builder.WriteString("display_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("node_type=")
	builder.WriteString(_m.NodeType)
	builder.WriteString(", ")
	builder.WriteString("server=")
	builder.WriteString(_m.Server)
	builder.WriteString(", ")
	builder.WriteString("port=")
	builder.WriteString(fmt.Sprintf("%v", _m.Port))
	builder.WriteString(", ")
	builder.WriteString("config_json=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConfigJSON))
	builder.WriteString(", ")
	builder.WriteString("landing_status=")
	builder.WriteString(_m.LandingStatus)
	builder.WriteString(", ")
	if v := _m.LastError; v != nil {
		builder.WriteString("last_error=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("last_seen_at=")
	builder.WriteString(_m.LastSeenAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ProxySubscriptionNodes is a parsable slice of ProxySubscriptionNode.
type ProxySubscriptionNodes []*ProxySubscriptionNode
