// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/proxysubscriptionnode"
	"github.com/Wei-Shaw/sub2api/ent/proxysubscriptionsource"
)

// ProxySubscriptionSourceCreate is the builder for creating a ProxySubscriptionSource entity.
type ProxySubscriptionSourceCreate struct {
	config
	mutation *ProxySubscriptionSourceMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProxySubscriptionSourceCreate) SetCreatedAt(v time.Time) *ProxySubscriptionSourceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProxySubscriptionSourceCreate) SetNillableCreatedAt(v *time.Time) *ProxySubscriptionSourceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ProxySubscriptionSourceCreate) SetUpdatedAt(v time.Time) *ProxySubscriptionSourceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ProxySubscriptionSourceCreate) SetNillableUpdatedAt(v *time.Time) *ProxySubscriptionSourceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *ProxySubscriptionSourceCreate) SetDeletedAt(v time.Time) *ProxySubscriptionSourceCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *ProxySubscriptionSourceCreate) SetNillableDeletedAt(v *time.Time) *ProxySubscriptionSourceCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *ProxySubscriptionSourceCreate) SetName(v string) *ProxySubscriptionSourceCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetURL sets the "url" field.
func (_c *ProxySubscriptionSourceCreate) SetURL(v string) *ProxySubscriptionSourceCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetSourceFormat sets the "source_format" field.
func (_c *ProxySubscriptionSourceCreate) SetSourceFormat(v string) *ProxySubscriptionSourceCreate {
	_c.mutation.SetSourceFormat(v)
	return _c
}

// SetNillableSourceFormat sets the "source_format" field if the given value is not nil.
func (_c *ProxySubscriptionSourceCreate) SetNillableSourceFormat(v *string) *ProxySubscriptionSourceCreate {
	if v != nil {
		_c.SetSourceFormat(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *ProxySubscriptionSourceCreate) SetEnabled(v bool) *ProxySubscriptionSourceCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *ProxySubscriptionSourceCreate) SetNillableEnabled(v *bool) *ProxySubscriptionSourceCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetRefreshIntervalHours sets the "refresh_interval_hours" field.
func (_c *ProxySubscriptionSourceCreate) SetRefreshIntervalHours(v int) *ProxySubscriptionSourceCreate {
	_c.mutation.SetRefreshIntervalHours(v)
	return _c
}

// SetNillableRefreshIntervalHours sets the "refresh_interval_hours" field if the given value is not nil.
func (_c *ProxySubscriptionSourceCreate) SetNillableRefreshIntervalHours(v *int) *ProxySubscriptionSourceCreate {
	if v != nil {
		_c.SetRefreshIntervalHours(*v)
	}
	return _c
}

// SetTargetEntryCount sets the "target_entry_count" field.
func (_c *ProxySubscriptionSourceCreate) SetTargetEntryCount(v int) *ProxySubscriptionSourceCreate {
	_c.mutation.SetTargetEntryCount(v)
	return _c
}

// SetNillableTargetEntryCount sets the "target_entry_count" field if the given value is not nil.
func (_c *ProxySubscriptionSourceCreate) SetNillableTargetEntryCount(v *int) *ProxySubscriptionSourceCreate {
	if v != nil {
		_c.SetTargetEntryCount(*v)
	}
	return _c
}

// SetAutoAddToPool sets the "auto_add_to_pool" field.
func (_c *ProxySubscriptionSourceCreate) SetAutoAddToPool(v bool) *ProxySubscriptionSourceCreate {
	_c.mutation.SetAutoAddToPool(v)
	return _c
}

// SetNillableAutoAddToPool sets the "auto_add_to_pool" field if the given value is not nil.
func (_c *ProxySubscriptionSourceCreate) SetNillableAutoAddToPool(v *bool) *ProxySubscriptionSourceCreate {
	if v != nil {
		_c.SetAutoAddToPool(*v)
	}
	return _c
}

// SetLastRefreshedAt sets the "last_refreshed_at" field.
func (_c *ProxySubscriptionSourceCreate) SetLastRefreshedAt(v time.Time) *ProxySubscriptionSourceCreate {
	_c.mutation.SetLastRefreshedAt(v)
	return _c
}

// SetNillableLastRefreshedAt sets the "last_refreshed_at" field if the given value is not nil.
func (_c *ProxySubscriptionSourceCreate) SetNillableLastRefreshedAt(v *time.Time) *ProxySubscriptionSourceCreate {
	if v != nil {
		_c.SetLastRefreshedAt(*v)
	}
	return _c
}

// SetLastSuccessAt sets the "last_success_at" field.
func (_c *ProxySubscriptionSourceCreate) SetLastSuccessAt(v time.Time) *ProxySubscriptionSourceCreate {
	_c.mutation.SetLastSuccessAt(v)
	return _c
}

// SetNillableLastSuccessAt sets the "last_success_at" field if the given value is not nil.
func (_c *ProxySubscriptionSourceCreate) SetNillableLastSuccessAt(v *time.Time) *ProxySubscriptionSourceCreate {
	if v != nil {
		_c.SetLastSuccessAt(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *ProxySubscriptionSourceCreate) SetLastError(v string) *ProxySubscriptionSourceCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *ProxySubscriptionSourceCreate) SetNillableLastError(v *string) *ProxySubscriptionSourceCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// SetLastNodeCount sets the "last_node_count" field.
func (_c *ProxySubscriptionSourceCreate) SetLastNodeCount(v int) *ProxySubscriptionSourceCreate {
	_c.mutation.SetLastNodeCount(v)
	return _c
}

// SetNillableLastNodeCount sets the "last_node_count" field if the given value is not nil.
func (_c *ProxySubscriptionSourceCreate) SetNillableLastNodeCount(v *int) *ProxySubscriptionSourceCreate {
	if v != nil {
		_c.SetLastNodeCount(*v)
	}
	return _c
}

// SetLastMaterializedProxyCount sets the "last_materialized_proxy_count" field.
func (_c *ProxySubscriptionSourceCreate) SetLastMaterializedProxyCount(v int) *ProxySubscriptionSourceCreate {
	_c.mutation.SetLastMaterializedProxyCount(v)
	return _c
}

// SetNillableLastMaterializedProxyCount sets the "last_materialized_proxy_count" field if the given value is not nil.
func (_c *ProxySubscriptionSourceCreate) SetNillableLastMaterializedProxyCount(v *int) *ProxySubscriptionSourceCreate {
	if v != nil {
		_c.SetLastMaterializedProxyCount(*v)
	}
	return _c
}

// AddNodeIDs adds the "nodes" edge to the ProxySubscriptionNode entity by IDs.
func (_c *ProxySubscriptionSourceCreate) AddNodeIDs(ids ...int64) *ProxySubscriptionSourceCreate {
	_c.mutation.AddNodeIDs(ids...)
	return _c
}

// AddNodes adds the "nodes" edges to the ProxySubscriptionNode entity.
func (_c *ProxySubscriptionSourceCreate) AddNodes(v ...*ProxySubscriptionNode) *ProxySubscriptionSourceCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddNodeIDs(ids...)
}

// Mutation returns the ProxySubscriptionSourceMutation object of the builder.
func (_c *ProxySubscriptionSourceCreate) Mutation() *ProxySubscriptionSourceMutation {
	return _c.mutation
}

// Save creates the ProxySubscriptionSource in the database.
func (_c *ProxySubscriptionSourceCreate) Save(ctx context.Context) (*ProxySubscriptionSource, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProxySubscriptionSourceCreate) SaveX(ctx context.Context) *ProxySubscriptionSource {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProxySubscriptionSourceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProxySubscriptionSourceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProxySubscriptionSourceCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if proxysubscriptionsource.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized proxysubscriptionsource.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := proxysubscriptionsource.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if proxysubscriptionsource.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized proxysubscriptionsource.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := proxysubscriptionsource.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.SourceFormat(); !ok {
		v := proxysubscriptionsource.DefaultSourceFormat
		_c.mutation.SetSourceFormat(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := proxysubscriptionsource.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.RefreshIntervalHours(); !ok {
		v := proxysubscriptionsource.DefaultRefreshIntervalHours
		_c.mutation.SetRefreshIntervalHours(v)
	}
	if _, ok := _c.mutation.TargetEntryCount(); !ok {
		v := proxysubscriptionsource.DefaultTargetEntryCount
		_c.mutation.SetTargetEntryCount(v)
	}
	if _, ok := _c.mutation.AutoAddToPool(); !ok {
		v := proxysubscriptionsource.DefaultAutoAddToPool
		_c.mutation.SetAutoAddToPool(v)
	}
	if _, ok := _c.mutation.LastNodeCount(); !ok {
		v := proxysubscriptionsource.DefaultLastNodeCount
		_c.mutation.SetLastNodeCount(v)
	}
	if _, ok := _c.mutation.LastMaterializedProxyCount(); !ok {
		v := proxysubscriptionsource.DefaultLastMaterializedProxyCount
		_c.mutation.SetLastMaterializedProxyCount(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProxySubscriptionSourceCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ProxySubscriptionSource.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ProxySubscriptionSource.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ProxySubscriptionSource.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := proxysubscriptionsource.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ProxySubscriptionSource.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "ProxySubscriptionSource.url"`)}
	}
	if v, ok := _c.mutation.URL(); ok {
		if err := proxysubscriptionsource.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "ProxySubscriptionSource.url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SourceFormat(); !ok {
		return &ValidationError{Name: "source_format", err: errors.New(`ent: missing required field "ProxySubscriptionSource.source_format"`)}
	}
	if v, ok := _c.mutation.SourceFormat(); ok {
		if err := proxysubscriptionsource.SourceFormatValidator(v); err != nil {
			return &ValidationError{Name: "source_format", err: fmt.Errorf(`ent: validator failed for field "ProxySubscriptionSource.source_format": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "ProxySubscriptionSource.enabled"`)}
	}
	if _, ok := _c.mutation.RefreshIntervalHours(); !ok {
		return &ValidationError{Name: "refresh_interval_hours", err: errors.New(`ent: missing required field "ProxySubscriptionSource.refresh_interval_hours"`)}
	}
	if _, ok := _c.mutation.TargetEntryCount(); !ok {
		return &ValidationError{Name: "target_entry_count", err: errors.New(`ent: missing required field "ProxySubscriptionSource.target_entry_count"`)}
	}
	if _, ok := _c.mutation.AutoAddToPool(); !ok {
		return &ValidationError{Name: "auto_add_to_pool", err: errors.New(`ent: missing required field "ProxySubscriptionSource.auto_add_to_pool"`)}
	}
	if _, ok := _c.mutation.LastNodeCount(); !ok {
		return &ValidationError{Name: "last_node_count", err: errors.New(`ent: missing required field "ProxySubscriptionSource.last_node_count"`)}
	}
	if _, ok := _c.mutation.LastMaterializedProxyCount(); !ok {
		return &ValidationError{Name: "last_materialized_proxy_count", err: errors.New(`ent: missing required field "ProxySubscriptionSource.last_materialized_proxy_count"`)}
	}
	return nil
}

func (_c *ProxySubscriptionSourceCreate) sqlSave(ctx context.Context) (*ProxySubscriptionSource, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProxySubscriptionSourceCreate) createSpec() (*ProxySubscriptionSource, *sqlgraph.CreateSpec) {
	var (
		_node = &ProxySubscriptionSource{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(proxysubscriptionsource.Table, sqlgraph.NewFieldSpec(proxysubscriptionsource.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(proxysubscriptionsource.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(proxysubscriptionsource.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(proxysubscriptionsource.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(proxysubscriptionsource.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(proxysubscriptionsource.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.SourceFormat(); ok {
		_spec.SetField(proxysubscriptionsource.FieldSourceFormat, field.TypeString, value)
		_node.SourceFormat = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(proxysubscriptionsource.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.RefreshIntervalHours(); ok {
		_spec.SetField(proxysubscriptionsource.FieldRefreshIntervalHours, field.TypeInt, value)
		_node.RefreshIntervalHours = value
	}
	if value, ok := _c.mutation.TargetEntryCount(); ok {
		_spec.SetField(proxysubscriptionsource.FieldTargetEntryCount, field.TypeInt, value)
		_node.TargetEntryCount = value
	}
	if value, ok := _c.mutation.AutoAddToPool(); ok {
		_spec.SetField(proxysubscriptionsource.FieldAutoAddToPool, field.TypeBool, value)
		_node.AutoAddToPool = value
	}
	if value, ok := _c.mutation.LastRefreshedAt(); ok {
		_spec.SetField(proxysubscriptionsource.FieldLastRefreshedAt, field.TypeTime, value)
		_node.LastRefreshedAt = &value
	}
	if value, ok := _c.mutation.LastSuccessAt(); ok {
		_spec.SetField(proxysubscriptionsource.FieldLastSuccessAt, field.TypeTime, value)
		_node.LastSuccessAt = &value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(proxysubscriptionsource.FieldLastError, field.TypeString, value)
		_node.LastError = &value
	}
	if value, ok := _c.mutation.LastNodeCount(); ok {
		_spec.SetField(proxysubscriptionsource.FieldLastNodeCount, field.TypeInt, value)
		_node.LastNodeCount = value
	}
	if value, ok := _c.mutation.LastMaterializedProxyCount(); ok {
		_spec.SetField(proxysubscriptionsource.FieldLastMaterializedProxyCount, field.TypeInt, value)
		_node.LastMaterializedProxyCount = value
	}
	if nodes := _c.mutation.NodesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   proxysubscriptionsource.NodesTable,
			Columns: []string{proxysubscriptionsource.NodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxysubscriptionnode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProxySubscriptionSource.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProxySubscriptionSourceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ProxySubscriptionSourceCreate) OnConflict(opts ...sql.ConflictOption) *ProxySubscriptionSourceUpsertOne {
	_c.conflict = opts
	return &ProxySubscriptionSourceUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProxySubscriptionSource.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProxySubscriptionSourceCreate) OnConflictColumns(columns ...string) *ProxySubscriptionSourceUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProxySubscriptionSourceUpsertOne{
		create: _c,
	}
}

type (
	// ProxySubscriptionSourceUpsertOne is the builder for "upsert"-ing
	//  one ProxySubscriptionSource node.
	ProxySubscriptionSourceUpsertOne struct {
		create *ProxySubscriptionSourceCreate
	}

	// ProxySubscriptionSourceUpsert is the "OnConflict" setter.
	ProxySubscriptionSourceUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ProxySubscriptionSourceUpsert) SetUpdatedAt(v time.Time) *ProxySubscriptionSourceUpsert {
	u.Set(proxysubscriptionsource.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProxySubscriptionSourceUpsert) UpdateUpdatedAt() *ProxySubscriptionSourceUpsert {
	u.SetExcluded(proxysubscriptionsource.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ProxySubscriptionSourceUpsert) SetDeletedAt(v time.Time) *ProxySubscriptionSourceUpsert {
	u.Set(proxysubscriptionsource.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ProxySubscriptionSourceUpsert) UpdateDeletedAt() *ProxySubscriptionSourceUpsert {
	u.SetExcluded(proxysubscriptionsource.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ProxySubscriptionSourceUpsert) ClearDeletedAt() *ProxySubscriptionSourceUpsert {
	u.SetNull(proxysubscriptionsource.FieldDeletedAt)
	return u
}

// SetName sets the "name" field.
func (u *ProxySubscriptionSourceUpsert) SetName(v string) *ProxySubscriptionSourceUpsert {
	u.Set(proxysubscriptionsource.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ProxySubscriptionSourceUpsert) UpdateName() *ProxySubscriptionSourceUpsert {
	u.SetExcluded(proxysubscriptionsource.FieldName)
	return u
}

// SetURL sets the "url" field.
func (u *ProxySubscriptionSourceUpsert) SetURL(v string) *ProxySubscriptionSourceUpsert {
	u.Set(proxysubscriptionsource.FieldURL, v)
	return u
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *ProxySubscriptionSourceUpsert) UpdateURL() *ProxySubscriptionSourceUpsert {
	u.SetExcluded(proxysubscriptionsource.FieldURL)
	return u
}

// SetSourceFormat sets the "source_format" field.
func (u *ProxySubscriptionSourceUpsert) SetSourceFormat(v string) *ProxySubscriptionSourceUpsert {
	u.Set(proxysubscriptionsource.FieldSourceFormat, v)
	return u
}

// UpdateSourceFormat sets the "source_format" field to the value that was provided on create.
func (u *ProxySubscriptionSourceUpsert) UpdateSourceFormat() *ProxySubscriptionSourceUpsert {
	u.SetExcluded(proxysubscriptionsource.FieldSourceFormat)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *ProxySubscriptionSourceUpsert) SetEnabled(v bool) *ProxySubscriptionSourceUpsert {
	u.Set(proxysubscriptionsource.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *ProxySubscriptionSourceUpsert) UpdateEnabled() *ProxySubscriptionSourceUpsert {
	u.SetExcluded(proxysubscriptionsource.FieldEnabled)
	return u
}

// SetRefreshIntervalHours sets the "refresh_interval_hours" field.
func (u *ProxySubscriptionSourceUpsert) SetRefreshIntervalHours(v int) *ProxySubscriptionSourceUpsert {
	u.Set(proxysubscriptionsource.FieldRefreshIntervalHours, v)
	return u
}

// UpdateRefreshIntervalHours sets the "refresh_interval_hours" field to the value that was provided on create.
func (u *ProxySubscriptionSourceUpsert) UpdateRefreshIntervalHours() *ProxySubscriptionSourceUpsert {
	u.SetExcluded(proxysubscriptionsource.FieldRefreshIntervalHours)
	return u
}

// AddRefreshIntervalHours adds v to the "refresh_interval_hours" field.
func (u *ProxySubscriptionSourceUpsert) AddRefreshIntervalHours(v int) *ProxySubscriptionSourceUpsert {
	u.Add(proxysubscriptionsource.FieldRefreshIntervalHours, v)
	return u
}

// SetTargetEntryCount sets the "target_entry_count" field.
func (u *ProxySubscriptionSourceUpsert) SetTargetEntryCount(v int) *ProxySubscriptionSourceUpsert {
	u.Set(proxysubscriptionsource.FieldTargetEntryCount, v)
	return u
}

// UpdateTargetEntryCount sets the "target_entry_count" field to the value that was provided on create.
func (u *ProxySubscriptionSourceUpsert) UpdateTargetEntryCount() *ProxySubscriptionSourceUpsert {
	u.SetExcluded(proxysubscriptionsource.FieldTargetEntryCount)
	return u
}

// AddTargetEntryCount adds v to the "target_entry_count" field.
func (u *ProxySubscriptionSourceUpsert) AddTargetEntryCount(v int) *ProxySubscriptionSourceUpsert {
	u.Add(proxysubscriptionsource.FieldTargetEntryCount, v)
	return u
}

// SetAutoAddToPool sets the "auto_add_to_pool" field.
func (u *ProxySubscriptionSourceUpsert) SetAutoAddToPool(v bool) *ProxySubscriptionSourceUpsert {
	u.Set(proxysubscriptionsource.FieldAutoAddToPool, v)
	return u
}

// UpdateAutoAddToPool sets the "auto_add_to_pool" field to the value that was provided on create.
func (u *ProxySubscriptionSourceUpsert) UpdateAutoAddToPool() *ProxySubscriptionSourceUpsert {
	u.SetExcluded(proxysubscriptionsource.FieldAutoAddToPool)
	return u
}

// SetLastRefreshedAt sets the "last_refreshed_at" field.
func (u *ProxySubscriptionSourceUpsert) SetLastRefreshedAt(v time.Time) *ProxySubscriptionSourceUpsert {
	u.Set(proxysubscriptionsource.FieldLastRefreshedAt, v)
	return u
}

// UpdateLastRefreshedAt sets the "last_refreshed_at" field to the value that was provided on create.
func (u *ProxySubscriptionSourceUpsert) UpdateLastRefreshedAt() *ProxySubscriptionSourceUpsert {
	u.SetExcluded(proxysubscriptionsource.FieldLastRefreshedAt)
	return u
}

// ClearLastRefreshedAt clears the value of the "last_refreshed_at" field.
func (u *ProxySubscriptionSourceUpsert) ClearLastRefreshedAt() *ProxySubscriptionSourceUpsert {
	u.SetNull(proxysubscriptionsource.FieldLastRefreshedAt)
	return u
}

// SetLastSuccessAt sets the "last_success_at" field.
func (u *ProxySubscriptionSourceUpsert) SetLastSuccessAt(v time.Time) *ProxySubscriptionSourceUpsert {
	u.Set(proxysubscriptionsource.FieldLastSuccessAt, v)
	return u
}

// UpdateLastSuccessAt sets the "last_success_at" field to the value that was provided on create.
func (u *ProxySubscriptionSourceUpsert) UpdateLastSuccessAt() *ProxySubscriptionSourceUpsert {
	u.SetExcluded(proxysubscriptionsource.FieldLastSuccessAt)
	return u
}

// ClearLastSuccessAt clears the value of the "last_success_at" field.
func (u *ProxySubscriptionSourceUpsert) ClearLastSuccessAt() *ProxySubscriptionSourceUpsert {
	u.SetNull(proxysubscriptionsource.FieldLastSuccessAt)
	return u
}

// SetLastError sets the "last_error" field.
func (u *ProxySubscriptionSourceUpsert) SetLastError(v string) *ProxySubscriptionSourceUpsert {
	u.Set(proxysubscriptionsource.FieldLastError, v)
	return u
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *ProxySubscriptionSourceUpsert) UpdateLastError() *ProxySubscriptionSourceUpsert {
	u.SetExcluded(proxysubscriptionsource.FieldLastError)
	return u
}

// ClearLastError clears the value of the "last_error" field.
func (u *ProxySubscriptionSourceUpsert) ClearLastError() *ProxySubscriptionSourceUpsert {
	u.SetNull(proxysubscriptionsource.FieldLastError)
	return u
}

// SetLastNodeCount sets the "last_node_count" field.
func (u *ProxySubscriptionSourceUpsert) SetLastNodeCount(v int) *ProxySubscriptionSourceUpsert {
	u.Set(proxysubscriptionsource.FieldLastNodeCount, v)
	return u
}

// UpdateLastNodeCount sets the "last_node_count" field to the value that was provided on create.
func (u *ProxySubscriptionSourceUpsert) UpdateLastNodeCount() *ProxySubscriptionSourceUpsert {
	u.SetExcluded(proxysubscriptionsource.FieldLastNodeCount)
	return u
}

// AddLastNodeCount adds v to the "last_node_count" field.
func (u *ProxySubscriptionSourceUpsert) AddLastNodeCount(v int) *ProxySubscriptionSourceUpsert {
	u.Add(proxysubscriptionsource.FieldLastNodeCount, v)
	return u
}

// SetLastMaterializedProxyCount sets the "last_materialized_proxy_count" field.
func (u *ProxySubscriptionSourceUpsert) SetLastMaterializedProxyCount(v int) *ProxySubscriptionSourceUpsert {
	u.Set(proxysubscriptionsource.FieldLastMaterializedProxyCount, v)
	return u
}

// UpdateLastMaterializedProxyCount sets the "last_materialized_proxy_count" field to the value that was provided on create.
func (u *ProxySubscriptionSourceUpsert) UpdateLastMaterializedProxyCount() *ProxySubscriptionSourceUpsert {
	u.SetExcluded(proxysubscriptionsource.FieldLastMaterializedProxyCount)
	return u
}

// AddLastMaterializedProxyCount adds v to the "last_materialized_proxy_count" field.
func (u *ProxySubscriptionSourceUpsert) AddLastMaterializedProxyCount(v int) *ProxySubscriptionSourceUpsert {
	u.Add(proxysubscriptionsource.FieldLastMaterializedProxyCount, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ProxySubscriptionSource.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ProxySubscriptionSourceUpsertOne) UpdateNewValues() *ProxySubscriptionSourceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(proxysubscriptionsource.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProxySubscriptionSource.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ProxySubscriptionSourceUpsertOne) Ignore() *ProxySubscriptionSourceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProxySubscriptionSourceUpsertOne) DoNothing() *ProxySubscriptionSourceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProxySubscriptionSourceCreate.OnConflict
// documentation for more info.
func (u *ProxySubscriptionSourceUpsertOne) Update(set func(*ProxySubscriptionSourceUpsert)) *ProxySubscriptionSourceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProxySubscriptionSourceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProxySubscriptionSourceUpsertOne) SetUpdatedAt(v time.Time) *ProxySubscriptionSourceUpsertOne {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProxySubscriptionSourceUpsertOne) UpdateUpdatedAt() *ProxySubscriptionSourceUpsertOne {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ProxySubscriptionSourceUpsertOne) SetDeletedAt(v time.Time) *ProxySubscriptionSourceUpsertOne {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ProxySubscriptionSourceUpsertOne) UpdateDeletedAt() *ProxySubscriptionSourceUpsertOne {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ProxySubscriptionSourceUpsertOne) ClearDeletedAt() *ProxySubscriptionSourceUpsertOne {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *ProxySubscriptionSourceUpsertOne) SetName(v string) *ProxySubscriptionSourceUpsertOne {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ProxySubscriptionSourceUpsertOne) UpdateName() *ProxySubscriptionSourceUpsertOne {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.UpdateName()
	})
}

// SetURL sets the "url" field.
func (u *ProxySubscriptionSourceUpsertOne) SetURL(v string) *ProxySubscriptionSourceUpsertOne {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *ProxySubscriptionSourceUpsertOne) UpdateURL() *ProxySubscriptionSourceUpsertOne {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.UpdateURL()
	})
}

// SetSourceFormat sets the "source_format" field.
func (u *ProxySubscriptionSourceUpsertOne) SetSourceFormat(v string) *ProxySubscriptionSourceUpsertOne {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.SetSourceFormat(v)
	})
}

// UpdateSourceFormat sets the "source_format" field to the value that was provided on create.
func (u *ProxySubscriptionSourceUpsertOne) UpdateSourceFormat() *ProxySubscriptionSourceUpsertOne {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.UpdateSourceFormat()
	})
}

// SetEnabled sets the "enabled" field.
func (u *ProxySubscriptionSourceUpsertOne) SetEnabled(v bool) *ProxySubscriptionSourceUpsertOne {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *ProxySubscriptionSourceUpsertOne) UpdateEnabled() *ProxySubscriptionSourceUpsertOne {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.UpdateEnabled()
	})
}

// SetRefreshIntervalHours sets the "refresh_interval_hours" field.
func (u *ProxySubscriptionSourceUpsertOne) SetRefreshIntervalHours(v int) *ProxySubscriptionSourceUpsertOne {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.SetRefreshIntervalHours(v)
	})
}

// AddRefreshIntervalHours adds v to the "refresh_interval_hours" field.
func (u *ProxySubscriptionSourceUpsertOne) AddRefreshIntervalHours(v int) *ProxySubscriptionSourceUpsertOne {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.AddRefreshIntervalHours(v)
	})
}

// UpdateRefreshIntervalHours sets the "refresh_interval_hours" field to the value that was provided on create.
func (u *ProxySubscriptionSourceUpsertOne) UpdateRefreshIntervalHours() *ProxySubscriptionSourceUpsertOne {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.UpdateRefreshIntervalHours()
	})
}

// SetTargetEntryCount sets the "target_entry_count" field.
func (u *ProxySubscriptionSourceUpsertOne) SetTargetEntryCount(v int) *ProxySubscriptionSourceUpsertOne {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.SetTargetEntryCount(v)
	})
}

// AddTargetEntryCount adds v to the "target_entry_count" field.
func (u *ProxySubscriptionSourceUpsertOne) AddTargetEntryCount(v int) *ProxySubscriptionSourceUpsertOne {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.AddTargetEntryCount(v)
	})
}

// UpdateTargetEntryCount sets the "target_entry_count" field to the value that was provided on create.
func (u *ProxySubscriptionSourceUpsertOne) UpdateTargetEntryCount() *ProxySubscriptionSourceUpsertOne {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.UpdateTargetEntryCount()
	})
}

// SetAutoAddToPool sets the "auto_add_to_pool" field.
func (u *ProxySubscriptionSourceUpsertOne) SetAutoAddToPool(v bool) *ProxySubscriptionSourceUpsertOne {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.SetAutoAddToPool(v)
	})
}

// UpdateAutoAddToPool sets the "auto_add_to_pool" field to the value that was provided on create.
func (u *ProxySubscriptionSourceUpsertOne) UpdateAutoAddToPool() *ProxySubscriptionSourceUpsertOne {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.UpdateAutoAddToPool()
	})
}

// SetLastRefreshedAt sets the "last_refreshed_at" field.
func (u *ProxySubscriptionSourceUpsertOne) SetLastRefreshedAt(v time.Time) *ProxySubscriptionSourceUpsertOne {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.SetLastRefreshedAt(v)
	})
}

// UpdateLastRefreshedAt sets the "last_refreshed_at" field to the value that was provided on create.
func (u *ProxySubscriptionSourceUpsertOne) UpdateLastRefreshedAt() *ProxySubscriptionSourceUpsertOne {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.UpdateLastRefreshedAt()
	})
}

// ClearLastRefreshedAt clears the value of the "last_refreshed_at" field.
func (u *ProxySubscriptionSourceUpsertOne) ClearLastRefreshedAt() *ProxySubscriptionSourceUpsertOne {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.ClearLastRefreshedAt()
	})
}

// SetLastSuccessAt sets the "last_success_at" field.
func (u *ProxySubscriptionSourceUpsertOne) SetLastSuccessAt(v time.Time) *ProxySubscriptionSourceUpsertOne {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.SetLastSuccessAt(v)
	})
}

// UpdateLastSuccessAt sets the "last_success_at" field to the value that was provided on create.
func (u *ProxySubscriptionSourceUpsertOne) UpdateLastSuccessAt() *ProxySubscriptionSourceUpsertOne {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.UpdateLastSuccessAt()
	})
}

// ClearLastSuccessAt clears the value of the "last_success_at" field.
func (u *ProxySubscriptionSourceUpsertOne) ClearLastSuccessAt() *ProxySubscriptionSourceUpsertOne {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.ClearLastSuccessAt()
	})
}

// SetLastError sets the "last_error" field.
func (u *ProxySubscriptionSourceUpsertOne) SetLastError(v string) *ProxySubscriptionSourceUpsertOne {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *ProxySubscriptionSourceUpsertOne) UpdateLastError() *ProxySubscriptionSourceUpsertOne {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.UpdateLastError()
	})
}

// ClearLastError clears the value of the "last_error" field.
func (u *ProxySubscriptionSourceUpsertOne) ClearLastError() *ProxySubscriptionSourceUpsertOne {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.ClearLastError()
	})
}

// SetLastNodeCount sets the "last_node_count" field.
func (u *ProxySubscriptionSourceUpsertOne) SetLastNodeCount(v int) *ProxySubscriptionSourceUpsertOne {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.SetLastNodeCount(v)
	})
}

// AddLastNodeCount adds v to the "last_node_count" field.
func (u *ProxySubscriptionSourceUpsertOne) AddLastNodeCount(v int) *ProxySubscriptionSourceUpsertOne {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.AddLastNodeCount(v)
	})
}

// UpdateLastNodeCount sets the "last_node_count" field to the value that was provided on create.
func (u *ProxySubscriptionSourceUpsertOne) UpdateLastNodeCount() *ProxySubscriptionSourceUpsertOne {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.UpdateLastNodeCount()
	})
}

// SetLastMaterializedProxyCount sets the "last_materialized_proxy_count" field.
func (u *ProxySubscriptionSourceUpsertOne) SetLastMaterializedProxyCount(v int) *ProxySubscriptionSourceUpsertOne {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.SetLastMaterializedProxyCount(v)
	})
}

// AddLastMaterializedProxyCount adds v to the "last_materialized_proxy_count" field.
func (u *ProxySubscriptionSourceUpsertOne) AddLastMaterializedProxyCount(v int) *ProxySubscriptionSourceUpsertOne {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.AddLastMaterializedProxyCount(v)
	})
}

// UpdateLastMaterializedProxyCount sets the "last_materialized_proxy_count" field to the value that was provided on create.
func (u *ProxySubscriptionSourceUpsertOne) UpdateLastMaterializedProxyCount() *ProxySubscriptionSourceUpsertOne {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.UpdateLastMaterializedProxyCount()
	})
}

// Exec executes the query.
func (u *ProxySubscriptionSourceUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProxySubscriptionSourceCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProxySubscriptionSourceUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ProxySubscriptionSourceUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ProxySubscriptionSourceUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ProxySubscriptionSourceCreateBulk is the builder for creating many ProxySubscriptionSource entities in bulk.
type ProxySubscriptionSourceCreateBulk struct {
	config
	err      error
	builders []*ProxySubscriptionSourceCreate
	conflict []sql.ConflictOption
}

// Save creates the ProxySubscriptionSource entities in the database.
func (_c *ProxySubscriptionSourceCreateBulk) Save(ctx context.Context) ([]*ProxySubscriptionSource, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProxySubscriptionSource, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProxySubscriptionSourceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProxySubscriptionSourceCreateBulk) SaveX(ctx context.Context) []*ProxySubscriptionSource {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProxySubscriptionSourceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProxySubscriptionSourceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProxySubscriptionSource.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProxySubscriptionSourceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ProxySubscriptionSourceCreateBulk) OnConflict(opts ...sql.ConflictOption) *ProxySubscriptionSourceUpsertBulk {
	_c.conflict = opts
	return &ProxySubscriptionSourceUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProxySubscriptionSource.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProxySubscriptionSourceCreateBulk) OnConflictColumns(columns ...string) *ProxySubscriptionSourceUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProxySubscriptionSourceUpsertBulk{
		create: _c,
	}
}

// ProxySubscriptionSourceUpsertBulk is the builder for "upsert"-ing
// a bulk of ProxySubscriptionSource nodes.
type ProxySubscriptionSourceUpsertBulk struct {
	create *ProxySubscriptionSourceCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ProxySubscriptionSource.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ProxySubscriptionSourceUpsertBulk) UpdateNewValues() *ProxySubscriptionSourceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(proxysubscriptionsource.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProxySubscriptionSource.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ProxySubscriptionSourceUpsertBulk) Ignore() *ProxySubscriptionSourceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProxySubscriptionSourceUpsertBulk) DoNothing() *ProxySubscriptionSourceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProxySubscriptionSourceCreateBulk.OnConflict
// documentation for more info.
func (u *ProxySubscriptionSourceUpsertBulk) Update(set func(*ProxySubscriptionSourceUpsert)) *ProxySubscriptionSourceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProxySubscriptionSourceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProxySubscriptionSourceUpsertBulk) SetUpdatedAt(v time.Time) *ProxySubscriptionSourceUpsertBulk {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProxySubscriptionSourceUpsertBulk) UpdateUpdatedAt() *ProxySubscriptionSourceUpsertBulk {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ProxySubscriptionSourceUpsertBulk) SetDeletedAt(v time.Time) *ProxySubscriptionSourceUpsertBulk {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ProxySubscriptionSourceUpsertBulk) UpdateDeletedAt() *ProxySubscriptionSourceUpsertBulk {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ProxySubscriptionSourceUpsertBulk) ClearDeletedAt() *ProxySubscriptionSourceUpsertBulk {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *ProxySubscriptionSourceUpsertBulk) SetName(v string) *ProxySubscriptionSourceUpsertBulk {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ProxySubscriptionSourceUpsertBulk) UpdateName() *ProxySubscriptionSourceUpsertBulk {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.UpdateName()
	})
}

// SetURL sets the "url" field.
func (u *ProxySubscriptionSourceUpsertBulk) SetURL(v string) *ProxySubscriptionSourceUpsertBulk {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *ProxySubscriptionSourceUpsertBulk) UpdateURL() *ProxySubscriptionSourceUpsertBulk {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.UpdateURL()
	})
}

// SetSourceFormat sets the "source_format" field.
func (u *ProxySubscriptionSourceUpsertBulk) SetSourceFormat(v string) *ProxySubscriptionSourceUpsertBulk {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.SetSourceFormat(v)
	})
}

// UpdateSourceFormat sets the "source_format" field to the value that was provided on create.
func (u *ProxySubscriptionSourceUpsertBulk) UpdateSourceFormat() *ProxySubscriptionSourceUpsertBulk {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.UpdateSourceFormat()
	})
}

// SetEnabled sets the "enabled" field.
func (u *ProxySubscriptionSourceUpsertBulk) SetEnabled(v bool) *ProxySubscriptionSourceUpsertBulk {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *ProxySubscriptionSourceUpsertBulk) UpdateEnabled() *ProxySubscriptionSourceUpsertBulk {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.UpdateEnabled()
	})
}

// SetRefreshIntervalHours sets the "refresh_interval_hours" field.
func (u *ProxySubscriptionSourceUpsertBulk) SetRefreshIntervalHours(v int) *ProxySubscriptionSourceUpsertBulk {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.SetRefreshIntervalHours(v)
	})
}

// AddRefreshIntervalHours adds v to the "refresh_interval_hours" field.
func (u *ProxySubscriptionSourceUpsertBulk) AddRefreshIntervalHours(v int) *ProxySubscriptionSourceUpsertBulk {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.AddRefreshIntervalHours(v)
	})
}

// UpdateRefreshIntervalHours sets the "refresh_interval_hours" field to the value that was provided on create.
func (u *ProxySubscriptionSourceUpsertBulk) UpdateRefreshIntervalHours() *ProxySubscriptionSourceUpsertBulk {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.UpdateRefreshIntervalHours()
	})
}

// SetTargetEntryCount sets the "target_entry_count" field.
func (u *ProxySubscriptionSourceUpsertBulk) SetTargetEntryCount(v int) *ProxySubscriptionSourceUpsertBulk {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.SetTargetEntryCount(v)
	})
}

// AddTargetEntryCount adds v to the "target_entry_count" field.
func (u *ProxySubscriptionSourceUpsertBulk) AddTargetEntryCount(v int) *ProxySubscriptionSourceUpsertBulk {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.AddTargetEntryCount(v)
	})
}

// UpdateTargetEntryCount sets the "target_entry_count" field to the value that was provided on create.
func (u *ProxySubscriptionSourceUpsertBulk) UpdateTargetEntryCount() *ProxySubscriptionSourceUpsertBulk {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.UpdateTargetEntryCount()
	})
}

// SetAutoAddToPool sets the "auto_add_to_pool" field.
func (u *ProxySubscriptionSourceUpsertBulk) SetAutoAddToPool(v bool) *ProxySubscriptionSourceUpsertBulk {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.SetAutoAddToPool(v)
	})
}

// UpdateAutoAddToPool sets the "auto_add_to_pool" field to the value that was provided on create.
func (u *ProxySubscriptionSourceUpsertBulk) UpdateAutoAddToPool() *ProxySubscriptionSourceUpsertBulk {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.UpdateAutoAddToPool()
	})
}

// SetLastRefreshedAt sets the "last_refreshed_at" field.
func (u *ProxySubscriptionSourceUpsertBulk) SetLastRefreshedAt(v time.Time) *ProxySubscriptionSourceUpsertBulk {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.SetLastRefreshedAt(v)
	})
}

// UpdateLastRefreshedAt sets the "last_refreshed_at" field to the value that was provided on create.
func (u *ProxySubscriptionSourceUpsertBulk) UpdateLastRefreshedAt() *ProxySubscriptionSourceUpsertBulk {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.UpdateLastRefreshedAt()
	})
}

// ClearLastRefreshedAt clears the value of the "last_refreshed_at" field.
func (u *ProxySubscriptionSourceUpsertBulk) ClearLastRefreshedAt() *ProxySubscriptionSourceUpsertBulk {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.ClearLastRefreshedAt()
	})
}

// SetLastSuccessAt sets the "last_success_at" field.
func (u *ProxySubscriptionSourceUpsertBulk) SetLastSuccessAt(v time.Time) *ProxySubscriptionSourceUpsertBulk {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.SetLastSuccessAt(v)
	})
}

// UpdateLastSuccessAt sets the "last_success_at" field to the value that was provided on create.
func (u *ProxySubscriptionSourceUpsertBulk) UpdateLastSuccessAt() *ProxySubscriptionSourceUpsertBulk {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.UpdateLastSuccessAt()
	})
}

// ClearLastSuccessAt clears the value of the "last_success_at" field.
func (u *ProxySubscriptionSourceUpsertBulk) ClearLastSuccessAt() *ProxySubscriptionSourceUpsertBulk {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.ClearLastSuccessAt()
	})
}

// SetLastError sets the "last_error" field.
func (u *ProxySubscriptionSourceUpsertBulk) SetLastError(v string) *ProxySubscriptionSourceUpsertBulk {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *ProxySubscriptionSourceUpsertBulk) UpdateLastError() *ProxySubscriptionSourceUpsertBulk {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.UpdateLastError()
	})
}

// ClearLastError clears the value of the "last_error" field.
func (u *ProxySubscriptionSourceUpsertBulk) ClearLastError() *ProxySubscriptionSourceUpsertBulk {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.ClearLastError()
	})
}

// SetLastNodeCount sets the "last_node_count" field.
func (u *ProxySubscriptionSourceUpsertBulk) SetLastNodeCount(v int) *ProxySubscriptionSourceUpsertBulk {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.SetLastNodeCount(v)
	})
}

// AddLastNodeCount adds v to the "last_node_count" field.
func (u *ProxySubscriptionSourceUpsertBulk) AddLastNodeCount(v int) *ProxySubscriptionSourceUpsertBulk {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.AddLastNodeCount(v)
	})
}

// UpdateLastNodeCount sets the "last_node_count" field to the value that was provided on create.
func (u *ProxySubscriptionSourceUpsertBulk) UpdateLastNodeCount() *ProxySubscriptionSourceUpsertBulk {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.UpdateLastNodeCount()
	})
}

// SetLastMaterializedProxyCount sets the "last_materialized_proxy_count" field.
func (u *ProxySubscriptionSourceUpsertBulk) SetLastMaterializedProxyCount(v int) *ProxySubscriptionSourceUpsertBulk {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.SetLastMaterializedProxyCount(v)
	})
}

// AddLastMaterializedProxyCount adds v to the "last_materialized_proxy_count" field.
func (u *ProxySubscriptionSourceUpsertBulk) AddLastMaterializedProxyCount(v int) *ProxySubscriptionSourceUpsertBulk {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.AddLastMaterializedProxyCount(v)
	})
}

// UpdateLastMaterializedProxyCount sets the "last_materialized_proxy_count" field to the value that was provided on create.
func (u *ProxySubscriptionSourceUpsertBulk) UpdateLastMaterializedProxyCount() *ProxySubscriptionSourceUpsertBulk {
	return u.Update(func(s *ProxySubscriptionSourceUpsert) {
		s.UpdateLastMaterializedProxyCount()
	})
}

// Exec executes the query.
func (u *ProxySubscriptionSourceUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ProxySubscriptionSourceCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProxySubscriptionSourceCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProxySubscriptionSourceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
