// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/ledgerentry"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/transactionlog"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/userbankaccount"
)

// TransactionLogUpdate is the builder for updating TransactionLog entities.
type TransactionLogUpdate struct {
	config
	hooks    []Hook
	mutation *TransactionLogMutation
}

// Where appends a list predicates to the TransactionLogUpdate builder.
func (_u *TransactionLogUpdate) Where(ps ...predicate.TransactionLog) *TransactionLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *TransactionLogUpdate) SetUserID(v int64) *TransactionLogUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TransactionLogUpdate) SetNillableUserID(v *int64) *TransactionLogUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *TransactionLogUpdate) SetAccountID(v int64) *TransactionLogUpdate {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *TransactionLogUpdate) SetNillableAccountID(v *int64) *TransactionLogUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *TransactionLogUpdate) SetUser(v *User) *TransactionLogUpdate {
	return _u.SetUserID(v.ID)
}

// SetAccount sets the "account" edge to the UserBankAccount entity.
func (_u *TransactionLogUpdate) SetAccount(v *UserBankAccount) *TransactionLogUpdate {
	return _u.SetAccountID(v.ID)
}

// AddLedgerEntryIDs adds the "ledger_entries" edge to the LedgerEntry entity by IDs.
func (_u *TransactionLogUpdate) AddLedgerEntryIDs(ids ...int64) *TransactionLogUpdate {
	_u.mutation.AddLedgerEntryIDs(ids...)
	return _u
}

// AddLedgerEntries adds the "ledger_entries" edges to the LedgerEntry entity.
func (_u *TransactionLogUpdate) AddLedgerEntries(v ...*LedgerEntry) *TransactionLogUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLedgerEntryIDs(ids...)
}

// Mutation returns the TransactionLogMutation object of the builder.
func (_u *TransactionLogUpdate) Mutation() *TransactionLogMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *TransactionLogUpdate) ClearUser() *TransactionLogUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearAccount clears the "account" edge to the UserBankAccount entity.
func (_u *TransactionLogUpdate) ClearAccount() *TransactionLogUpdate {
	_u.mutation.ClearAccount()
	return _u
}

// ClearLedgerEntries clears all "ledger_entries" edges to the LedgerEntry entity.
func (_u *TransactionLogUpdate) ClearLedgerEntries() *TransactionLogUpdate {
	_u.mutation.ClearLedgerEntries()
	return _u
}

// RemoveLedgerEntryIDs removes the "ledger_entries" edge to LedgerEntry entities by IDs.
func (_u *TransactionLogUpdate) RemoveLedgerEntryIDs(ids ...int64) *TransactionLogUpdate {
	_u.mutation.RemoveLedgerEntryIDs(ids...)
	return _u
}

// RemoveLedgerEntries removes "ledger_entries" edges to LedgerEntry entities.
func (_u *TransactionLogUpdate) RemoveLedgerEntries(v ...*LedgerEntry) *TransactionLogUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLedgerEntryIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TransactionLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TransactionLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TransactionLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TransactionLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TransactionLogUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TransactionLog.user"`)
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TransactionLog.account"`)
	}
	return nil
}

func (_u *TransactionLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(transactionlog.Table, transactionlog.Columns, sqlgraph.NewFieldSpec(transactionlog.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.ReferenceTypeCleared() {
		_spec.ClearField(transactionlog.FieldReferenceType, field.TypeString)
	}
	if _u.mutation.ReferenceIDCleared() {
		_spec.ClearField(transactionlog.FieldReferenceID, field.TypeString)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(transactionlog.FieldRequestID, field.TypeString)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(transactionlog.FieldMetadata, field.TypeJSON)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transactionlog.UserTable,
			Columns: []string{transactionlog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transactionlog.UserTable,
			Columns: []string{transactionlog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transactionlog.AccountTable,
			Columns: []string{transactionlog.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userbankaccount.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transactionlog.AccountTable,
			Columns: []string{transactionlog.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userbankaccount.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LedgerEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   transactionlog.LedgerEntriesTable,
			Columns: []string{transactionlog.LedgerEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgerentry.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLedgerEntriesIDs(); len(nodes) > 0 && !_u.mutation.LedgerEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   transactionlog.LedgerEntriesTable,
			Columns: []string{transactionlog.LedgerEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgerentry.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LedgerEntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   transactionlog.LedgerEntriesTable,
			Columns: []string{transactionlog.LedgerEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgerentry.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{transactionlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TransactionLogUpdateOne is the builder for updating a single TransactionLog entity.
type TransactionLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TransactionLogMutation
}

// SetUserID sets the "user_id" field.
func (_u *TransactionLogUpdateOne) SetUserID(v int64) *TransactionLogUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TransactionLogUpdateOne) SetNillableUserID(v *int64) *TransactionLogUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *TransactionLogUpdateOne) SetAccountID(v int64) *TransactionLogUpdateOne {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *TransactionLogUpdateOne) SetNillableAccountID(v *int64) *TransactionLogUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *TransactionLogUpdateOne) SetUser(v *User) *TransactionLogUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetAccount sets the "account" edge to the UserBankAccount entity.
func (_u *TransactionLogUpdateOne) SetAccount(v *UserBankAccount) *TransactionLogUpdateOne {
	return _u.SetAccountID(v.ID)
}

// AddLedgerEntryIDs adds the "ledger_entries" edge to the LedgerEntry entity by IDs.
func (_u *TransactionLogUpdateOne) AddLedgerEntryIDs(ids ...int64) *TransactionLogUpdateOne {
	_u.mutation.AddLedgerEntryIDs(ids...)
	return _u
}

// AddLedgerEntries adds the "ledger_entries" edges to the LedgerEntry entity.
func (_u *TransactionLogUpdateOne) AddLedgerEntries(v ...*LedgerEntry) *TransactionLogUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLedgerEntryIDs(ids...)
}

// Mutation returns the TransactionLogMutation object of the builder.
func (_u *TransactionLogUpdateOne) Mutation() *TransactionLogMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *TransactionLogUpdateOne) ClearUser() *TransactionLogUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearAccount clears the "account" edge to the UserBankAccount entity.
func (_u *TransactionLogUpdateOne) ClearAccount() *TransactionLogUpdateOne {
	_u.mutation.ClearAccount()
	return _u
}

// ClearLedgerEntries clears all "ledger_entries" edges to the LedgerEntry entity.
func (_u *TransactionLogUpdateOne) ClearLedgerEntries() *TransactionLogUpdateOne {
	_u.mutation.ClearLedgerEntries()
	return _u
}

// RemoveLedgerEntryIDs removes the "ledger_entries" edge to LedgerEntry entities by IDs.
func (_u *TransactionLogUpdateOne) RemoveLedgerEntryIDs(ids ...int64) *TransactionLogUpdateOne {
	_u.mutation.RemoveLedgerEntryIDs(ids...)
	return _u
}

// RemoveLedgerEntries removes "ledger_entries" edges to LedgerEntry entities.
func (_u *TransactionLogUpdateOne) RemoveLedgerEntries(v ...*LedgerEntry) *TransactionLogUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLedgerEntryIDs(ids...)
}

// Where appends a list predicates to the TransactionLogUpdate builder.
func (_u *TransactionLogUpdateOne) Where(ps ...predicate.TransactionLog) *TransactionLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TransactionLogUpdateOne) Select(field string, fields ...string) *TransactionLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TransactionLog entity.
func (_u *TransactionLogUpdateOne) Save(ctx context.Context) (*TransactionLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TransactionLogUpdateOne) SaveX(ctx context.Context) *TransactionLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TransactionLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TransactionLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TransactionLogUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TransactionLog.user"`)
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TransactionLog.account"`)
	}
	return nil
}

func (_u *TransactionLogUpdateOne) sqlSave(ctx context.Context) (_node *TransactionLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(transactionlog.Table, transactionlog.Columns, sqlgraph.NewFieldSpec(transactionlog.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TransactionLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, transactionlog.FieldID)
		for _, f := range fields {
			if !transactionlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != transactionlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.ReferenceTypeCleared() {
		_spec.ClearField(transactionlog.FieldReferenceType, field.TypeString)
	}
	if _u.mutation.ReferenceIDCleared() {
		_spec.ClearField(transactionlog.FieldReferenceID, field.TypeString)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(transactionlog.FieldRequestID, field.TypeString)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(transactionlog.FieldMetadata, field.TypeJSON)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transactionlog.UserTable,
			Columns: []string{transactionlog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transactionlog.UserTable,
			Columns: []string{transactionlog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transactionlog.AccountTable,
			Columns: []string{transactionlog.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userbankaccount.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transactionlog.AccountTable,
			Columns: []string{transactionlog.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userbankaccount.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LedgerEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   transactionlog.LedgerEntriesTable,
			Columns: []string{transactionlog.LedgerEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgerentry.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLedgerEntriesIDs(); len(nodes) > 0 && !_u.mutation.LedgerEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   transactionlog.LedgerEntriesTable,
			Columns: []string{transactionlog.LedgerEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgerentry.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LedgerEntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   transactionlog.LedgerEntriesTable,
			Columns: []string{transactionlog.LedgerEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgerentry.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TransactionLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{transactionlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
