export default {
  checkin: {
    title: 'Daily Check-in', checked: 'Checked in today', todayReward: 'Earned ${amount} today', streakDays: '{days}-day streak',
    rangeHint: 'Reward range ${min} - ${max}', luckTitle: 'Lucky Check-in', luckButton: 'Confirm lucky check-in',
    luckSuccess: '{multiplier}x multiplier, earned ${amount}', luckLoss: '{multiplier}x multiplier, lost ${amount}', luckEven: '1.00x multiplier, no gain or loss',
    betAmount: 'Bet amount', betAmountPlaceholder: 'Enter an amount', multiplierRange: 'Multiplier range ${min}x - ${max}x',
    checkinType: 'Check-in type', normalCheckin: 'Normal check-in', luckCheckin: 'Lucky check-in',
    blindboxCommon: 'Common', blindboxRare: 'Rare', blindboxEpic: 'Epic', blindboxLegendary: 'Legendary',
    blindboxBalanceReward: 'Balance +${value}', blindboxConcurrencyReward: 'Concurrency +{value}', blindboxSubscriptionReward: '{days}-day subscription',
    blindboxInvitationReward: 'Invitation code x1', blindboxInviteCode: 'Your invitation code', blindboxHistory: 'Blind-box prizes', blindboxHistoryDesc: 'Prizes earned from check-in blind boxes', blindboxDays: ' days',
    page: {
      description: 'Daily rewards, blind-box prizes, and account overview', balance: 'Balance', streak: 'Check-in streak', days: ' days', concurrency: 'Concurrency', blindboxCount: 'Blind boxes',
      noBlindbox: 'No blind-box prizes yet', todayResult: "Today's check-in", todayReward: 'Reward', todayMultiplier: 'Multiplier', todayBlindbox: 'Blind box',
      todayNormal: 'Normal check-in', todayLuck: 'Lucky check-in', todayNoResult: 'Not checked in today', rarityBreakdown: 'Rarity breakdown', blindboxInfo: 'Blind-box rules',
      triggerType: 'Trigger', triggerTotal: 'Total check-ins', triggerStreak: 'Check-in streak', triggerInterval: 'Interval',
      blindboxNextIn: '{days} days until the next blind box', blindboxNextCycle: 'Triggers every {interval} consecutive days', calendarTitle: 'Check-in calendar'
    }
  },
  leaderboard: {
    title: 'Leaderboard', subtitle: 'Explore site activity using consistent ranking rules', empty: 'No ranking data', streakDays: '{days} days', rank: 'Rank {rank}', daysValue: '{value} days', loadFailed: 'Could not load the leaderboard. Try again.', privacyNotice: 'Display names follow the site privacy policy. Rankings are for on-site activity only.',
    balanceSubtitle: '{count} total check-ins', consumptionSubtitle: '{count} requests', checkinSubtitle: '{total} check-ins · Latest {date} · Earned ${reward}', transferSubtitle: '{count} successful transfers',
    filterLabel: 'Leaderboard filters', periodFilterLabel: 'Ranking period', distributionTitle: '{board} distribution', distributionHint: 'Values and shares are calculated from the current page', pageTotal: 'Page total', listedUsers: 'Users', currentPageUsers: '{count} on this page', chartHint: 'Hover a chart segment to view its user, amount, and share', rankingTitle: 'Ranking details', currentPage: 'Page {page}', others: 'Other users', noBoards: 'No leaderboards available', noBoardsHint: 'No leaderboard has been enabled yet. Please check again later.',
    distributionNames: { balance: 'Balance', consumption: 'Consumption', checkin: 'Check-in', transfer: 'Transfer' }, distributionHints: { balance: 'View the amount share of users on the balance leaderboard', consumption: 'View the amount share of all consumers in the current period', checkin: 'View the streak share of users on the check-in leaderboard', transfer: 'View the amount share of all senders in the current period' }, summaryHeaders: { balance: 'Amount', consumption: 'Total amount', checkin: 'Total days', transfer: 'Total amount' },
    columns: { user: 'User', share: 'Share' }, activityHeaders: { balance: 'Check-ins', consumption: 'Requests', checkin: 'Total check-ins', transfer: 'Transfers' }, valueHeaders: { balance: 'Balance', consumption: 'Spend', checkin: 'Streak', transfer: 'Amount sent' },
    tabs: { balance: 'Balance', consumption: 'Consumption', checkin: 'Check-in', transfer: 'Transfers' }, periods: { daily: 'Daily', weekly: 'Weekly', monthly: 'Monthly' }
  },
  transfer: {
    title: 'Balance Transfer', description: 'Verify the recipient and fees before sending site balance', totalSent: 'Total sent', totalReceived: 'Total received', totalFee: 'Fees paid', newTransfer: 'New transfer', irreversible: 'Transfers cannot be reversed by users after settlement.', receiverId: 'Recipient user ID', recipient: 'Recipient', amount: 'Amount received', feePreview: 'Fee', total: 'Total debit', memo: 'Message (optional)', continue: 'Verify and continue', success: 'Transfer completed', successWithId: 'Transfer completed, reference #{id}', submit: 'Confirm transfer', failed: 'Transfer failed. Try again later.', validationFailed: 'Could not verify the recipient or fees.', confirmTitle: 'Confirm balance transfer', confirmMessage: 'Review this transfer carefully. It settles immediately after confirmation.', confirmRecipient: 'Recipient: {recipient}', confirmAmount: 'Receives {amount}; fee {fee}; total debit {total}', history: 'Transfer history', historyHint: 'Review outgoing and incoming balance records', historyFailed: 'Could not load transfer history', emptyHistory: 'No transfer records', sent: 'Sent', received: 'Received', toUser: 'To user #{id}', fromUser: 'From user #{id}', status: { completed: 'Completed', frozen: 'Flagged', revoked: 'Reversed' }
  },
  redpacket: {
    title: 'Red Packets', description: 'Create and share a packet code, or claim one from a friend', create: 'Send packet', claim: 'Claim packet', myPackets: 'My packets', sent: 'Sent', received: 'Claimed', sentHistoryHint: 'Review remaining portions, amounts, and expiry', totalAmount: 'Total amount', count: 'Portions', type: 'Distribution', equal: 'Equal', equalHint: 'Every portion has the same amount', random: 'Lucky draw', randomHint: 'The server randomly allocates each portion', memo: 'Message', memoPlaceholder: 'Best wishes', perPacket: 'Estimated per portion', confirmTitle: 'Confirm packet', confirmMessage: 'Send {count} portions totaling {amount}?', createdTitle: 'Packet created', shareHint: 'Share this code so another user can claim it.', createFailed: 'Could not create the packet. Check the amount and count.', claimTitle: 'Enter packet code', claimHint: 'Spaces are trimmed and the code is normalized to uppercase', code: 'Packet code', codePlaceholder: 'Enter packet code', claimSuccess: 'Claimed successfully', claimFailed: 'Could not claim. Check the code and packet status.', historyFailed: 'Could not load packet history', detailFailed: 'Could not load packet details', claimRecords: 'Claims', empty: 'No packet records', remaining: '{remaining}/{total} portions left', detailTitle: 'Packet details', remainingAmount: 'Remaining amount', expiresAt: 'Expires', status: { active: 'Active', expired: 'Expired', exhausted: 'Claimed' }
  }
  ,gameHall: {
    title: 'Game Hall', description: 'Use an isolated DG wallet for on-site games', mainBalance: 'Main balance', dgBalance: 'DG balance', jackpot: 'Jackpot',
    exchangeTitle: 'Balance exchange', exchangeHint: 'Main balance and DG exchange at 1:1 with an auditable transaction record.', toDG: 'Main to DG', toMain: 'DG to main', amount: 'Amount', rate: 'Rate', afterExchange: 'After exchange: main / DG', exchangeAction: 'Confirm exchange', exchangeSuccess: 'Exchange completed', loadFailed: 'Could not load the game hall. Try again.', exchangeFailed: 'Exchange failed. Check your balance and feature availability.', playFailed: 'The round could not be settled. Try again later.',
    safetyTitle: 'Funds and game rules', safetyWallet: 'The DG wallet is isolated from your main balance.', safetySettlement: 'Results are generated and settled atomically by the server.', riskNotice: 'Games can lose DG. Set a reasonable spending limit.',
    slotsTitle: 'Three-reel slots', betRange: 'Bet {min} - {max} DG per round', betAmount: 'Bet amount', serverResult: 'The page only presents the result after server settlement.', playAction: 'Play round', noGames: 'No games are currently available', win: 'Round won', loss: 'No prize this round', push: 'Round tied', payoutSummary: 'Payout {payout} DG · {multiplier}x',
    confirmExchangeTitle: 'Confirm balance exchange', confirmExchangeMessage: 'Exchange {amount} using “{direction}” at 1:1?', transactions: 'Wallet activity', rounds: 'Game rounds', historyFailed: 'Could not load history', emptyHistory: 'No history yet', betValue: 'Bet {value} DG', transactionTypes: { balance_to_dg: 'Main balance deposit', dg_to_balance: 'Return to main balance', bet: 'Game bet', payout: 'Game payout' },
    symbols: { star: 'Star', seven: 'Seven', diamond: 'Diamond', cherry: 'Cherry', bell: 'Bell', lemon: 'Lemon', bar: 'BAR' }
  },
  activityErrors: { featureDisabled: 'This feature is currently unavailable', insufficientBalance: 'Insufficient available balance', limitExceeded: 'The current amount or request limit was exceeded', alreadyClaimed: 'You already claimed this packet', redpacketExpired: 'This packet has expired', redpacketExhausted: 'This packet has been fully claimed', redpacketNotFound: 'Packet code not found', cannotClaimOwn: 'You cannot claim your own packet', duplicateRequest: 'This request is already processing or completed' }
}
