export default {
  checkin: {
    title: 'Daily Check-in', checked: 'Checked in today', todayReward: 'Earned ${amount} today', streakDays: '{days}-day streak',
    rangeHint: 'Reward range ${min} - ${max}', luckTitle: 'Lucky Check-in', luckButton: 'Confirm lucky check-in',
    luckSuccess: '{multiplier}x multiplier, earned ${amount}', luckLoss: '{multiplier}x multiplier, lost ${amount}', luckEven: '1.00x multiplier, no gain or loss',
    betAmount: 'Bet amount', betAmountPlaceholder: 'Enter an amount', multiplierRange: 'Multiplier range ${min}x - ${max}x',
    success: 'Check-in successful!', statusLoadFailed: 'Could not load check-in status', actionFailed: 'Check-in failed. Review the error and try again.',
    checkinType: 'Check-in type', normalCheckin: 'Normal check-in', luckCheckin: 'Lucky check-in',
    blindboxCommon: 'Common', blindboxRare: 'Rare', blindboxEpic: 'Epic', blindboxLegendary: 'Legendary',
    blindboxBalanceReward: 'Balance +${value}', blindboxConcurrencyReward: 'Concurrency +{value}', blindboxSubscriptionReward: '{days}-day subscription',
    blindboxInvitationReward: 'Invitation code x1', blindboxInviteCode: 'Your invitation code', blindboxHistory: 'Blind-box prizes', blindboxHistoryDesc: 'Prizes earned from check-in blind boxes', blindboxDays: ' days',
    page: {
      description: 'Daily rewards, blind-box prizes, and account overview', balance: 'Balance', streak: 'Check-in streak', days: ' days', concurrency: 'Concurrency', blindboxCount: 'Blind boxes',
      noBlindbox: 'No blind-box prizes yet', todayResult: "Today's check-in", todayReward: 'Reward', todayMultiplier: 'Multiplier', todayBlindbox: 'Blind box',
      todayNormal: 'Normal check-in', todayLuck: 'Lucky check-in', todayNoResult: 'Not checked in today', rarityBreakdown: 'Rarity breakdown', blindboxInfo: 'Blind-box rules',
      triggerType: 'Trigger', triggerTotal: 'Total check-ins', triggerStreak: 'Check-in streak', triggerInterval: 'Interval',
      blindboxNextIn: '{days} days until the next blind box', blindboxNextCycle: 'Triggers every {interval} consecutive days', calendarTitle: 'Check-in calendar'
    }
  },
  leaderboard: {
    title: 'Leaderboard', subtitle: 'Explore site activity using consistent ranking rules', empty: 'No ranking data', streakDays: '{days} days', rank: 'Rank {rank}', daysValue: '{value} days', loadFailed: 'Could not load the leaderboard. Try again.', privacyNotice: 'Display names follow the site privacy policy. Rankings are for on-site activity only.',
    balanceSubtitle: '{count} total check-ins', consumptionSubtitle: '{count} requests', checkinSubtitle: '{total} check-ins · Latest {date} · Earned ${reward}', transferSubtitle: '{count} successful transfers',
    filterLabel: 'Leaderboard filters', periodFilterLabel: 'Ranking period', distributionTitle: '{board} distribution', distributionHint: 'Values and shares are calculated from the current page', pageTotal: 'Page total', listedUsers: 'Users', currentPageUsers: '{count} on this page', chartHint: 'Hover a chart segment to view its user, amount, and share', rankingTitle: 'Ranking details', currentPage: 'Page {page}', others: 'Other users', noBoards: 'No leaderboards available', noBoardsHint: 'No leaderboard has been enabled yet. Please check again later.',
    distributionNames: { balance: 'Balance', consumption: 'Consumption', checkin: 'Check-in', transfer: 'Transfer' }, distributionHints: { balance: 'View the amount share of users on the balance leaderboard', consumption: 'View the amount share of all consumers in the current period', checkin: 'View the streak share of users on the check-in leaderboard', transfer: 'View the amount share of all senders in the current period' }, summaryHeaders: { balance: 'Amount', consumption: 'Total amount', checkin: 'Total days', transfer: 'Total amount' },
    columns: { user: 'User', share: 'Share' }, activityHeaders: { balance: 'Check-ins', consumption: 'Requests', checkin: 'Total check-ins', transfer: 'Transfers' }, valueHeaders: { balance: 'Balance', consumption: 'Spend', checkin: 'Streak', transfer: 'Amount sent' },
    tabs: { balance: 'Balance', consumption: 'Consumption', checkin: 'Check-in', transfer: 'Transfers' }, periods: { daily: 'Daily', weekly: 'Weekly', monthly: 'Monthly' }
  },
  transfer: {
    title: 'Balance Transfer', description: 'Verify the recipient and fees before sending site balance', currentBalance: 'Current balance', totalSent: 'Total sent', totalReceived: 'Total received', totalFee: 'Fees paid', newTransfer: 'New transfer', irreversible: 'Transfers cannot be reversed by users after settlement.', receiverId: 'Recipient', receiverPlaceholder: 'Enter email, username, or user ID', receiverResolved: 'Selected {recipient}', receiverSearchFailed: 'Could not search for recipients', receiverNoResults: 'No matching recipient found', receiverSelectRequired: 'Select a recipient from the search results first', recipient: 'Recipient', amount: 'Amount', feePreview: 'Fee', calculateFee: 'Calculate fee', total: 'Total debit', available: 'Available: {amount}', dailyRemaining: 'Daily amount left {amount} · {count} transfers left', memo: 'Message', memoPlaceholder: 'Optional message', continue: 'Verify and continue', success: 'Transfer completed', successWithId: 'Transfer completed, reference #{id}', submit: 'Confirm transfer', failed: 'Transfer failed. Try again later.', validationFailed: 'Could not verify the recipient or fees.', confirmTitle: 'Confirm balance transfer', confirmMessage: 'Review this transfer carefully. It settles immediately after confirmation.', confirmRecipient: 'Recipient: {recipient}', confirmAmount: 'Receives {amount}; fee {fee}; total debit {total}', history: 'Transfer history', historyHint: 'Review outgoing and incoming balance records', historyFailed: 'Could not load transfer history', emptyHistory: 'No transfer records', sent: 'Sent', received: 'Received', toUser: 'To', fromUser: 'From', transferTypes: { direct: 'Balance transfer', redpacket: 'Red packet', batch: 'Batch grant' }, status: { completed: 'Completed', frozen: 'Flagged', revoked: 'Reversed' }
  },
  redpacket: {
    title: 'Red Packet Center', description: 'Send, claim, and share the joy', create: 'Send packet', createHint: 'Send a balance packet to a friend', claim: 'Claim packet', claimHint: 'Enter a code to claim a packet', myPackets: 'My packets', sent: 'Sent', received: 'Claimed', sentHistoryHint: 'Review remaining portions, amounts, and expiry', totalAmount: 'Total amount', count: 'Portions', type: 'Distribution', equal: 'Equal packet', equalHint: 'Every portion has the same amount', random: 'Lucky packet', randomHint: 'The server randomly allocates each portion', memo: 'Message', memoPlaceholder: 'Best wishes', perPacket: 'Estimated per portion', confirmTitle: 'Confirm packet', confirmMessage: 'Send {count} portions totaling {amount}?', createdTitle: 'Packet created', shareHint: 'Share this code so another user can claim it.', createFailed: 'Could not create the packet. Check the amount and count.', claimTitle: 'Enter packet code', code: 'Packet code', codePlaceholder: 'Enter packet code', claimSuccess: 'Claimed successfully', claimFailed: 'Could not claim. Check the code and packet status.', historyFailed: 'Could not load packet history', detailFailed: 'Could not load packet details', claimRecords: 'Claims', bestLuck: 'Best luck', empty: 'No packet records', remaining: '{remaining}/{total} portions left', detailTitle: 'Packet details', remainingAmount: 'Remaining amount', expiresAt: 'Expires', progress: 'Claim progress', validUntil: 'Valid until {date}', status: { active: 'Active', expired: 'Expired', exhausted: 'Claimed' }
  },
  activityErrors: { featureDisabled: 'This feature is currently unavailable', insufficientBalance: 'Insufficient available balance', limitExceeded: 'The current amount or request limit was exceeded', transferDailyLimit: 'The daily transfer amount limit was exceeded', transferDailyCount: 'No transfers remain today', transferSelf: 'You cannot transfer to yourself', transferAmountInvalid: 'The transfer amount is outside the allowed range', receiverNotFound: 'No eligible recipient was found', alreadyClaimed: 'You already claimed this packet', redpacketExpired: 'This packet has expired', redpacketExhausted: 'This packet has been fully claimed', redpacketNotFound: 'Packet code not found', cannotClaimOwn: 'You cannot claim your own packet', duplicateRequest: 'This request is already processing or completed' }
}
